!! The CI Hamiltonian applied to a vector
module test_mqc_ci
   !! Tested against a *model* Hamiltonian rather than a molecule, deliberately.
   !! A one- and two-electron integral set is all the CI needs; where the
   !! numbers came from is the integral transformation's problem, not this
   !! module's. Feeding it something made up isolates the sigma build completely
   !! -- no basis set, no SCF, no orbital optimisation -- so a failure here is
   !! this code and nothing else.
   !!
   !! The model is a Cholesky-style sum, `(pq|rs) = sum_L B_pqL B_rsL` with `B`
   !! symmetric in its first two indices. That is not for realism: it is the
   !! cheapest way to get a tensor with the full eightfold permutational
   !! symmetry that a real ERI set has, which the folding in
   !! `absorb_one_electron` relies on and which a matrix of arbitrary numbers
   !! would not have.
   !!
   !! References are `pyscf.fci.direct_spin1`, on the same model, generated by
   !! building its dense Hamiltonian through `pspace` and diagonalising. Three
   !! spin cases, because the alpha and beta excitation tables are separate
   !! objects and a test with equal electron counts cannot tell them apart.
   use testdrive, only: new_unittest, unittest_type, error_type, check
   use pic_types, only: dp
   use pic_lapack_interfaces, only: pic_syev
   use mqc_error, only: error_t
   use mqc_determinants, only: link_table_t, build_link_table
   use mqc_ci, only: absorb_one_electron, sigma_vector, ci_hamiltonian, ci_diagonal, &
                     apply_excitations, excitations_block, beta_strings_per_block
   implicit none
   private

   public :: collect_mqc_ci_tests

   integer, parameter :: NORB = 4
   integer, parameter :: NCHOL = 3

contains

   subroutine collect_mqc_ci_tests(testsuite)
      type(unittest_type), allocatable, intent(out) :: testsuite(:)

      testsuite = [ &
                  new_unittest("hamiltonian_is_symmetric", test_symmetry), &
                  new_unittest("spectrum_against_pyscf", test_spectrum), &
                  new_unittest("open_shell_against_pyscf", test_open_shell), &
                  new_unittest("sigma_matches_dense_product", test_sigma_consistency), &
                  new_unittest("diagonal_matches_the_matrix", test_diagonal), &
                  new_unittest("blocking_is_exact", test_blocking), &
                  new_unittest("refusals", test_refusals) &
                  ]
   end subroutine collect_mqc_ci_tests

   subroutine model_integrals(h1e, eri)
      !! The model Hamiltonian
      !!
      !! `h_pq = -1/(p+q)` and `B_pqL = 1/(p+q+L)` on zero-based indices, so the
      !! Fortran loops below run from one and subtract. Stated as a formula
      !! rather than a table of numbers so the references can be regenerated:
      !! build the same `h1e` and `eri` in numpy, hand them to
      !! `pyscf.fci.direct_spin1.pspace(h1e, eri, norb, nelec, np=na*nb)`, and
      !! diagonalise what comes back. Every value is the reciprocal of a small
      !! integer, so the two languages agree to the last bit.
      real(dp), allocatable, intent(out) :: h1e(:, :)
      real(dp), allocatable, intent(out) :: eri(:, :, :, :)

      real(dp) :: b(NORB, NORB, NCHOL)
      integer :: p, q, r, s, l

      allocate (h1e(NORB, NORB), eri(NORB, NORB, NORB, NORB))
      do q = 1, NORB
         do p = 1, NORB
            h1e(p, q) = -1.0_dp/real((p - 1) + (q - 1) + 2, dp)
         end do
      end do
      do l = 1, NCHOL
         do q = 1, NORB
            do p = 1, NORB
               b(p, q, l) = 1.0_dp/real((p - 1) + (q - 1) + (l - 1) + 3, dp)
            end do
         end do
      end do

      eri = 0.0_dp
      do s = 1, NORB
         do r = 1, NORB
            do q = 1, NORB
               do p = 1, NORB
                  do l = 1, NCHOL
                     eri(p, q, r, s) = eri(p, q, r, s) + b(p, q, l)*b(r, s, l)
                  end do
               end do
            end do
         end do
      end do
   end subroutine model_integrals

   subroutine model_hamiltonian(n_alpha, n_beta, matrix, err, ok)
      !! The dense CI Hamiltonian of the model, for one spin case
      integer, intent(in) :: n_alpha, n_beta
      real(dp), allocatable, intent(out) :: matrix(:, :)
      type(error_t), intent(inout) :: err
      logical, intent(out) :: ok

      real(dp), allocatable :: h1e(:, :), eri(:, :, :, :), folded(:, :)
      type(link_table_t) :: alpha, beta

      ok = .false.
      call model_integrals(h1e, eri)
      call absorb_one_electron(h1e, eri, n_alpha + n_beta, folded, err)
      if (err%has_error()) return
      call build_link_table(NORB, n_alpha, alpha, err)
      call build_link_table(NORB, n_beta, beta, err)
      if (err%has_error()) return
      call ci_hamiltonian(folded, alpha, beta, matrix, err)
      ok = .not. err%has_error()
      call alpha%destroy()
      call beta%destroy()
   end subroutine model_hamiltonian

   subroutine spectrum(matrix, values)
      !! Every eigenvalue, ascending
      real(dp), intent(in) :: matrix(:, :)
      real(dp), allocatable, intent(out) :: values(:)

      real(dp), allocatable :: work(:, :)
      integer :: info

      allocate (work(size(matrix, 1), size(matrix, 2)), values(size(matrix, 1)))
      work = matrix
      call pic_syev(work, values, jobz="N", uplo="U", info=info)
      deallocate (work)
   end subroutine spectrum

   subroutine test_symmetry(error)
      !! The Hamiltonian comes out symmetric
      !!
      !! Nothing symmetrises it. It is symmetric only if the excitation phases,
      !! the destination addresses and the folding all agree, so this is a real
      !! check on all three and it is the cheapest one available -- a transposed
      !! index or a dropped sign in the scatter shows up here immediately, with
      !! no reference needed.
      type(error_type), allocatable, intent(out) :: error
      type(error_t) :: err
      real(dp), allocatable :: matrix(:, :)
      logical :: ok

      call model_hamiltonian(2, 2, matrix, err, ok)
      call check(error, ok, "the closed-shell Hamiltonian should build")
      if (allocated(error)) return
      call check(error, size(matrix, 1), 36, "six alpha strings times six beta")
      if (allocated(error)) return
      call check(error, maxval(abs(matrix - transpose(matrix))) < 1.0e-13_dp, &
                 "the CI Hamiltonian must be symmetric")
      if (allocated(error)) return
      deallocate (matrix)

      ! And for unequal spins, where the two tables are genuinely different
      ! objects rather than the same one used twice.
      call model_hamiltonian(2, 1, matrix, err, ok)
      call check(error, ok, "the open-shell Hamiltonian should build")
      if (allocated(error)) return
      call check(error, size(matrix, 1), 24, "six alpha strings times four beta")
      if (allocated(error)) return
      call check(error, maxval(abs(matrix - transpose(matrix))) < 1.0e-13_dp, &
                 "it must be symmetric when the spins differ too")
   end subroutine test_symmetry

   subroutine test_spectrum(error)
      !! Four electrons in four orbitals, against PySCF
      type(error_type), allocatable, intent(out) :: error
      type(error_t) :: err
      real(dp), allocatable :: matrix(:, :), values(:)
      logical :: ok
      real(dp) :: trace
      integer :: i

      !> `fci.direct_spin1.pspace` on the same model, diagonalised.
      real(dp), parameter :: LOWEST(4) = [-1.058973188934_dp, -1.057251313930_dp, &
                                          -1.057247805143_dp, -1.054982153731_dp]
      real(dp), parameter :: HIGHEST(2) = [-0.064054916404_dp, -0.003683707490_dp]
      real(dp), parameter :: TRACE_REF = -25.046869362300_dp

      call model_hamiltonian(2, 2, matrix, err, ok)
      call check(error, ok, "the Hamiltonian should build")
      if (allocated(error)) return
      call spectrum(matrix, values)

      ! The ground state is what a CI solver will be asked for.
      call check(error, values(1), LOWEST(1), "the lowest eigenvalue", thr=1.0e-10_dp)
      if (allocated(error)) return

      ! And the rest of the low end, which the lowest alone would not pin down:
      ! roots two and three are 3e-6 apart here, so an implementation that got
      ! the ground state by luck would not also get those.
      do i = 2, 4
         call check(error, values(i), LOWEST(i), "eigenvalue "//char(48 + i), &
                    thr=1.0e-10_dp)
         if (allocated(error)) return
      end do

      call check(error, values(35), HIGHEST(1), "second-highest eigenvalue", &
                 thr=1.0e-10_dp)
      if (allocated(error)) return
      call check(error, values(36), HIGHEST(2), "highest eigenvalue", thr=1.0e-10_dp)
      if (allocated(error)) return

      ! The trace is every eigenvalue at once and is invariant under any
      ! orthogonal change of basis, so it catches a permutation of the
      ! determinant ordering that the individual eigenvalues above would also
      ! survive -- but it catches it in one number, and it is the diagonal of
      ! the Hamiltonian, which is what a Davidson preconditioner will need next.
      trace = 0.0_dp
      do i = 1, size(matrix, 1)
         trace = trace + matrix(i, i)
      end do
      call check(error, trace, TRACE_REF, "the trace of the CI Hamiltonian", &
                 thr=1.0e-9_dp)
   end subroutine test_spectrum

   subroutine test_open_shell(error)
      !! Three electrons, two alpha and one beta, against PySCF
      !!
      !! The case that distinguishes the two excitation tables. With equal
      !! counts the alpha and beta tables are identical and a sigma build that
      !! used one where it meant the other would pass everything above.
      type(error_type), allocatable, intent(out) :: error
      type(error_t) :: err
      real(dp), allocatable :: matrix(:, :), values(:)
      logical :: ok
      real(dp) :: trace
      integer :: i

      real(dp), parameter :: LOWEST(4) = [-1.057243536246_dp, -1.054974372937_dp, &
                                          -1.046406083254_dp, -1.001177615505_dp]
      real(dp), parameter :: TRACE_REF = -14.598956454100_dp

      call model_hamiltonian(2, 1, matrix, err, ok)
      call check(error, ok, "the Hamiltonian should build")
      if (allocated(error)) return
      call check(error, size(matrix, 1), 24, "twenty-four determinants")
      if (allocated(error)) return
      call spectrum(matrix, values)

      do i = 1, 4
         call check(error, values(i), LOWEST(i), "eigenvalue "//char(48 + i), &
                    thr=1.0e-10_dp)
         if (allocated(error)) return
      end do

      trace = 0.0_dp
      do i = 1, size(matrix, 1)
         trace = trace + matrix(i, i)
      end do
      call check(error, trace, TRACE_REF, "the trace", thr=1.0e-9_dp)
   end subroutine test_open_shell

   subroutine test_sigma_consistency(error)
      !! `sigma_vector` agrees with multiplying by the dense matrix
      !!
      !! `ci_hamiltonian` is built out of `sigma_vector`, so this is not
      !! circular only because of what it varies: the dense matrix is assembled
      !! from unit vectors, one determinant at a time, and this applies the same
      !! routine to a vector with every component non-zero. A gather or scatter
      !! that mishandled accumulation -- overwriting where it should add, which
      !! a unit vector cannot reveal because only one term ever lands -- fails
      !! here and passes everything above.
      type(error_type), allocatable, intent(out) :: error
      type(error_t) :: err
      real(dp), allocatable :: h1e(:, :), eri(:, :, :, :), folded(:, :)
      real(dp), allocatable :: matrix(:, :), ci(:, :), sigma(:, :), reference(:)
      type(link_table_t) :: alpha, beta
      integer :: na, nb, ia, ib, idet

      call model_integrals(h1e, eri)
      call absorb_one_electron(h1e, eri, 4, folded, err)
      call build_link_table(NORB, 2, alpha, err)
      call build_link_table(NORB, 2, beta, err)
      call check(error,.not. err%has_error(), "the setup should succeed")
      if (allocated(error)) return
      na = alpha%n_strings
      nb = beta%n_strings

      call ci_hamiltonian(folded, alpha, beta, matrix, err)
      call check(error,.not. err%has_error(), "the dense matrix should build")
      if (allocated(error)) return

      ! Something with no zeros and no symmetry of its own.
      allocate (ci(na, nb), sigma(na, nb))
      do ib = 1, nb
         do ia = 1, na
            ci(ia, ib) = 1.0_dp/real(ia + 2*ib, dp)
         end do
      end do

      call sigma_vector(folded, ci, alpha, beta, sigma, err)
      call check(error,.not. err%has_error(), "the sigma build should succeed")
      if (allocated(error)) return

      reference = matmul(matrix, reshape(ci, [na*nb]))
      do idet = 1, na*nb
         ia = mod(idet - 1, na) + 1
         ib = (idet - 1)/na + 1
         call check(error, abs(sigma(ia, ib) - reference(idet)) < 1.0e-12_dp, &
                    "sigma should equal the dense matrix-vector product")
         if (allocated(error)) return
      end do

      ! The Rayleigh quotient of a normalised vector cannot fall below the
      ! lowest eigenvalue. Cheap, and it is the property a variational solver
      ! depends on.
      call check(error, dot_product(reshape(ci, [na*nb]), reference) &
                 /dot_product(reshape(ci, [na*nb]), reshape(ci, [na*nb])) &
                 > -1.058973188935_dp, &
                 "no vector may have an expectation value below the ground state")

      call alpha%destroy()
      call beta%destroy()
   end subroutine test_sigma_consistency

   subroutine test_diagonal(error)
      !! `ci_diagonal` against the diagonal of the assembled matrix
      !!
      !! The two share no code: one reads Coulomb and exchange integrals off the
      !! raw tensor and sums over occupied orbitals, the other applies the
      !! folded Hamiltonian to unit vectors. They agree only if the folding, the
      !! excitation phases and the Slater rule for a diagonal element all say
      !! the same thing, which makes this a check on the folding as much as on
      !! the diagonal.
      !!
      !! Worth its own test because the diagonal is about to become a
      !! preconditioner, and a wrong preconditioner does not give a wrong
      !! answer -- it gives a correct answer slowly, or no convergence at all,
      !! neither of which points anywhere near here.
      type(error_type), allocatable, intent(out) :: error
      type(error_t) :: err
      real(dp), allocatable :: h1e(:, :), eri(:, :, :, :), folded(:, :)
      real(dp), allocatable :: matrix(:, :), diagonal(:, :)
      type(link_table_t) :: alpha, beta
      integer :: na, nb, ia, ib, idet, case_index
      integer, parameter :: ALPHA_COUNT(3) = [2, 2, 3]
      integer, parameter :: BETA_COUNT(3) = [2, 1, 2]

      do case_index = 1, 3
         call model_integrals(h1e, eri)
         call absorb_one_electron(h1e, eri, ALPHA_COUNT(case_index) &
                                  + BETA_COUNT(case_index), folded, err)
         call build_link_table(NORB, ALPHA_COUNT(case_index), alpha, err)
         call build_link_table(NORB, BETA_COUNT(case_index), beta, err)
         call check(error,.not. err%has_error(), "the setup should succeed")
         if (allocated(error)) return

         call ci_hamiltonian(folded, alpha, beta, matrix, err)
         call ci_diagonal(h1e, eri, alpha, beta, diagonal, err)
         call check(error,.not. err%has_error(), "both routes should succeed")
         if (allocated(error)) return

         na = alpha%n_strings
         nb = beta%n_strings
         call check(error, size(diagonal, 1), na, "one row per alpha string")
         if (allocated(error)) return
         call check(error, size(diagonal, 2), nb, "one column per beta string")
         if (allocated(error)) return

         do idet = 1, na*nb
            ia = mod(idet - 1, na) + 1
            ib = (idet - 1)/na + 1
            call check(error, abs(diagonal(ia, ib) - matrix(idet, idet)) < 1.0e-12_dp, &
                       "the diagonal element of every determinant should agree "// &
                       "with the assembled matrix")
            if (allocated(error)) return
         end do

         call alpha%destroy()
         call beta%destroy()
         deallocate (h1e, eri, folded, matrix, diagonal)
      end do
   end subroutine test_diagonal

   subroutine test_blocking(error)
      !! Assembling the intermediate a block at a time is the same intermediate
      !!
      !! `sigma_vector` and the density matrices no longer build the whole
      !! `(norb^2, n_determinants)` array -- for a full valence CAS(14,14) that
      !! is 18.5 GB, and two of them are needed at once -- so they walk it a
      !! range of beta strings at a time instead. That is only sound if the
      !! blocks partition it exactly, which is what this checks: every block
      !! width from one beta string up to all of them must reassemble into the
      !! array `apply_excitations` returns whole.
      !!
      !! **The narrow width is the one that matters.** The two spins block
      !! differently -- an alpha excitation leaves the beta string alone, while
      !! a beta excitation moves it, so contributions can arrive from source
      !! strings outside the block being filled. A blocking that forgot the
      !! second case would still be right at full width and wrong at every
      !! other, which is exactly the error this shape of test exists to catch.
      type(error_type), allocatable, intent(out) :: error

      type(link_table_t) :: alpha, beta
      type(error_t) :: err
      real(dp), allocatable :: ci(:, :), whole(:, :), piece(:, :), rebuilt(:, :)
      integer, parameter :: NORB = 6, NA_ELEC = 3, NB_ELEC = 2
      integer :: na, nb, npair, ia, ib, wide, first, last, width

      call build_link_table(NORB, NA_ELEC, alpha, err)
      call build_link_table(NORB, NB_ELEC, beta, err)
      call check(error,.not. err%has_error(), "the tables were refused")
      if (allocated(error)) return

      na = alpha%n_strings
      nb = beta%n_strings
      npair = NORB*NORB

      allocate (ci(na, nb))
      do ib = 1, nb
         do ia = 1, na
            ci(ia, ib) = sin(real(3*ia + 5*ib, dp))
         end do
      end do
      ci = ci/sqrt(sum(ci**2))

      call apply_excitations(ci, alpha, beta, whole)
      call check(error, size(whole, 2), na*nb, "the whole intermediate is one "// &
                 "column per determinant")
      if (allocated(error)) return

      allocate (rebuilt(npair, na*nb), piece(npair, na*nb))
      do wide = 1, nb
         rebuilt = 0.0_dp
         do first = 1, nb, wide
            last = min(first + wide - 1, nb)
            width = na*(last - first + 1)
            call excitations_block(ci, alpha, beta, first, last, piece(:, 1:width))
            rebuilt(:, (first - 1)*na + 1:last*na) = piece(:, 1:width)
         end do
         call check(error, maxval(abs(rebuilt - whole)), 0.0_dp, thr=1.0e-13_dp, &
                    more="blocks of this width do not reassemble into the whole "// &
                    "intermediate")
         if (allocated(error)) return
      end do

      ! And the chooser stays inside its own contract: at least one string,
      ! never more than there are.
      call check(error, beta_strings_per_block(npair, na, nb) >= 1, &
                 "a block must cover at least one beta string")
      if (allocated(error)) return
      call check(error, beta_strings_per_block(npair, na, nb) <= nb, &
                 "a block cannot cover more beta strings than exist")
      if (allocated(error)) return
      ! A space large enough to exceed the budget must actually be split, or
      ! the blocking is dead code on the only cases that need it.
      call check(error, beta_strings_per_block(196, 3432, 3432) < 3432, &
                 "a full valence CAS(14,14) must be blocked, not built whole")

      call alpha%destroy()
      call beta%destroy()
   end subroutine test_blocking

   subroutine test_refusals(error)
      !! Shapes that do not describe one active space
      type(error_type), allocatable, intent(out) :: error
      type(error_t) :: err
      real(dp), allocatable :: h1e(:, :), eri(:, :, :, :), folded(:, :)
      real(dp), allocatable :: ci(:, :), sigma(:, :)
      type(link_table_t) :: alpha, beta, wide

      call model_integrals(h1e, eri)

      ! The folding divides by the electron count.
      call absorb_one_electron(h1e, eri, 0, folded, err)
      call check(error, err%has_error(), "an empty active space should be refused")
      if (allocated(error)) return
      call err%clear()

      call absorb_one_electron(h1e, eri, 4, folded, err)
      call build_link_table(NORB, 2, alpha, err)
      call build_link_table(NORB, 2, beta, err)
      call build_link_table(NORB + 1, 2, wide, err)
      call check(error,.not. err%has_error(), "the setup should succeed")
      if (allocated(error)) return

      ! Two tables over different orbital counts are not one active space.
      allocate (ci(alpha%n_strings, beta%n_strings), &
                sigma(alpha%n_strings, beta%n_strings))
      ci = 0.0_dp
      call sigma_vector(folded, ci, alpha, wide, sigma, err)
      call check(error, err%has_error(), &
                 "excitation tables over different orbital counts should be refused")
      if (allocated(error)) return
      call err%clear()

      ! A vector that is not the size of the determinant space.
      deallocate (ci, sigma)
      allocate (ci(alpha%n_strings + 1, beta%n_strings), &
                sigma(alpha%n_strings + 1, beta%n_strings))
      ci = 0.0_dp
      call sigma_vector(folded, ci, alpha, beta, sigma, err)
      call check(error, err%has_error(), &
                 "a vector of the wrong shape should be refused rather than "// &
                 "silently read past its end")
      call err%clear()

      call alpha%destroy()
      call beta%destroy()
      call wide%destroy()
   end subroutine test_refusals

end module test_mqc_ci

program tester
   use, intrinsic :: iso_fortran_env, only: error_unit
   use testdrive, only: run_testsuite, new_testsuite, testsuite_type
   use test_mqc_ci, only: collect_mqc_ci_tests
   implicit none
   integer :: stat, is
   type(testsuite_type), allocatable :: testsuites(:)
   character(len=*), parameter :: fmt = '("#", *(1x, a))'

   stat = 0
   testsuites = [new_testsuite("mqc_ci", collect_mqc_ci_tests)]

   do is = 1, size(testsuites)
      write (error_unit, fmt) "Testing:", testsuites(is)%name
      call run_testsuite(testsuites(is)%collect, error_unit, stat)
   end do

   if (stat > 0) then
      write (error_unit, "(i0, 1x, a)") stat, "test(s) failed!"
      error stop
   end if
end program tester
