append_result_to_batch – metalquicha
append_result_to_batch Subroutine
10 statements
Source File
public subroutine append_result_to_batch(item_idx, result, batch_count, batch_ids, batch_results)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: item_idx
type(calculation_result_t), intent(in) :: result
integer(kind=int32), intent(inout) :: batch_count
integer(kind=int64), intent(inout) :: batch_ids(:)
type(calculation_result_t), intent(inout) :: batch_results(:)
Called by
Source Code
   subroutine append_result_to_batch(item_idx, result, batch_count, batch_ids, batch_results)
      integer(int64), intent(in) :: item_idx
      type(calculation_result_t), intent(in) :: result
      integer(int32), intent(inout) :: batch_count
      integer(int64), intent(inout) :: batch_ids(:)
      type(calculation_result_t), intent(inout) :: batch_results(:)
      batch_count = batch_count + 1
      batch_ids(batch_count) = item_idx
      batch_results(batch_count) = result
   end subroutine append_result_to_batch
Call graph
handle_local_worker_results_to_batch calls append_result_to_batch
handle_node_results_to_batch calls append_result_to_batch
gmbe_group_global_coordinator calls handle_local_worker_results_to_batch, handle_node_results_to_batch
group_global_coordinator_impl calls handle_local_worker_results_to_batch, handle_node_results_to_batch
gmbe_run_distributed calls gmbe_group_global_coordinator
node_coordinator_impl calls group_global_coordinator_impl
node_coordinator calls node_coordinator_impl, node_coordinator