build_fragment_payload_from_row – metalquicha
build_fragment_payload_from_row Subroutine
10 statements
Source File
subroutine build_fragment_payload_from_row(polymer_row, fragment_type, fragment_size, fragment_indices)
Build fragment payload arrays for a given polymer row. Caller owns the returned fragment_indices and must deallocate it.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: polymer_row(:)
integer(kind=int32), intent(out) :: fragment_type
integer(kind=int32), intent(out) :: fragment_size
integer, intent(out), allocatable :: fragment_indices(:)
Called by
Source Code
   subroutine build_fragment_payload_from_row(polymer_row, fragment_type, fragment_size, fragment_indices)
      !! Build fragment payload arrays for a given polymer row.
      !! Caller owns the returned fragment_indices and must deallocate it.
      integer, intent(in) :: polymer_row(:)
      integer(int32), intent(out) :: fragment_type
      integer(int32), intent(out) :: fragment_size
      integer, allocatable, intent(out) :: fragment_indices(:)
      fragment_size = count(polymer_row > 0)
      allocate (fragment_indices(fragment_size))
      fragment_indices = polymer_row(1:fragment_size)
      fragment_type = FRAGMENT_TYPE_MONOMERS
   end subroutine build_fragment_payload_from_row
Call graph
send_fragment_payload_from_row calls build_fragment_payload_from_row
handle_group_node_requests calls send_fragment_payload_from_row
handle_local_worker_requests_group calls send_fragment_payload_from_row
global_coordinator_impl calls handle_group_node_requests, handle_local_worker_requests_group
group_global_coordinator_impl calls handle_group_node_requests, handle_local_worker_requests_group
global_coordinator calls global_coordinator_impl, global_coordinator
node_coordinator_impl calls group_global_coordinator_impl
node_coordinator calls node_coordinator_impl