calculate_monomer_distance – metalquicha
calculate_monomer_distance Function
51 statements
Source File
public pure function calculate_monomer_distance(sys_geom, monomer_indices) result(min_distance)
Calculate minimal atomic distance between monomers in a fragment For single monomer (size 1), returns 0.0 For multi-monomer fragments, returns minimal distance between atoms in different monomers Result is in Angstrom
Arguments
Type Intent Optional Attributes Name
type(system_geometry_t), intent(in) :: sys_geom
integer, intent(in) :: monomer_indices(:)
Return Value real(kind=dp)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: atom_end_i
integer, private :: atom_end_j
integer, private :: atom_start_i
integer, private :: atom_start_j
real(kind=dp), private :: dist
real(kind=dp), private :: dx
real(kind=dp), private :: dy
real(kind=dp), private :: dz
integer, private :: i
integer, private :: iatom
logical, private :: is_variable_size
integer, private :: j
integer, private :: jatom
integer, private :: mon_i
integer, private :: mon_j
integer, private :: n_monomers
Source Code
   pure function calculate_monomer_distance(sys_geom, monomer_indices) result(min_distance)
      !! Calculate minimal atomic distance between monomers in a fragment
      !! For single monomer (size 1), returns 0.0
      !! For multi-monomer fragments, returns minimal distance between atoms in different monomers
      !! Result is in Angstrom
      type(system_geometry_t), intent(in) :: sys_geom
      integer, intent(in) :: monomer_indices(:)
      real(dp) :: min_distance
      integer :: n_monomers, i, j, iatom, jatom
      integer :: mon_i, mon_j
      integer :: atom_start_i, atom_end_i, atom_start_j, atom_end_j
      real(dp) :: dist, dx, dy, dz
      logical :: is_variable_size
      n_monomers = size(monomer_indices)
      ! Monomers have distance 0
      if (n_monomers == 1) then
         min_distance = 0.0_dp
         return
      end if
      ! Check if we have variable-sized fragments
      is_variable_size = allocated(sys_geom%fragment_sizes)
      ! Initialize with huge value
      min_distance = huge(1.0_dp)
      ! Loop over all pairs of monomers
      do i = 1, n_monomers - 1
         mon_i = monomer_indices(i)
         do j = i + 1, n_monomers
            mon_j = monomer_indices(j)
            if (is_variable_size) then
               ! Variable-sized fragments
               do iatom = 1, sys_geom%fragment_sizes(mon_i)
                  atom_start_i = sys_geom%fragment_atoms(iatom, mon_i) + 1  ! Convert to 1-indexed
                  do jatom = 1, sys_geom%fragment_sizes(mon_j)
                     atom_start_j = sys_geom%fragment_atoms(jatom, mon_j) + 1  ! Convert to 1-indexed
                     ! Calculate distance (coordinates in Bohr)
                     dx = sys_geom%coordinates(1, atom_start_i) - sys_geom%coordinates(1, atom_start_j)
                     dy = sys_geom%coordinates(2, atom_start_i) - sys_geom%coordinates(2, atom_start_j)
                     dz = sys_geom%coordinates(3, atom_start_i) - sys_geom%coordinates(3, atom_start_j)
                     dist = sqrt(dx*dx + dy*dy + dz*dz)
                     if (dist < min_distance) min_distance = dist
                  end do
               end do
            else
               ! Fixed-sized monomers
               atom_start_i = (mon_i - 1)*sys_geom%atoms_per_monomer + 1
               atom_end_i = mon_i*sys_geom%atoms_per_monomer
               atom_start_j = (mon_j - 1)*sys_geom%atoms_per_monomer + 1
               atom_end_j = mon_j*sys_geom%atoms_per_monomer
               ! Loop over all atom pairs
               do iatom = atom_start_i, atom_end_i
                  do jatom = atom_start_j, atom_end_j
                     ! Calculate distance (coordinates in Bohr)
                     dx = sys_geom%coordinates(1, iatom) - sys_geom%coordinates(1, jatom)
                     dy = sys_geom%coordinates(2, iatom) - sys_geom%coordinates(2, jatom)
                     dz = sys_geom%coordinates(3, iatom) - sys_geom%coordinates(3, jatom)
                     dist = sqrt(dx*dx + dy*dy + dz*dz)
                     if (dist < min_distance) min_distance = dist
                  end do
               end do
            end if
         end do
      end do
      ! Convert from Bohr to Angstrom
      min_distance = to_angstrom(min_distance)
   end function calculate_monomer_distance
Call graph
calculate_monomer_distance calls to_angstrom
build_fragment_from_indices calls calculate_monomer_distance
fragment_should_be_screened calls calculate_monomer_distance
apply_distance_screening calls fragment_should_be_screened
compute_gmbe calls build_fragment_from_indices
map_fragment_to_system_dipole_derivatives calls build_fragment_from_indices
map_fragment_to_system_gradient calls build_fragment_from_indices
map_fragment_to_system_hessian calls build_fragment_from_indices
node_worker_impl calls build_fragment_from_indices
serial_fragment_processor calls build_fragment_from_indices, compute_mbe, serial_fragment_processor
compute_mbe calls map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives
compute_mbe_gradient calls map_fragment_to_system_gradient
compute_mbe_hessian calls map_fragment_to_system_hessian
node_worker calls node_worker_impl, node_worker
run_fragmented_calculation calls apply_distance_screening
global_coordinator_impl calls compute_mbe
mbe_run_serial calls serial_fragment_processor
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
global_coordinator calls global_coordinator_impl
gmbe_run_distributed calls node_worker
mbe_run_distributed calls node_worker
run_multi_molecule_calculations calls run_calculation
main calls run_calculation