compute_mbe_energy – metalquicha
compute_mbe_energy Subroutine
51 statements
Source File
private subroutine compute_mbe_energy(polymers, fragment_count, max_level, energies, total_energy)
Uses
pic_logger
Compute the many-body expansion (MBE) energy Total = sum(E(i)) + sum(deltaE(ij)) + sum(deltaE(ijk)) + … General n-body correction: deltaE(i1,i2,…,in) = E(i1,i2,…,in) - sum of all lower-order terms Uses int64 for fragment_count to handle large fragment counts that overflow int32. Detailed breakdown is printed only if logger level is verbose or higher.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: polymers(:,:)
integer(kind=int64), intent(in) :: fragment_count
integer, intent(in) :: max_level
real(kind=dp), intent(in) :: energies(:)
real(kind=dp), intent(out) :: total_energy
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: body_level
integer, private :: current_log_level
real(kind=dp), private :: delta_E
real(kind=dp), private, allocatable :: delta_energies(:)
logical, private :: do_detailed_print
integer, private :: fragment_size
integer(kind=int64), private :: i
real(kind=dp), private, allocatable :: sum_by_level(:)
Source Code
   subroutine compute_mbe_energy(polymers, fragment_count, max_level, energies, total_energy)
      !! Compute the many-body expansion (MBE) energy
      !! Total = sum(E(i)) + sum(deltaE(ij)) + sum(deltaE(ijk)) + ...
      !! General n-body correction:
      !! deltaE(i1,i2,...,in) = E(i1,i2,...,in) - sum of all lower-order terms
      !! Uses int64 for fragment_count to handle large fragment counts that overflow int32.
      !! Detailed breakdown is printed only if logger level is verbose or higher.
      use pic_logger, only: verbose_level
      integer(int64), intent(in) :: fragment_count
      integer, intent(in) :: polymers(:, :), max_level
      real(dp), intent(in) :: energies(:)
      real(dp), intent(out) :: total_energy
      integer(int64) :: i
      integer :: fragment_size, body_level, current_log_level
      real(dp), allocatable :: sum_by_level(:), delta_energies(:)
      real(dp) :: delta_E
      logical :: do_detailed_print
      ! Query logger to decide if we should print detailed breakdown
      call logger%configuration(level=current_log_level)
      do_detailed_print = (current_log_level >= verbose_level)
      allocate (sum_by_level(max_level))
      allocate (delta_energies(fragment_count))
      sum_by_level = 0.0_dp
      delta_energies = 0.0_dp
      ! Sum over all fragments by their size
      do i = 1_int64, fragment_count
         fragment_size = count(polymers(i, :) > 0)
         if (fragment_size == 1) then
            ! 1-body terms: just the monomer energies
            delta_E = energies(i)
            delta_energies(i) = delta_E
            sum_by_level(1) = sum_by_level(1) + delta_E
         else if (fragment_size >= 2 .and. fragment_size <= max_level) then
            ! n-body corrections for n >= 2
            delta_E = compute_delta_nbody(polymers(i, 1:fragment_size), polymers, energies, &
                                          fragment_count, fragment_size)
            delta_energies(i) = delta_E
            sum_by_level(fragment_size) = sum_by_level(fragment_size) + delta_E
         end if
      end do
      total_energy = sum(sum_by_level)
      ! Print text summary to console
      call logger%info("MBE Energy breakdown:")
      do body_level = 1, max_level
         if (abs(sum_by_level(body_level)) > 1e-15_dp) then
            block
               character(len=256) :: energy_line
               write (energy_line, '(a,i0,a,f20.10)') "  ", body_level, "-body:  ", sum_by_level(body_level)
               call logger%info(trim(energy_line))
            end block
         end if
      end do
      block
         character(len=256) :: total_line
         write (total_line, '(a,f20.10)') "  Total:   ", total_energy
         call logger%info(trim(total_line))
      end block
      ! Print detailed breakdown if requested
      if (do_detailed_print) then
         call print_detailed_breakdown(polymers, fragment_count, max_level, energies, delta_energies)
      end if
      ! Always write JSON file for machine-readable output
      call print_detailed_breakdown_json(polymers, fragment_count, max_level, energies, delta_energies, &
                                         sum_by_level, total_energy)
      deallocate (sum_by_level, delta_energies)
   end subroutine compute_mbe_energy
Call graph
compute_mbe_energy calls configuration, info, compute_delta_nbody, print_detailed_breakdown, print_detailed_breakdown_json
compute_delta_nbody calls find_fragment_index, generate_and_subtract_subsets
print_detailed_breakdown calls header, level_name, get_body_level_name, verbose, warning
print_detailed_breakdown_json calls info, error, get_body_level_name, warning
find_fragment_index calls error
generate_and_subtract_subsets calls compute_delta_nbody, find_fragment_index, next_combination
global_coordinator calls compute_mbe_energy
run_fragmented_calculation calls global_coordinator
run_calculation calls run_fragmented_calculation
main calls run_calculation