compute_mbe_energy_gradient – metalquicha
compute_mbe_energy_gradient Subroutine
105 statements
Source File
public subroutine compute_mbe_energy_gradient(polymers, fragment_count, max_level, results, sys_geom, total_energy, total_gradient, bonds)
Uses
mqc_config_parser
mqc_result_types
Compute both MBE energy and gradient in a single pass This is more efficient than calling compute_mbe_energy and compute_mbe_gradient separately as it only builds the lookup table once and processes all fragments in one loop
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: polymers(:,:)
integer(kind=int64), intent(in) :: fragment_count
integer, intent(in) :: max_level
type(calculation_result_t), intent(in) :: results(:)
type(system_geometry_t), intent(in) :: sys_geom
real(kind=dp), intent(out) :: total_energy
real(kind=dp), intent(out) :: total_gradient(:,:)
(3, total_atoms)
type(bond_t), intent(in), optional :: bonds(:)
Bond information for caps
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: body_level
integer, private :: current_log_level
real(kind=dp), private :: delta_E
real(kind=dp), private, allocatable :: delta_energies(:)
real(kind=dp), private, allocatable :: delta_gradients(:,:,:)
(3, total_atoms, fragment_count)
logical, private :: do_detailed_print
real(kind=dp), private, allocatable :: energies(:)
integer, private :: fragment_size
integer(kind=int64), private :: i
integer, private :: iatom
type(fragment_lookup_t), private :: lookup
type(timer_type), private :: lookup_timer
real(kind=dp), private, allocatable :: sum_by_level(:)
Source Code
   subroutine compute_mbe_energy_gradient(polymers, fragment_count, max_level, results, sys_geom, &
                                          total_energy, total_gradient, bonds)
      !! Compute both MBE energy and gradient in a single pass
      !! This is more efficient than calling compute_mbe_energy and compute_mbe_gradient separately
      !! as it only builds the lookup table once and processes all fragments in one loop
      use mqc_result_types, only: calculation_result_t
      use mqc_config_parser, only: bond_t
      integer(int64), intent(in) :: fragment_count
      integer, intent(in) :: polymers(:, :), max_level
      type(calculation_result_t), intent(in) :: results(:)
      type(system_geometry_t), intent(in) :: sys_geom
      real(dp), intent(out) :: total_energy
      real(dp), intent(out) :: total_gradient(:, :)  !! (3, total_atoms)
      type(bond_t), intent(in), optional :: bonds(:)  !! Bond information for caps
      integer(int64) :: i
      integer :: fragment_size, body_level, current_log_level, iatom
      real(dp), allocatable :: sum_by_level(:), delta_energies(:), energies(:)
      real(dp), allocatable :: delta_gradients(:, :, :)  !! (3, total_atoms, fragment_count)
      real(dp) :: delta_E
      logical :: do_detailed_print
      type(fragment_lookup_t) :: lookup
      type(timer_type) :: lookup_timer
      ! Validate that all fragments have gradients
      do i = 1_int64, fragment_count
         if (.not. results(i)%has_gradient) then
            call logger%error("Fragment "//to_char(i)//" does not have gradient!")
            error stop "Missing gradient in compute_mbe_energy_gradient"
         end if
      end do
      call logger%configuration(level=current_log_level)
      do_detailed_print = (current_log_level >= verbose_level)
      ! Allocate arrays for energy
      allocate (sum_by_level(max_level))
      allocate (delta_energies(fragment_count))
      allocate (energies(fragment_count))
      sum_by_level = 0.0_dp
      delta_energies = 0.0_dp
      ! Extract total energies from results
      do i = 1_int64, fragment_count
         energies(i) = results(i)%energy%total()
      end do
      ! Allocate arrays for gradient
      allocate (delta_gradients(3, sys_geom%total_atoms, fragment_count))
      delta_gradients = 0.0_dp
      total_gradient = 0.0_dp
      ! Build hash table for fast fragment lookups (shared for both energy and gradient)
      call lookup_timer%start()
      call lookup%init(fragment_count)
      do i = 1_int64, fragment_count
         fragment_size = count(polymers(i, :) > 0)
         call lookup%insert(polymers(i, :), fragment_size, i)
      end do
      call lookup_timer%stop()
      call logger%debug("Time to build lookup table: "//to_char(lookup_timer%get_elapsed_time())//" s")
      call logger%debug("Hash table size: "//to_char(lookup%table_size)// &
                        ", entries: "//to_char(lookup%n_entries))
      ! Bottom-up computation: process fragments by size (1-body, 2-body, 3-body, etc.)
      ! Process by n-mer level to ensure all subsets are computed before they're needed
      do body_level = 1, max_level
         do i = 1_int64, fragment_count
            fragment_size = count(polymers(i, :) > 0)
            ! Only process fragments of the current body_level
            if (fragment_size /= body_level) cycle
            if (fragment_size == 1) then
               ! 1-body: deltaE = E, deltaG = G (no subsets to subtract)
               delta_energies(i) = energies(i)
               sum_by_level(1) = sum_by_level(1) + delta_energies(i)
               ! Map fragment gradient to system coordinates
               call map_fragment_to_system_gradient(results(i)%gradient, polymers(i, 1:fragment_size), &
                                                    sys_geom, delta_gradients(:, :, i), bonds)
            else if (fragment_size >= 2 .and. fragment_size <= max_level) then
               ! n-body: deltaE = E - sum(all subset deltaEs), deltaG = G - sum(all subset deltaGs)
               ! Energy delta
               delta_E = compute_mbe(i, polymers(i, 1:fragment_size), lookup, &
                                     energies, delta_energies, fragment_size)
               delta_energies(i) = delta_E
               sum_by_level(fragment_size) = sum_by_level(fragment_size) + delta_E
               ! Gradient delta
               call compute_mbe_gradient(i, polymers(i, 1:fragment_size), lookup, &
                                         results, delta_gradients, fragment_size, sys_geom, bonds)
            end if
         end do
      end do
      ! Clean up lookup table
      call lookup%destroy()
      ! Compute total energy
      total_energy = sum(sum_by_level)
      ! Compute total gradient
      do i = 1_int64, fragment_count
         fragment_size = count(polymers(i, :) > 0)
         if (fragment_size <= max_level) then
            total_gradient = total_gradient + delta_gradients(:, :, i)
         end if
      end do
      ! Print energy breakdown
      call logger%info("MBE Energy breakdown:")
      do body_level = 1, max_level
         if (abs(sum_by_level(body_level)) > 1e-15_dp) then
            block
               character(len=256) :: energy_line
               write (energy_line, '(a,i0,a,f20.10)') "  ", body_level, "-body:  ", sum_by_level(body_level)
               call logger%info(trim(energy_line))
            end block
         end if
      end do
      block
         character(len=256) :: total_line
         write (total_line, '(a,f20.10)') "  Total:   ", total_energy
         call logger%info(trim(total_line))
      end block
      ! Print gradient info
      call logger%info("MBE gradient computation completed")
      call logger%info("  Total gradient norm: "//to_char(sqrt(sum(total_gradient**2))))
      ! Print detailed gradient if verbose and small system
      if (current_log_level >= info_level .and. sys_geom%total_atoms < 100) then
         call logger%info(" ")
         call logger%info("Total MBE Gradient (Hartree/Bohr):")
         do iatom = 1, sys_geom%total_atoms
            block
               character(len=256) :: grad_line
               write (grad_line, '(a,i5,a,3f20.12)') "  Atom ", iatom, ": ", &
                  total_gradient(1, iatom), total_gradient(2, iatom), total_gradient(3, iatom)
               call logger%info(trim(grad_line))
            end block
         end do
         call logger%info(" ")
      end if
      ! Print detailed breakdown if requested
      if (do_detailed_print) then
         call print_detailed_breakdown(polymers, fragment_count, max_level, energies, delta_energies)
      end if
      ! Always write JSON file for machine-readable output (include gradient)
      call print_detailed_breakdown_json(polymers, fragment_count, max_level, energies, delta_energies, &
                                         sum_by_level, total_energy, total_gradient, results=results)
      deallocate (sum_by_level, delta_energies, energies, delta_gradients)
   end subroutine compute_mbe_energy_gradient
Call graph
compute_mbe_energy_gradient calls configuration, debug, error, get_elapsed_time, info, compute_mbe, compute_mbe_gradient, energy_total, fragment_lookup_destroy, fragment_lookup_init, fragment_lookup_insert, map_fragment_to_system_gradient, print_detailed_breakdown, print_detailed_breakdown_json, start, to_char
compute_mbe calls error, fragment_lookup_find, get_next_combination
compute_mbe_gradient calls map_fragment_to_system_gradient, fragment_lookup_find, get_next_combination
energy_total calls mp2_total
fragment_lookup_init calls next_prime_internal
fragment_lookup_insert calls fnv_1a_hash, sort
map_fragment_to_system_gradient calls configuration, debug, build_fragment_from_indices, fragment_destroy, redistribute_cap_gradients
print_detailed_breakdown calls header, level_name, get_frag_level_name, verbose, warning
print_detailed_breakdown_json calls error, info, get_basename, get_frag_level_name, get_output_json_filename, warning
build_fragment_from_indices calls add_hydrogen_caps, calculate_monomer_distance, check_duplicate_atoms, count_hydrogen_caps, fragment_compute_nelec
fragment_destroy calls basis_set_destroy
fragment_lookup_find calls fnv_1a_hash, sort, arrays_equal_internal
basis_set_destroy calls atomic_basis_destroy
calculate_monomer_distance calls to_angstrom
check_duplicate_atoms calls error, to_char, element_number_to_symbol
atomic_basis_destroy calls cgto_destroy
global_coordinator calls compute_mbe_energy_gradient
serial_fragment_processor calls compute_mbe_energy_gradient
run_fragmented_calculation calls global_coordinator, serial_fragment_processor
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations