energy_reset – metalquicha
energy_reset Subroutine
6 statements
Source File
private subroutine energy_reset(this)
Reset all energy components to zero
Type Bound
energy_t
Arguments
Type Intent Optional Attributes Name
class(energy_t), intent(inout) :: this
Calls
Called by
Source Code
   subroutine energy_reset(this)
      !! Reset all energy components to zero
      class(energy_t), intent(inout) :: this
      this%scf = 0.0_dp
      call this%mp2%reset()
      call this%cc%reset()
   end subroutine energy_reset
Call graph
energy_reset calls mp2_reset
do_fragment_work calls energy_reset, do_fragment_work
result_reset calls energy_reset
result_destroy calls result_reset
compute_energy_and_forces calls result_destroy
flush_group_results calls result_destroy
handle_local_worker_results_to_batch calls result_destroy, flush_group_results
handle_node_results_to_batch calls result_destroy, flush_group_results
hessian_coordinator calls result_destroy, hessian_coordinator
hessian_worker calls result_destroy, hessian_worker
node_worker_impl calls do_fragment_work
serial_fragment_processor calls do_fragment_work, serial_fragment_processor
serial_gmbe_pie_processor calls do_fragment_work
unfragmented_calculation calls do_fragment_work, result_destroy, unfragmented_calculation
xtb_calc_hessian calls result_destroy
gmbe_group_global_coordinator calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
gmbe_run_serial calls serial_gmbe_pie_processor
group_global_coordinator_impl calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
node_worker calls node_worker_impl, node_worker
distributed_unfragmented_hessian calls hessian_coordinator, hessian_worker
gmbe_run_distributed calls gmbe_group_global_coordinator
mbe_run_serial calls serial_fragment_processor
node_coordinator_impl calls group_global_coordinator_impl
run_unfragmented_calculation calls unfragmented_calculation