error_get_message – metalquicha
error_get_message Function
9 statements
Source File
private pure function error_get_message(this) result(message)
Get the error message (without stack trace)
Type Bound
error_t
Arguments
Type Intent Optional Attributes Name
class(error_t), intent(in) :: this
Return Value character(len=:), allocatable
Called by
Source Code
   pure function error_get_message(this) result(message)
      !! Get the error message (without stack trace)
      class(error_t), intent(in) :: this
      character(len=:), allocatable :: message
      if (allocated(this%message)) then
         message = this%message
      else
         message = ""
      end if
   end function error_get_message
Call graph
build_molecular_basis calls error_get_message
handle_group_results calls error_get_message
handle_local_worker_results calls error_get_message
handle_local_worker_results_to_batch calls error_get_message
handle_node_results calls error_get_message
handle_node_results_to_batch calls error_get_message
hessian_worker calls error_get_message, hessian_worker
node_coordinator_impl calls error_get_message, group_global_coordinator_impl
run_fragmented_calculation calls error_get_message
serial_fragment_processor calls error_get_message, serial_fragment_processor
serial_gmbe_pie_processor calls error_get_message
unfragmented_calculation calls error_get_message, unfragmented_calculation
main calls error_get_message, run_calculation, run_multi_molecule_calculations
global_coordinator_impl calls handle_group_results, handle_local_worker_results, handle_node_results
gmbe_group_global_coordinator calls handle_local_worker_results_to_batch, handle_node_results_to_batch
gmbe_pie_coordinator calls handle_group_results, handle_local_worker_results, handle_node_results
gmbe_run_serial calls serial_gmbe_pie_processor
group_global_coordinator_impl calls handle_local_worker_results_to_batch, handle_node_results_to_batch
node_coordinator calls node_coordinator_impl, node_coordinator
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation
compute_energy_and_forces calls run_calculation
distributed_unfragmented_hessian calls hessian_worker, distributed_unfragmented_hessian
global_coordinator calls global_coordinator_impl, global_coordinator
gmbe_run_distributed calls gmbe_group_global_coordinator, gmbe_pie_coordinator, node_coordinator
mbe_run_serial calls serial_fragment_processor
run_multi_molecule_calculations calls run_calculation
run_unfragmented_calculation calls unfragmented_calculation, distributed_unfragmented_hessian
mbe_run_distributed calls node_coordinator, global_coordinator