error_set – metalquicha
error_set Subroutine
8 statements
Source File
private pure subroutine error_set(this, code, message)
Set an error with code and message Resets the stack trace
Type Bound
error_t
Arguments
Type Intent Optional Attributes Name
class(error_t), intent(inout) :: this
integer, intent(in) :: code
character(len=*), intent(in) :: message
Called by
Source Code
   pure subroutine error_set(this, code, message)
      !! Set an error with code and message
      !! Resets the stack trace
      class(error_t), intent(inout) :: this
      integer, intent(in) :: code
      character(len=*), intent(in) :: message
      this%code = code
      this%message = trim(message)
      this%stack_depth = 0  ! Reset stack when setting new error
   end subroutine error_set
Call graph
build_molecular_basis calls error_set, parse_element_basis
check_duplicate_atoms calls error_set
check_fragment_overlap calls error_set
config_to_system_geometry calls error_set, molecule_to_system_geometry, geometry_to_system_fragmented
count_shells_for_element calls error_set
do_fragment_work calls error_set, do_fragment_work
extract_element calls error_set
fill_element_basis calls error_set
find_basis_file calls error_set
fragment_lookup_insert calls error_set
gmbe_enumerate_pie_terms calls error_set, dfs_pie_accumulate
grow_pie_storage calls error_set
initialize_system_geometry calls error_set, read_xyz_file
molecule_to_system_geometry calls error_set, initialize_fragmented_system
open_basis_file calls error_set
parse_aimd_section calls error_set, parse_aimd_section
parse_command_line calls error_set
parse_connectivity_generic calls error_set, skip_to_end, parse_connectivity_generic
parse_driver_section calls error_set, parse_driver_section
parse_element_basis calls error_set, count_shells_for_element, fill_element_basis
parse_fragment calls error_set, parse_indices_line
parse_fragmentation_section calls error_set, validate_cutoffs, parse_fragmentation_section
parse_fragments_generic calls error_set, parse_fragment, skip_to_end, parse_fragments_generic
parse_geometry_generic calls error_set, parse_geometry_generic
parse_hessian_section calls error_set, parse_hessian_section
parse_indices_line calls error_set
parse_model_section calls error_set, parse_model_section
parse_molecules_section calls error_set, parse_single_molecule, skip_to_end, parse_molecules_section
parse_scf_section calls error_set, parse_scf_section
parse_schema_section calls error_set, parse_schema_section
parse_single_molecule calls error_set, skip_to_end, parse_molecule_connectivity, parse_molecule_fragments, parse_molecule_geometry, parse_molecule_structure
parse_structure_generic calls error_set, parse_structure_generic
parse_system_section calls error_set, parse_system_section
parse_xtb_section calls error_set, parse_xtb_section
read_mqc_file calls error_set, skip_to_end, parse_aimd_section, parse_driver_section, parse_fragmentation_section, parse_hessian_section, parse_model_section, parse_molecules_section, parse_scf_section, parse_schema_section, parse_system_section, parse_xtb_section, parse_connectivity_section, parse_fragments_section, parse_geometry_section, parse_structure_section
read_xyz_file calls error_set, read_xyz_string
read_xyz_string calls error_set
skip_to_end calls error_set
validate_cutoffs calls error_set
xtb_calc_energy calls error_set
xtb_calc_gradient calls error_set
xtb_calc_hessian calls error_set, xtb_calc_gradient
build_fragment_from_atom_list calls check_duplicate_atoms
build_fragment_from_indices calls check_duplicate_atoms
build_mbe_lookup_table calls fragment_lookup_insert
dfs_pie_accumulate calls grow_pie_storage, dfs_pie_accumulate
initialize_fragmented_system calls check_fragment_overlap
run_fragmented_calculation calls gmbe_enumerate_pie_terms
run_multi_molecule_calculations calls config_to_system_geometry, run_calculation
unfragmented_calculation calls check_duplicate_atoms, do_fragment_work, unfragmented_calculation
main calls config_to_system_geometry, read_mqc_file, run_multi_molecule_calculations, run_calculation
compute_gmbe calls build_fragment_from_indices, process_intersection_derivatives
compute_mbe calls build_mbe_lookup_table, map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian
geometry_to_system_fragmented calls initialize_fragmented_system
gmbe_pie_coordinator calls build_fragment_from_atom_list
map_fragment_to_system_dipole_derivatives calls build_fragment_from_indices
map_fragment_to_system_gradient calls build_fragment_from_indices
map_fragment_to_system_hessian calls build_fragment_from_indices
node_worker_impl calls do_fragment_work, build_fragment_from_atom_list, build_fragment_from_indices
parse_connectivity_section calls parse_connectivity_generic, parse_connectivity_section
parse_fragments_section calls parse_fragments_generic, parse_fragments_section
parse_geometry_section calls parse_geometry_generic, parse_geometry_section
parse_molecule_connectivity calls parse_connectivity_generic
parse_molecule_fragments calls parse_fragments_generic
parse_molecule_geometry calls parse_geometry_generic
parse_molecule_structure calls parse_structure_generic
parse_structure_section calls parse_structure_generic, parse_structure_section
process_intersection_derivatives calls build_fragment_from_atom_list
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation
serial_fragment_processor calls do_fragment_work, build_fragment_from_indices, compute_mbe, serial_fragment_processor
serial_gmbe_pie_processor calls do_fragment_work, build_fragment_from_atom_list
compute_energy_and_forces calls run_calculation
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives
compute_mbe_gradient calls map_fragment_to_system_gradient
compute_mbe_hessian calls map_fragment_to_system_hessian
global_coordinator_impl calls compute_mbe
gmbe_run_distributed calls gmbe_pie_coordinator
gmbe_run_serial calls serial_gmbe_pie_processor
node_worker calls node_worker_impl, node_worker
run_unfragmented_calculation calls unfragmented_calculation
global_coordinator calls global_coordinator_impl
mbe_run_serial calls serial_fragment_processor