error_has_error – metalquicha
error_has_error Function
5 statements
Source File
private pure function error_has_error(this) result(has_err)
Check if an error is set
Type Bound
error_t
Arguments
Type Intent Optional Attributes Name
class(error_t), intent(in) :: this
Return Value logical
Called by
Source Code
   pure function error_has_error(this) result(has_err)
      !! Check if an error is set
      class(error_t), intent(in) :: this
      logical :: has_err
      has_err = (this%code /= SUCCESS)
   end function error_has_error
Call graph
build_fragment_from_atom_list calls error_has_error
build_fragment_from_indices calls error_has_error
build_mbe_lookup_table calls error_has_error
build_molecular_basis calls error_has_error, parse_element_basis
compute_gmbe calls error_has_error, build_fragment_from_indices, error_get_full_trace, process_intersection_derivatives
config_to_system_geometry calls error_has_error, geometry_to_system_fragmented, molecule_to_system_geometry
dfs_pie_accumulate calls error_has_error, dfs_pie_accumulate
error_get_full_trace calls error_has_error
error_print_trace calls error_has_error
gmbe_enumerate_pie_terms calls error_has_error, dfs_pie_accumulate
initialize_fragmented_system calls error_has_error
initialize_system_geometry calls error_has_error, read_xyz_file
map_fragment_to_system_gradient calls error_has_error, build_fragment_from_indices, error_get_full_trace
node_worker_impl calls error_has_error, build_fragment_from_atom_list, build_fragment_from_indices, error_get_full_trace
parse_element_basis calls error_has_error
parse_fragment calls error_has_error
parse_fragmentation_section calls error_has_error, parse_fragmentation_section
parse_fragments_generic calls error_has_error, parse_fragment, parse_fragments_generic
parse_molecules_section calls error_has_error, parse_single_molecule, parse_molecules_section
parse_single_molecule calls error_has_error, parse_molecule_fragments
process_intersection_derivatives calls error_has_error, build_fragment_from_atom_list, error_get_full_trace
read_mqc_file calls error_has_error, parse_fragmentation_section, parse_molecules_section, parse_fragments_section
read_xyz_file calls error_has_error
run_fragmented_calculation calls error_has_error, gmbe_enumerate_pie_terms
run_multi_molecule_calculations calls error_has_error, config_to_system_geometry, error_get_full_trace, run_calculation
serial_fragment_processor calls error_has_error, build_fragment_from_indices, error_get_full_trace, compute_mbe, serial_fragment_processor
serial_gmbe_pie_processor calls error_has_error, build_fragment_from_atom_list, error_get_full_trace
unfragmented_calculation calls error_has_error, error_get_full_trace, unfragmented_calculation
main calls error_has_error, config_to_system_geometry, read_mqc_file, run_multi_molecule_calculations, run_calculation
compute_mbe calls build_mbe_lookup_table, map_fragment_to_system_gradient, compute_mbe_gradient, map_fragment_to_system_dipole_derivatives, map_fragment_to_system_hessian, compute_mbe_dipole_derivatives, compute_mbe_hessian
compute_mbe_gradient calls map_fragment_to_system_gradient
geometry_to_system_fragmented calls initialize_fragmented_system
gmbe_pie_coordinator calls build_fragment_from_atom_list
gmbe_run_serial calls serial_gmbe_pie_processor
map_fragment_to_system_dipole_derivatives calls build_fragment_from_indices
map_fragment_to_system_hessian calls build_fragment_from_indices
molecule_to_system_geometry calls initialize_fragmented_system
node_worker calls node_worker_impl, node_worker
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation
compute_energy_and_forces calls run_calculation
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives
compute_mbe_hessian calls map_fragment_to_system_hessian
global_coordinator_impl calls compute_mbe
gmbe_run_distributed calls gmbe_pie_coordinator, node_worker
mbe_run_serial calls serial_fragment_processor
parse_fragments_section calls parse_fragments_generic, parse_fragments_section
parse_molecule_fragments calls parse_fragments_generic
run_unfragmented_calculation calls unfragmented_calculation
global_coordinator calls global_coordinator_impl, global_coordinator
mbe_run_distributed calls node_worker