error_add_context – metalquicha
error_add_context Subroutine
8 statements
Source File
private pure subroutine error_add_context(this, location)
Add a call location to the stack trace Typically called when propagating errors upward
Example: call some_routine(…, error) if (error%has_error()) then call error%add_context(“mqc_mbe:compute_energy”) return end if
Type Bound
error_t
Arguments
Type Intent Optional Attributes Name
class(error_t), intent(inout) :: this
character(len=*), intent(in) :: location
Called by
Source Code
   pure subroutine error_add_context(this, location)
      !! Add a call location to the stack trace
      !! Typically called when propagating errors upward
      !!
      !! Example:
      !!   call some_routine(..., error)
      !!   if (error%has_error()) then
      !!      call error%add_context("mqc_mbe:compute_energy")
      !!      return
      !!   end if
      class(error_t), intent(inout) :: this
      character(len=*), intent(in) :: location
      if (this%stack_depth < MAX_STACK_DEPTH) then
         this%stack_depth = this%stack_depth + 1
         this%call_stack(this%stack_depth) = location
      end if
      ! If stack is full, silently ignore (could print warning in non-pure version)
   end subroutine error_add_context
Call graph
build_fragment_from_atom_list calls error_add_context
build_fragment_from_indices calls error_add_context
build_mbe_lookup_table calls error_add_context
build_molecular_basis calls error_add_context, parse_element_basis
config_to_system_geometry calls error_add_context, geometry_to_system_fragmented, molecule_to_system_geometry
do_fragment_work calls error_add_context, do_fragment_work
initialize_fragmented_system calls error_add_context
initialize_system_geometry calls error_add_context, read_xyz_file
parse_element_basis calls error_add_context
parse_fragment calls error_add_context
parse_fragmentation_section calls error_add_context, parse_fragmentation_section
parse_fragments_generic calls error_add_context, parse_fragment, parse_fragments_generic
parse_molecules_section calls error_add_context, parse_single_molecule, parse_molecules_section
parse_single_molecule calls error_add_context, parse_molecule_fragments
read_mqc_file calls error_add_context, parse_fragmentation_section, parse_molecules_section, parse_fragments_section
read_xyz_file calls error_add_context
run_multi_molecule_calculations calls error_add_context, config_to_system_geometry
compute_gmbe calls build_fragment_from_indices, process_intersection_derivatives
compute_mbe calls build_mbe_lookup_table, map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian
geometry_to_system_fragmented calls initialize_fragmented_system
gmbe_pie_coordinator calls build_fragment_from_atom_list
map_fragment_to_system_dipole_derivatives calls build_fragment_from_indices
map_fragment_to_system_gradient calls build_fragment_from_indices
map_fragment_to_system_hessian calls build_fragment_from_indices
molecule_to_system_geometry calls initialize_fragmented_system
node_worker_impl calls build_fragment_from_atom_list, build_fragment_from_indices, do_fragment_work
process_intersection_derivatives calls build_fragment_from_atom_list
serial_fragment_processor calls build_fragment_from_indices, do_fragment_work, compute_mbe, serial_fragment_processor
serial_gmbe_pie_processor calls build_fragment_from_atom_list, do_fragment_work
main calls config_to_system_geometry, read_mqc_file, run_multi_molecule_calculations
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives
compute_mbe_gradient calls map_fragment_to_system_gradient
compute_mbe_hessian calls map_fragment_to_system_hessian
global_coordinator_impl calls compute_mbe
gmbe_run_distributed calls gmbe_pie_coordinator, node_worker
gmbe_run_serial calls serial_gmbe_pie_processor
node_worker calls node_worker_impl, node_worker
parse_fragments_section calls parse_fragments_generic, parse_fragments_section
parse_molecule_fragments calls parse_fragments_generic
unfragmented_calculation calls do_fragment_work, unfragmented_calculation
global_coordinator calls global_coordinator_impl, global_coordinator
mbe_run_serial calls serial_fragment_processor
mbe_run_distributed calls node_worker
run_unfragmented_calculation calls unfragmented_calculation