error_clear – metalquicha
error_clear Subroutine
6 statements
Source File
private pure subroutine error_clear(this)
Clear the error state and stack trace
Type Bound
error_t
Arguments
Type Intent Optional Attributes Name
class(error_t), intent(inout) :: this
Called by
Source Code
   pure subroutine error_clear(this)
      !! Clear the error state and stack trace
      class(error_t), intent(inout) :: this
      this%code = SUCCESS
      this%stack_depth = 0
      if (allocated(this%message)) deallocate (this%message)
   end subroutine error_clear
Call graph
result_reset calls error_clear
result_destroy calls result_reset
compute_energy_and_forces calls result_destroy
flush_group_results calls result_destroy
handle_local_worker_results_to_batch calls result_destroy, flush_group_results
handle_node_results_to_batch calls result_destroy, flush_group_results
hessian_coordinator calls result_destroy, hessian_coordinator
hessian_worker calls result_destroy, hessian_worker
unfragmented_calculation calls result_destroy, unfragmented_calculation
xtb_calc_hessian calls result_destroy
gmbe_group_global_coordinator calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
group_global_coordinator_impl calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
distributed_unfragmented_hessian calls hessian_coordinator, hessian_worker
gmbe_run_distributed calls gmbe_group_global_coordinator
node_coordinator_impl calls group_global_coordinator_impl
run_unfragmented_calculation calls unfragmented_calculation