flush_group_results – metalquicha
flush_group_results Subroutine
19 statements
Source File
public subroutine flush_group_results(world_comm, batch_count, batch_ids, batch_results)
Send all currently batched results to rank 0 and reset the batch.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: world_comm
integer(kind=int32), intent(inout) :: batch_count
integer(kind=int64), intent(inout) :: batch_ids(:)
type(calculation_result_t), intent(inout) :: batch_results(:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
type(request_t), private :: req
Source Code
   subroutine flush_group_results(world_comm, batch_count, batch_ids, batch_results)
      !! Send all currently batched results to rank 0 and reset the batch.
      type(comm_t), intent(in) :: world_comm
      integer(int32), intent(inout) :: batch_count
      integer(int64), intent(inout) :: batch_ids(:)
      type(calculation_result_t), intent(inout) :: batch_results(:)
      type(request_t) :: req
      integer :: i
      if (batch_count <= 0) return
      call isend(world_comm, batch_count, 0, TAG_GROUP_RESULT, req)
      call wait(req)
      call isend(world_comm, batch_ids(1:batch_count), 0, TAG_GROUP_RESULT, req)
      call wait(req)
      do i = 1, batch_count
         call result_isend(batch_results(i), world_comm, 0, TAG_GROUP_RESULT, req)
         call wait(req)
         call batch_results(i)%destroy()
      end do
      batch_count = 0
   end subroutine flush_group_results
Call graph
flush_group_results calls isend, result_destroy, result_isend
result_destroy calls result_reset
result_isend calls isend, send
result_reset calls energy_reset, error_clear
energy_reset calls mp2_reset
gmbe_group_global_coordinator calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
group_global_coordinator_impl calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
handle_local_worker_results_to_batch calls flush_group_results
handle_node_results_to_batch calls flush_group_results
gmbe_run_distributed calls gmbe_group_global_coordinator, node_coordinator
node_coordinator_impl calls group_global_coordinator_impl
node_coordinator calls node_coordinator_impl, node_coordinator
mbe_run_distributed calls node_coordinator