fragment_compute_nelec – metalquicha
fragment_compute_nelec Subroutine
6 statements
Source File
private subroutine fragment_compute_nelec(this)
Compute number of electrons from atomic numbers and charge
Type Bound
physical_fragment_t
Arguments
Type Intent Optional Attributes Name
class(physical_fragment_t), intent(inout) :: this
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: nuclear_charge
Source Code
   subroutine fragment_compute_nelec(this)
      !! Compute number of electrons from atomic numbers and charge
      class(physical_fragment_t), intent(inout) :: this
      integer :: nuclear_charge
      nuclear_charge = sum(this%element_numbers)
      this%nelec = nuclear_charge - this%charge
   end subroutine fragment_compute_nelec
Call graph
build_fragment_from_atom_list calls fragment_compute_nelec
build_fragment_from_indices calls fragment_compute_nelec
hessian_coordinator calls fragment_compute_nelec, hessian_coordinator
hessian_worker calls fragment_compute_nelec, hessian_worker
unfragmented_calculation calls fragment_compute_nelec, unfragmented_calculation
compute_gmbe calls build_fragment_from_indices, process_intersection_derivatives
gmbe_pie_coordinator calls build_fragment_from_atom_list
map_fragment_to_system_dipole_derivatives calls build_fragment_from_indices
map_fragment_to_system_gradient calls build_fragment_from_indices
map_fragment_to_system_hessian calls build_fragment_from_indices
node_worker_impl calls build_fragment_from_atom_list, build_fragment_from_indices
process_intersection_derivatives calls build_fragment_from_atom_list
serial_fragment_processor calls build_fragment_from_indices, compute_mbe, serial_fragment_processor
serial_gmbe_pie_processor calls build_fragment_from_atom_list
compute_mbe calls map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives
compute_mbe_gradient calls map_fragment_to_system_gradient
compute_mbe_hessian calls map_fragment_to_system_hessian
distributed_unfragmented_hessian calls hessian_coordinator, hessian_worker, distributed_unfragmented_hessian
gmbe_run_distributed calls gmbe_pie_coordinator, node_worker
gmbe_run_serial calls serial_gmbe_pie_processor
node_worker calls node_worker_impl, node_worker
run_unfragmented_calculation calls unfragmented_calculation, distributed_unfragmented_hessian
global_coordinator_impl calls compute_mbe
mbe_run_serial calls serial_fragment_processor
run_calculation calls run_unfragmented_calculation
compute_energy_and_forces calls run_calculation
global_coordinator calls global_coordinator_impl
mbe_run_distributed calls node_worker
run_multi_molecule_calculations calls run_calculation
main calls run_calculation