fragment_lookup_find – metalquicha
fragment_lookup_find Function
27 statements
Source File
private function fragment_lookup_find(this, monomers, n) result(idx)
Find fragment index for given monomer combination
Type Bound
fragment_lookup_t
Arguments
Type Intent Optional Attributes Name
class(fragment_lookup_t), intent(in) :: this
integer, intent(in) :: monomers(:)
integer, intent(in) :: n
Return Value integer(kind=int64)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: bucket
type(hash_entry_t), private, pointer :: entry
integer(kind=int32), private :: hash_val
integer, private :: sorted_key(n)
Source Code
   function fragment_lookup_find(this, monomers, n) result(idx)
      !! Find fragment index for given monomer combination
      class(fragment_lookup_t), intent(in) :: this
      integer, intent(in) :: monomers(:), n
      integer(int64) :: idx
      integer(int32) :: hash_val
      integer :: bucket, sorted_key(n)
      type(hash_entry_t), pointer :: entry
      ! Sort monomers for canonical key
      sorted_key = monomers(1:n)
      call sort(sorted_key)
      ! Compute hash
      hash_val = fnv_1a_hash(sorted_key)
      bucket = 1 + modulo(hash_val, int(this%table_size, int32))
      ! Search chain
      if (allocated(this%table(bucket)%key)) then
         if (arrays_equal_internal(this%table(bucket)%key, sorted_key, n)) then
            idx = this%table(bucket)%value
            return
         end if
         entry => this%table(bucket)%next
         do while (associated(entry))
            if (arrays_equal_internal(entry%key, sorted_key, n)) then
               idx = entry%value
               return
            end if
            entry => entry%next
         end do
      end if
      ! Not found
      idx = -1
   end function fragment_lookup_find
Call graph
fragment_lookup_find calls fnv_1a_hash, arrays_equal_internal, sort
compute_mbe_delta calls fragment_lookup_find
compute_mbe_dipole calls fragment_lookup_find
compute_mbe_dipole_derivatives calls fragment_lookup_find
compute_mbe_gradient calls fragment_lookup_find
compute_mbe_hessian calls fragment_lookup_find
compute_mbe calls compute_mbe_delta, compute_mbe_dipole, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian
global_coordinator_impl calls compute_mbe
serial_fragment_processor calls compute_mbe, serial_fragment_processor
global_coordinator calls global_coordinator_impl, global_coordinator
mbe_run_serial calls serial_fragment_processor