get_next_combination – metalquicha
get_next_combination Subroutine
20 statements
Source File
public pure subroutine get_next_combination(indices, k, n, has_next)
Generate next combination (updates indices in place) has_next = .true. if there’s a next combination
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: indices(:)
integer, intent(in) :: k
integer, intent(in) :: n
logical, intent(out) :: has_next
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
Source Code
   pure subroutine get_next_combination(indices, k, n, has_next)
      !! Generate next combination (updates indices in place)
      !! has_next = .true. if there's a next combination
      integer, intent(inout) :: indices(:)
      integer, intent(in)    :: k, n
      logical, intent(out)   :: has_next
      integer                :: i
      has_next = .true.
      i = k
      do while (i >= 1)
         if (indices(i) < n - k + i) then
            indices(i) = indices(i) + 1
            do while (i < k)
               i = i + 1
               indices(i) = indices(i - 1) + 1
            end do
            return
         end if
         i = i - 1
      end do
      has_next = .false.
   end subroutine get_next_combination
Call graph
compute_mbe_delta calls get_next_combination
compute_mbe_dipole calls get_next_combination
compute_mbe_dipole_derivatives calls get_next_combination
compute_mbe_gradient calls get_next_combination
compute_mbe_hessian calls get_next_combination
fragment_should_be_screened calls get_next_combination
apply_distance_screening calls fragment_should_be_screened
compute_mbe calls compute_mbe_delta, compute_mbe_dipole, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian
global_coordinator_impl calls compute_mbe
run_fragmented_calculation calls apply_distance_screening
serial_fragment_processor calls compute_mbe, serial_fragment_processor
global_coordinator calls global_coordinator_impl, global_coordinator
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
mbe_run_serial calls serial_fragment_processor
run_multi_molecule_calculations calls run_calculation
main calls run_calculation