gmbe_run_distributed – metalquicha
gmbe_run_distributed Subroutine
41 statements
Source File
private subroutine gmbe_run_distributed(this, json_data)
Uses
omp_lib
mqc_mbe_fragment_distribution_scheme
pic_logger
pic_io
mqc_gmbe_fragment_distribution_scheme
Run distributed GMBE calculation
Type Bound
gmbe_context_t
Arguments
Type Intent Optional Attributes Name
class(gmbe_context_t), intent(inout) :: this
type(json_output_data_t), intent(out), optional :: json_data
Calls
Source Code
   subroutine gmbe_run_distributed(this, json_data)
      !! Run distributed GMBE calculation
      use mqc_gmbe_fragment_distribution_scheme, only: gmbe_pie_coordinator, gmbe_group_global_coordinator
      use mqc_mbe_fragment_distribution_scheme, only: node_coordinator, node_worker
      use pic_logger, only: logger => global_logger
      use pic_io, only: to_char
      use omp_lib, only: omp_set_num_threads, omp_get_max_threads
      class(gmbe_context_t), intent(inout) :: this
      type(json_output_data_t), intent(out), optional :: json_data
      if (.not. this%has_mpi()) then
         call logger%error("gmbe_run_distributed: resources not set in context")
         return
      end if
      ! Determine role based on MPI rank
      if (this%resources%mpi_comms%world_comm%leader() .and. &
          this%resources%mpi_comms%node_comm%leader()) then
         ! Global coordinator (rank 0, node leader on node 0)
         call omp_set_num_threads(omp_get_max_threads())
         call logger%verbose("Rank 0: Acting as GMBE PIE coordinator")
         call gmbe_pie_coordinator(this%resources, this%pie_atom_sets, this%pie_coefficients, &
                                   this%n_pie_terms, this%node_leader_ranks, this%num_nodes, &
                                   this%group_leader_ranks, this%group_ids, this%global_groups, &
                                   this%sys_geom, this%method_config, this%calc_type, json_data)
      else if (this%resources%mpi_comms%node_comm%leader()) then
         ! Node coordinator (node leader on other nodes)
         call logger%verbose("Rank "//to_char(this%resources%mpi_comms%world_comm%rank())// &
                             ": Acting as node coordinator")
         block
            integer :: i, group_leader_rank
            group_leader_rank = 0
            if (allocated(this%node_leader_ranks) .and. allocated(this%group_leader_ranks)) then
               do i = 1, size(this%node_leader_ranks)
                  if (this%node_leader_ranks(i) == this%resources%mpi_comms%world_comm%rank()) then
                     group_leader_rank = this%group_leader_ranks(i)
                     exit
                  end if
               end do
            end if
            if (group_leader_rank == this%resources%mpi_comms%world_comm%rank()) then
               call gmbe_group_global_coordinator(this%resources, this%node_leader_ranks, this%group_ids)
            else
               ! Note: node_coordinator works for both MBE and GMBE
               call node_coordinator(this)
            end if
         end block
      else
         ! Worker
         call omp_set_num_threads(1)
         call logger%verbose("Rank "//to_char(this%resources%mpi_comms%world_comm%rank())// &
                             ": Acting as worker")
         ! Note: node_worker works for both MBE and GMBE (fragment_type distinguishes)
         call node_worker(this)
      end if
   end subroutine gmbe_run_distributed
Call graph
gmbe_run_distributed calls error, node_coordinator, node_worker, leader, omp_get_max_threads, omp_set_num_threads, gmbe_group_global_coordinator, gmbe_pie_coordinator, mbe_base_has_mpi, to_char, verbose
node_coordinator calls node_coordinator, error, abort_comm, comm_world, node_coordinator_impl
node_worker calls node_worker, error, abort_comm, comm_world, node_worker_impl
gmbe_group_global_coordinator calls isend, flush_group_results, handle_group_node_requests, handle_local_worker_requests_group, handle_local_worker_results_to_batch, handle_node_results_to_batch, queue_init_from_list, queue_is_empty, receive_group_assignment_matrix
gmbe_pie_coordinator calls error, to_char, verbose, abort_comm, cart_disp, configuration, fc_mdyne, force_constants, frequencies, get_elapsed_time, info, build_fragment_from_atom_list, compute_thermochemistry, compute_vibrational_analysis, energy_total, fragment_destroy, handle_group_node_requests, handle_group_results, handle_local_worker_requests_group, handle_local_worker_results, handle_node_results, print_vibrational_analysis, queue_init_from_list, queue_is_empty, redistribute_cap_dipole_derivatives, redistribute_cap_gradients, redistribute_cap_hessian, send_group_assignment_matrix, reduced_masses, start, temp_ids
build_fragment_from_atom_list calls add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, error_add_context, error_has_error, fragment_compute_nelec
compute_thermochemistry calls compute_electronic_entropy, compute_moments_of_inertia, compute_partition_functions, compute_rotational_constants, compute_rotational_thermo, compute_translational_thermo, compute_vibrational_thermo, compute_zpe
compute_vibrational_analysis calls compute_cartesian_displacements, compute_force_constants, compute_ir_intensities, compute_reduced_masses, compute_vibrational_frequencies
energy_total calls mp2_total
flush_group_results calls isend, result_destroy, result_isend
fragment_destroy calls basis_set_destroy
handle_group_node_requests calls isend, iprobe, irecv, queue_pop, send_pie_term_payload
handle_group_results calls error, to_char, abort_comm, get_elapsed_time, info, iprobe, irecv, error_get_message, result_irecv, recv
handle_local_worker_requests_group calls isend, iprobe, irecv, queue_pop, send_pie_term_payload
handle_local_worker_results_to_batch calls error, to_char, abort_comm, flush_group_results, iprobe, append_result_to_batch, error_get_message, result_destroy, result_irecv
handle_local_worker_results calls error, to_char, abort_comm, get_elapsed_time, info, iprobe, error_get_message, result_irecv
handle_node_results_to_batch calls error, to_char, abort_comm, flush_group_results, iprobe, irecv, append_result_to_batch, error_get_message, result_destroy, result_irecv
handle_node_results calls error, to_char, abort_comm, get_elapsed_time, info, iprobe, irecv, error_get_message, result_irecv
print_vibrational_analysis calls info, compute_thermochemistry, element_number_to_symbol, print_thermochemistry, warning
receive_group_assignment_matrix calls irecv, recv
send_group_assignment_matrix calls isend
basis_set_destroy calls atomic_basis_destroy
check_duplicate_atoms calls error, to_char, element_number_to_symbol, error_set
compute_cartesian_displacements calls element_mass
compute_ir_intensities calls element_mass
compute_moments_of_inertia calls to_char, warning, pic_syev, element_mass
compute_reduced_masses calls element_mass
compute_vibrational_frequencies calls error, warning, pic_syev, mass_weight_hessian, project_translation_rotation
compute_zpe calls to_char, warning
node_coordinator_impl calls error, to_char, abort_comm, isend, iprobe, irecv, error_get_message, result_irecv, result_isend, recv, get_group_leader_rank, group_global_coordinator_impl
node_worker_impl calls error, to_char, abort_comm, isend, build_fragment_from_atom_list, fragment_destroy, irecv, error_has_error, result_isend, recv, do_fragment_work, build_fragment_from_indices, error_get_full_trace, mbe_base_has_geometry
print_thermochemistry calls info
result_destroy calls result_reset
result_irecv calls irecv, recv
result_isend calls isend, send
send_pie_term_payload calls isend
do_fragment_work calls do_fragment_work
atomic_basis_destroy calls cgto_destroy
build_fragment_from_indices calls add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, error_add_context, error_has_error, fragment_compute_nelec, calculate_monomer_distance
error_get_full_trace calls error_has_error
group_global_coordinator_impl calls error, abort_comm, isend, flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch, queue_init_from_list, queue_is_empty, receive_group_assignment_matrix, get_group_leader_rank, handle_group_node_requests, handle_local_worker_requests_group, queue_destroy
mass_weight_hessian calls element_mass
project_translation_rotation calls element_mass, pic_gesvd
result_reset calls energy_reset, error_clear