gmbe_coordinator – metalquicha
gmbe_coordinator Subroutine
161 statements
Source File
public subroutine gmbe_coordinator(world_comm, node_comm, n_monomers, polymers, intersections, intersection_sets, intersection_levels, n_intersections, node_leader_ranks, num_nodes, sys_geom, method, calc_type, bonds)
Uses
mqc_mbe
MPI-enabled GMBE coordinator: distributes monomers and intersections across ranks Similar to global_coordinator but handles GMBE-specific fragment types
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: world_comm
type(comm_t), intent(in) :: node_comm
integer, intent(in) :: n_monomers
Number of monomers
integer, intent(in) :: polymers(:,:)
Monomer indices (n_monomers, 1)
integer, intent(in) :: intersections(:,:)
Intersection atom lists
integer, intent(in) :: intersection_sets(:,:)
k-tuples that created intersections
integer, intent(in) :: intersection_levels(:)
Level k of each intersection
integer, intent(in) :: n_intersections
Number of intersection fragments
integer, intent(in) :: node_leader_ranks(:)
integer, intent(in) :: num_nodes
type(system_geometry_t), intent(in) :: sys_geom
integer(kind=int32), intent(in) :: method
integer(kind=int32), intent(in) :: calc_type
type(bond_t), intent(in), optional :: bonds(:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(timer_type), private :: coord_timer
integer, private :: current_fragment_idx
integer, private :: dummy_msg
integer, private :: finished_nodes
integer, private :: fragment_idx
logical, private :: handling_local_workers
logical, private :: has_pending
type(calculation_result_t), private, allocatable :: intersection_results(:)
integer, private :: intersection_size
logical, private :: is_monomer
integer, private :: local_dummy
integer, private :: local_finished_workers
type(MPI_Status), private :: local_status
integer, private, allocatable :: monomer_indices(:)
type(calculation_result_t), private, allocatable :: monomer_results(:)
type(request_t), private :: req
integer, private :: request_source
integer, private :: results_received
type(MPI_Status), private :: status
real(kind=dp), private :: total_energy
integer, private :: total_fragments
integer, private :: worker_fragment_map(node_comm%size())
integer, private :: worker_source
Source Code
   subroutine gmbe_coordinator(world_comm, node_comm, n_monomers, polymers, intersections, intersection_sets, &
                   intersection_levels, n_intersections, node_leader_ranks, num_nodes, sys_geom, method, calc_type, bonds)
      !! MPI-enabled GMBE coordinator: distributes monomers and intersections across ranks
      !! Similar to global_coordinator but handles GMBE-specific fragment types
      use mqc_mbe, only: compute_gmbe_energy
      type(comm_t), intent(in) :: world_comm, node_comm
      integer, intent(in) :: n_monomers  !! Number of monomers
      integer, intent(in) :: polymers(:, :)  !! Monomer indices (n_monomers, 1)
      integer, intent(in) :: intersections(:, :)  !! Intersection atom lists
      integer, intent(in) :: intersection_sets(:, :)  !! k-tuples that created intersections
      integer, intent(in) :: intersection_levels(:)  !! Level k of each intersection
      integer, intent(in) :: n_intersections  !! Number of intersection fragments
      integer, intent(in) :: node_leader_ranks(:), num_nodes
      type(system_geometry_t), intent(in) :: sys_geom
      integer(int32), intent(in) :: method, calc_type
      type(bond_t), intent(in), optional :: bonds(:)
      type(timer_type) :: coord_timer
      integer :: current_fragment_idx, total_fragments, results_received
      integer :: finished_nodes
      integer :: request_source, dummy_msg, fragment_idx
      type(MPI_Status) :: status, local_status
      logical :: handling_local_workers
      logical :: has_pending
      logical :: is_monomer
      integer :: intersection_size
      ! For local workers
      integer :: local_finished_workers, local_dummy
      ! Storage for results
      type(calculation_result_t), allocatable :: monomer_results(:), intersection_results(:)
      integer :: worker_fragment_map(node_comm%size())
      integer :: worker_source
      integer, allocatable :: monomer_indices(:)
      real(dp) :: total_energy
      ! MPI request handles for non-blocking operations
      type(request_t) :: req
      ! Total fragments = monomers + intersections
      total_fragments = n_monomers + n_intersections
      current_fragment_idx = total_fragments
      finished_nodes = 0
      local_finished_workers = 0
      handling_local_workers = (node_comm%size() > 1)
      results_received = 0
      worker_fragment_map = 0
      ! Allocate storage for results
      allocate (monomer_results(n_monomers))
      if (n_intersections > 0) then
         allocate (intersection_results(n_intersections))
      end if
      call logger%verbose("GMBE coordinator starting with "//to_char(n_monomers)// &
                          " monomers and "//to_char(n_intersections)//" intersections for "// &
                          to_char(num_nodes)//" nodes")
      call coord_timer%start()
      do while (finished_nodes < num_nodes)
         ! PRIORITY 1: Check for incoming results from local workers
         if (handling_local_workers) then
            do
               call iprobe(node_comm, MPI_ANY_SOURCE, TAG_WORKER_SCALAR_RESULT, has_pending, local_status)
               if (.not. has_pending) exit
               worker_source = local_status%MPI_SOURCE
               if (worker_fragment_map(worker_source) == 0) then
                  call logger%error("Received result from worker "//to_char(worker_source)// &
                                    " but no fragment was assigned!")
                  error stop "Invalid worker_fragment_map state"
               end if
               ! Determine if this was a monomer or intersection
               fragment_idx = worker_fragment_map(worker_source)
               is_monomer = (fragment_idx <= n_monomers)
               ! Receive result and store it
               if (is_monomer) then
                  call result_irecv(monomer_results(fragment_idx), node_comm, worker_source, &
                                    TAG_WORKER_SCALAR_RESULT, req)
               else
                  call result_irecv(intersection_results(fragment_idx - n_monomers), node_comm, worker_source, &
                                    TAG_WORKER_SCALAR_RESULT, req)
               end if
               call wait(req)
               worker_fragment_map(worker_source) = 0
               results_received = results_received + 1
               if (mod(results_received, max(1, total_fragments/10)) == 0 .or. &
                   results_received == total_fragments) then
                  call logger%info("  Processed "//to_char(results_received)//"/"// &
                                   to_char(total_fragments)//" fragments ["// &
                                   to_char(coord_timer%get_elapsed_time())//" s]")
               end if
            end do
         end if
         ! PRIORITY 1b: Check for incoming results from remote node coordinators
         do
            call iprobe(world_comm, MPI_ANY_SOURCE, TAG_NODE_SCALAR_RESULT, has_pending, status)
            if (.not. has_pending) exit
            ! Receive fragment index
            call irecv(world_comm, fragment_idx, status%MPI_SOURCE, TAG_NODE_SCALAR_RESULT, req)
            call wait(req)
            ! Determine if this was a monomer or intersection
            is_monomer = (fragment_idx <= n_monomers)
            ! Receive result
            if (is_monomer) then
               call result_irecv(monomer_results(fragment_idx), world_comm, status%MPI_SOURCE, &
                                 TAG_NODE_SCALAR_RESULT, req)
            else
               call result_irecv(intersection_results(fragment_idx - n_monomers), world_comm, status%MPI_SOURCE, &
                                 TAG_NODE_SCALAR_RESULT, req)
            end if
            call wait(req)
            results_received = results_received + 1
            if (mod(results_received, max(1, total_fragments/10)) == 0 .or. &
                results_received == total_fragments) then
               call logger%info("  Processed "//to_char(results_received)//"/"// &
                                to_char(total_fragments)//" fragments ["// &
                                to_char(coord_timer%get_elapsed_time())//" s]")
            end if
         end do
         ! PRIORITY 2: Remote node coordinator requests
         call iprobe(world_comm, MPI_ANY_SOURCE, TAG_NODE_REQUEST, has_pending, status)
         if (has_pending) then
            call irecv(world_comm, dummy_msg, status%MPI_SOURCE, TAG_NODE_REQUEST, req)
            call wait(req)
            request_source = status%MPI_SOURCE
            if (current_fragment_idx >= 1) then
               call send_gmbe_fragment_to_node(world_comm, current_fragment_idx, n_monomers, polymers, &
                                               intersections, request_source)
               current_fragment_idx = current_fragment_idx - 1
            else
               call isend(world_comm, -1, request_source, TAG_NODE_FINISH, req)
               call wait(req)
               finished_nodes = finished_nodes + 1
            end if
         end if
         ! PRIORITY 3: Local workers (shared memory) - send new work
         if (handling_local_workers .and. local_finished_workers < node_comm%size() - 1) then
            call iprobe(node_comm, MPI_ANY_SOURCE, TAG_WORKER_REQUEST, has_pending, local_status)
            if (has_pending) then
               if (worker_fragment_map(local_status%MPI_SOURCE) == 0) then
                  call irecv(node_comm, local_dummy, local_status%MPI_SOURCE, TAG_WORKER_REQUEST, req)
                  call wait(req)
                  if (current_fragment_idx >= 1) then
                     call send_gmbe_fragment_to_worker(node_comm, current_fragment_idx, n_monomers, polymers, &
                                                       intersections, local_status%MPI_SOURCE)
                     worker_fragment_map(local_status%MPI_SOURCE) = current_fragment_idx
                     current_fragment_idx = current_fragment_idx - 1
                  else
                     call isend(node_comm, -1, local_status%MPI_SOURCE, TAG_WORKER_FINISH, req)
                     call wait(req)
                     local_finished_workers = local_finished_workers + 1
                  end if
               end if
            end if
         end if
         ! Finalize local worker completion
         if (handling_local_workers .and. local_finished_workers >= node_comm%size() - 1 &
             .and. results_received >= total_fragments) then
            handling_local_workers = .false.
            finished_nodes = finished_nodes + 1
         end if
      end do
      call logger%verbose("GMBE coordinator finished all fragments")
      call coord_timer%stop()
      call logger%info("Time to evaluate all fragments "//to_char(coord_timer%get_elapsed_time())//" s")
      ! Compute GMBE energy
      call logger%info(" ")
      call logger%info("Computing Generalized Many-Body Expansion (GMBE)...")
      call coord_timer%start()
      allocate (monomer_indices(n_monomers))
      do fragment_idx = 1, n_monomers
         monomer_indices(fragment_idx) = polymers(fragment_idx, 1)
      end do
      if (n_intersections > 0) then
         call compute_gmbe_energy(monomer_indices, n_monomers, monomer_results, &
                                  n_intersections, intersection_results, &
                                  intersection_sets, intersection_levels, total_energy)
      else
         ! No intersections case - need dummy arrays
         block
            integer, allocatable :: dummy_sets(:, :), dummy_levels(:)
            allocate (dummy_sets(1, 0), dummy_levels(0))
            call compute_gmbe_energy(monomer_indices, n_monomers, monomer_results, &
                                     0, monomer_results(1:0), &
                                     dummy_sets, dummy_levels, total_energy)
            deallocate (dummy_sets, dummy_levels)
         end block
      end if
      call coord_timer%stop()
      call logger%info("Time to compute GMBE "//to_char(coord_timer%get_elapsed_time())//" s")
      call logger%info(" ")
      call logger%info("GMBE calculation completed successfully")
      call logger%info("Final GMBE energy: "//to_char(total_energy)//" Hartree")
      call logger%info(" ")
      ! Write JSON output
      if (n_intersections > 0) then
         call print_gmbe_json(n_monomers, monomer_indices, monomer_results, &
                              n_intersections, intersection_results, &
                              intersection_sets, intersection_levels, total_energy)
      else
         ! No intersections - need dummy arrays
         block
            integer, allocatable :: dummy_sets(:, :), dummy_levels(:)
            type(calculation_result_t), allocatable :: dummy_results(:)
            allocate (dummy_sets(1, 0), dummy_levels(0), dummy_results(0))
            call print_gmbe_json(n_monomers, monomer_indices, monomer_results, &
                                 0, dummy_results, &
                                 dummy_sets, dummy_levels, total_energy)
            deallocate (dummy_sets, dummy_levels, dummy_results)
         end block
      end if
      ! Cleanup
      deallocate (monomer_results, monomer_indices)
      if (allocated(intersection_results)) deallocate (intersection_results)
   end subroutine gmbe_coordinator
Call graph
gmbe_coordinator calls dummy_levels, dummy_results, dummy_sets, error, get_elapsed_time, info, iprobe, irecv, isend, compute_gmbe_energy, print_gmbe_json, result_irecv, send_gmbe_fragment_to_node, send_gmbe_fragment_to_worker, start, to_char, verbose
compute_gmbe_energy calls info, debug, energy_total
print_gmbe_json calls error, info, energy_total, get_basename, get_output_json_filename
result_irecv calls irecv, recv
send_gmbe_fragment_to_node calls isend
send_gmbe_fragment_to_worker calls isend
energy_total calls mp2_total
run_fragmented_calculation calls gmbe_coordinator
run_calculation calls run_fragmented_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations