handle_local_worker_results_to_batch – metalquicha
handle_local_worker_results_to_batch Subroutine
42 statements
Source File
public subroutine handle_local_worker_results_to_batch(node_comm, world_comm, worker_map, batch_count, batch_ids, batch_results, results_received)
Drain pending local worker results and append them to the outbound batch.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: node_comm
type(comm_t), intent(in) :: world_comm
integer(kind=int64), intent(inout) :: worker_map(:)
integer(kind=int32), intent(inout) :: batch_count
integer(kind=int64), intent(inout) :: batch_ids(:)
type(calculation_result_t), intent(inout) :: batch_results(:)
integer(kind=int64), intent(inout), optional :: results_received
Calls
Called by
Variables
Type Visibility Attributes Name Initial
logical, private :: has_pending
integer(kind=int64), private :: item_idx
type(MPI_Status), private :: local_status
type(request_t), private :: req
type(calculation_result_t), private :: worker_result
integer, private :: worker_source
Source Code
   subroutine handle_local_worker_results_to_batch(node_comm, world_comm, worker_map, batch_count, batch_ids, batch_results, &
                                                   results_received)
      !! Drain pending local worker results and append them to the outbound batch.
      type(comm_t), intent(in) :: node_comm
      type(comm_t), intent(in) :: world_comm
      integer(int64), intent(inout) :: worker_map(:)
      integer(int32), intent(inout) :: batch_count
      integer(int64), intent(inout) :: batch_ids(:)
      type(calculation_result_t), intent(inout) :: batch_results(:)
      integer(int64), intent(inout), optional :: results_received
      type(MPI_Status) :: local_status
      logical :: has_pending
      integer :: worker_source
      type(request_t) :: req
      type(calculation_result_t) :: worker_result
      integer(int64) :: item_idx
      if (node_comm%size() <= 1) return
      do
         call iprobe(node_comm, MPI_ANY_SOURCE, TAG_WORKER_SCALAR_RESULT, has_pending, local_status)
         if (.not. has_pending) exit
         worker_source = local_status%MPI_SOURCE
         if (worker_map(worker_source) == 0) then
            call logger%error("Received result from worker "//to_char(worker_source)// &
                              " but no item was assigned!")
            call abort_comm(world_comm, 1)
         end if
         call result_irecv(worker_result, node_comm, worker_source, TAG_WORKER_SCALAR_RESULT, req)
         call wait(req)
         if (worker_result%has_error) then
            call logger%error("Item "//to_char(worker_map(worker_source))// &
                              " calculation failed: "// &
                              worker_result%error%get_message())
            call abort_comm(world_comm, 1)
         end if
         item_idx = worker_map(worker_source)
         worker_map(worker_source) = 0
         if (batch_count >= size(batch_ids)) then
            call flush_group_results(world_comm, batch_count, batch_ids, batch_results)
         end if
         call append_result_to_batch(item_idx, worker_result, batch_count, batch_ids, batch_results)
         if (present(results_received)) results_received = results_received + 1_int64
         if (batch_count >= size(batch_ids)) then
            call flush_group_results(world_comm, batch_count, batch_ids, batch_results)
         end if
         call worker_result%destroy()
      end do
   end subroutine handle_local_worker_results_to_batch
Call graph
handle_local_worker_results_to_batch calls abort_comm, error, iprobe, append_result_to_batch, error_get_message, flush_group_results, result_destroy, result_irecv, to_char
flush_group_results calls result_destroy, isend, result_isend
result_destroy calls result_reset
result_irecv calls irecv, recv
result_isend calls isend, send
result_reset calls energy_reset, error_clear
energy_reset calls mp2_reset
gmbe_group_global_coordinator calls handle_local_worker_results_to_batch
group_global_coordinator_impl calls handle_local_worker_results_to_batch
gmbe_run_distributed calls gmbe_group_global_coordinator, node_coordinator
node_coordinator_impl calls group_global_coordinator_impl
node_coordinator calls node_coordinator_impl, node_coordinator
mbe_run_distributed calls node_coordinator