handle_node_results_to_batch – metalquicha
handle_node_results_to_batch Subroutine
33 statements
Source File
public subroutine handle_node_results_to_batch(world_comm, batch_count, batch_ids, batch_results, results_received)
Drain pending node-level results and append them to the outbound batch.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: world_comm
integer(kind=int32), intent(inout) :: batch_count
integer(kind=int64), intent(inout) :: batch_ids(:)
type(calculation_result_t), intent(inout) :: batch_results(:)
integer(kind=int64), intent(inout), optional :: results_received
Calls
Called by
Variables
Type Visibility Attributes Name Initial
logical, private :: has_pending
integer(kind=int64), private :: item_idx
type(calculation_result_t), private :: node_result
type(request_t), private :: req
type(MPI_Status), private :: status
Source Code
   subroutine handle_node_results_to_batch(world_comm, batch_count, batch_ids, batch_results, results_received)
      !! Drain pending node-level results and append them to the outbound batch.
      type(comm_t), intent(in) :: world_comm
      integer(int32), intent(inout) :: batch_count
      integer(int64), intent(inout) :: batch_ids(:)
      type(calculation_result_t), intent(inout) :: batch_results(:)
      integer(int64), intent(inout), optional :: results_received
      integer(int64) :: item_idx
      type(MPI_Status) :: status
      logical :: has_pending
      type(request_t) :: req
      type(calculation_result_t) :: node_result
      do
         call iprobe(world_comm, MPI_ANY_SOURCE, TAG_NODE_SCALAR_RESULT, has_pending, status)
         if (.not. has_pending) exit
         call irecv(world_comm, item_idx, status%MPI_SOURCE, TAG_NODE_SCALAR_RESULT, req)
         call wait(req)
         call result_irecv(node_result, world_comm, status%MPI_SOURCE, TAG_NODE_SCALAR_RESULT, req)
         call wait(req)
         if (node_result%has_error) then
            call logger%error("Item "//to_char(item_idx)//" calculation failed: "// &
                              node_result%error%get_message())
            call abort_comm(world_comm, 1)
         end if
         if (batch_count >= size(batch_ids)) then
            call flush_group_results(world_comm, batch_count, batch_ids, batch_results)
         end if
         call append_result_to_batch(item_idx, node_result, batch_count, batch_ids, batch_results)
         if (present(results_received)) results_received = results_received + 1_int64
         if (batch_count >= size(batch_ids)) then
            call flush_group_results(world_comm, batch_count, batch_ids, batch_results)
         end if
         call node_result%destroy()
      end do
   end subroutine handle_node_results_to_batch
Call graph
handle_node_results_to_batch calls abort_comm, error, iprobe, irecv, append_result_to_batch, error_get_message, flush_group_results, result_destroy, result_irecv, to_char
flush_group_results calls result_destroy, isend, result_isend
result_destroy calls result_reset
result_irecv calls irecv, recv
result_isend calls isend, send
result_reset calls energy_reset, error_clear
energy_reset calls mp2_reset
gmbe_group_global_coordinator calls handle_node_results_to_batch
group_global_coordinator_impl calls handle_node_results_to_batch
gmbe_run_distributed calls gmbe_group_global_coordinator, node_coordinator
node_coordinator_impl calls group_global_coordinator_impl
node_coordinator calls node_coordinator_impl, node_coordinator
mbe_run_distributed calls node_coordinator