handle_local_worker_requests_group – metalquicha
handle_local_worker_requests_group Subroutine
29 statements
Source File
subroutine handle_local_worker_requests_group(ctx, fragment_queue, group_fragment_ids, group_polymers, worker_fragment_map, local_finished_workers)
Uses
mqc_many_body_expansion
Handle a single pending local worker request for a group shard, if any.
Arguments
Type Intent Optional Attributes Name
class(many_body_expansion_t), intent(in) :: ctx
type(queue_t), intent(inout) :: fragment_queue
integer(kind=int64), intent(in) :: group_fragment_ids(:)
integer, intent(in) :: group_polymers(:,:)
integer(kind=int64), intent(inout) :: worker_fragment_map(:)
integer, intent(inout) :: local_finished_workers
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int64), private :: fragment_idx
logical, private :: has_fragment
logical, private :: has_pending
integer(kind=int32), private :: local_dummy
integer(kind=int64), private :: local_idx
type(MPI_Status), private :: local_status
type(request_t), private :: req
Source Code
   subroutine handle_local_worker_requests_group(ctx, fragment_queue, group_fragment_ids, group_polymers, &
                                                 worker_fragment_map, local_finished_workers)
      !! Handle a single pending local worker request for a group shard, if any.
      use mqc_many_body_expansion, only: many_body_expansion_t
      class(many_body_expansion_t), intent(in) :: ctx
      type(queue_t), intent(inout) :: fragment_queue
      integer(int64), intent(in) :: group_fragment_ids(:)
      integer, intent(in) :: group_polymers(:, :)
      integer(int64), intent(inout) :: worker_fragment_map(:)
      integer, intent(inout) :: local_finished_workers
      integer(int64) :: local_idx, fragment_idx
      integer(int32) :: local_dummy
      type(MPI_Status) :: local_status
      logical :: has_pending, has_fragment
      type(request_t) :: req
      call iprobe(ctx%resources%mpi_comms%node_comm, MPI_ANY_SOURCE, TAG_WORKER_REQUEST, has_pending, local_status)
      if (.not. has_pending) return
      if (worker_fragment_map(local_status%MPI_SOURCE) /= 0) return
      call irecv(ctx%resources%mpi_comms%node_comm, local_dummy, local_status%MPI_SOURCE, TAG_WORKER_REQUEST, req)
      call wait(req)
      call queue_pop(fragment_queue, local_idx, has_fragment)
      if (has_fragment) then
         fragment_idx = group_fragment_ids(local_idx)
         call send_fragment_payload_from_row(ctx%resources%mpi_comms%node_comm, TAG_WORKER_FRAGMENT, fragment_idx, &
                                             group_polymers(local_idx, :), local_status%MPI_SOURCE)
         worker_fragment_map(local_status%MPI_SOURCE) = fragment_idx
      else
         call isend(ctx%resources%mpi_comms%node_comm, -1, local_status%MPI_SOURCE, TAG_WORKER_FINISH, req)
         call wait(req)
         local_finished_workers = local_finished_workers + 1
      end if
   end subroutine handle_local_worker_requests_group
Call graph
handle_local_worker_requests_group calls iprobe, irecv, isend, queue_pop, send_fragment_payload_from_row
send_fragment_payload_from_row calls isend, build_fragment_payload_from_row
global_coordinator_impl calls handle_local_worker_requests_group
group_global_coordinator_impl calls handle_local_worker_requests_group
global_coordinator calls global_coordinator_impl, global_coordinator
node_coordinator_impl calls group_global_coordinator_impl
node_coordinator calls node_coordinator_impl, node_coordinator
mbe_run_distributed calls global_coordinator, node_coordinator
gmbe_run_distributed calls node_coordinator