mbe_run_distributed – metalquicha
mbe_run_distributed Subroutine
32 statements
Source File
private subroutine mbe_run_distributed(this, json_data)
Uses
omp_lib
mqc_mbe_fragment_distribution_scheme
pic_io
pic_logger
Run distributed MBE calculation
Type Bound
mbe_context_t
Arguments
Type Intent Optional Attributes Name
class(mbe_context_t), intent(inout) :: this
type(json_output_data_t), intent(out), optional :: json_data
Calls
Source Code
   subroutine mbe_run_distributed(this, json_data)
      !! Run distributed MBE calculation
      use mqc_mbe_fragment_distribution_scheme, only: global_coordinator, node_coordinator, node_worker
      use pic_logger, only: logger => global_logger
      use pic_io, only: to_char
      use omp_lib, only: omp_set_num_threads, omp_get_max_threads
      class(mbe_context_t), intent(inout) :: this
      type(json_output_data_t), intent(out), optional :: json_data
      if (.not. this%has_mpi()) then
         call logger%error("mbe_run_distributed: resources not set in context")
         return
      end if
      ! Determine role based on MPI rank
      if (this%resources%mpi_comms%world_comm%leader() .and. &
          this%resources%mpi_comms%node_comm%leader()) then
         ! Global coordinator (rank 0, node leader on node 0)
         call omp_set_num_threads(omp_get_max_threads())
         call logger%verbose("Rank 0: Acting as global coordinator")
         if (this%has_geometry()) then
            call global_coordinator(this%resources, this%total_fragments, this%polymers, &
                                    this%max_level, this%node_leader_ranks, this%num_nodes, &
                                    this%sys_geom, this%method_config, this%calc_type, json_data)
         else
            call global_coordinator(this%resources, this%total_fragments, this%polymers, &
                                    this%max_level, this%node_leader_ranks, this%num_nodes, &
                                    method_config=this%method_config, calc_type=this%calc_type, &
                                    json_data=json_data)
         end if
      else if (this%resources%mpi_comms%node_comm%leader()) then
         ! Node coordinator (node leader on other nodes)
         call logger%verbose("Rank "//to_char(this%resources%mpi_comms%world_comm%rank())// &
                             ": Acting as node coordinator")
         call node_coordinator(this%resources, this%method_config, this%calc_type)
      else
         ! Worker
         call omp_set_num_threads(1)
         call logger%verbose("Rank "//to_char(this%resources%mpi_comms%world_comm%rank())// &
                             ": Acting as worker")
         if (this%has_geometry()) then
            call node_worker(this%resources, this%sys_geom, this%method_config, this%calc_type)
         else
            call node_worker(this%resources, method_config=this%method_config, &
                             calc_type=this%calc_type)
         end if
      end if
   end subroutine mbe_run_distributed
Call graph
mbe_run_distributed calls error, global_coordinator, node_coordinator, node_worker, leader, omp_get_max_threads, omp_set_num_threads, mbe_base_has_geometry, mbe_base_has_mpi, to_char, verbose
global_coordinator calls global_coordinator, error, to_char, verbose, abort_comm, allocate_dipole, allocate_gradient, allocate_hessian, debug, destroy, get_elapsed_time, info, iprobe, irecv, isend, compute_mbe, error_get_message, result_irecv, send_fragment_to_node, send_fragment_to_worker, start
node_coordinator calls node_coordinator, error, to_char, abort_comm, iprobe, irecv, isend, error_get_message, result_irecv, result_isend, recv
node_worker calls node_worker, error, to_char, abort_comm, do_fragment_work, irecv, isend, build_fragment_from_atom_list, build_fragment_from_indices, error_get_full_trace, error_has_error, fragment_destroy, result_isend, recv
do_fragment_work calls do_fragment_work, to_char, configuration, error_add_context, calc_energy, calc_gradient, calc_hessian, calc_type_to_string, create_method, energy_reset, error_set, print_fragment_xyz
build_fragment_from_atom_list calls error_has_error, add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
build_fragment_from_indices calls error_has_error, add_hydrogen_caps, calculate_monomer_distance, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
compute_mbe calls error, to_char, abort_comm, info, cart_disp, configuration, fc_mdyne, force_constants, frequencies, get_message, has_error, build_mbe_lookup_table, compute_mbe_delta, compute_mbe_dipole, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian, compute_thermochemistry, compute_vibrational_analysis, energy_total, fragment_lookup_destroy, map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, print_detailed_breakdown, print_mbe_energy_breakdown, print_mbe_gradient_info, print_vibrational_analysis, reduced_masses, warning
error_get_full_trace calls error_has_error
fragment_destroy calls basis_set_destroy
result_irecv calls irecv, recv
result_isend calls isend, send
send_fragment_to_node calls isend
send_fragment_to_worker calls isend
basis_set_destroy calls atomic_basis_destroy
build_mbe_lookup_table calls to_char, debug, get_elapsed_time, error_has_error, start, error_add_context, fragment_lookup_init, fragment_lookup_insert
calculate_monomer_distance calls to_angstrom
check_duplicate_atoms calls error, to_char, element_number_to_symbol, error_set
compute_mbe_delta calls error, abort_comm, fragment_lookup_find, get_next_combination
compute_mbe_dipole calls error, abort_comm, fragment_lookup_find, get_next_combination
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives, fragment_lookup_find, get_next_combination
compute_mbe_gradient calls error, abort_comm, map_fragment_to_system_gradient, fragment_lookup_find, get_next_combination
compute_mbe_hessian calls map_fragment_to_system_hessian, fragment_lookup_find, get_next_combination
compute_thermochemistry calls compute_electronic_entropy, compute_moments_of_inertia, compute_partition_functions, compute_rotational_constants, compute_rotational_thermo, compute_translational_thermo, compute_vibrational_thermo, compute_zpe
compute_vibrational_analysis calls compute_cartesian_displacements, compute_force_constants, compute_ir_intensities, compute_reduced_masses, compute_vibrational_frequencies
energy_total calls mp2_total
map_fragment_to_system_dipole_derivatives calls build_fragment_from_indices, fragment_destroy, redistribute_cap_dipole_derivatives
map_fragment_to_system_gradient calls error, abort_comm, debug, build_fragment_from_indices, error_get_full_trace, error_has_error, fragment_destroy, configuration, redistribute_cap_gradients
map_fragment_to_system_hessian calls build_fragment_from_indices, fragment_destroy, redistribute_cap_hessian
print_detailed_breakdown calls verbose, warning, header, level_name, get_frag_level_name
print_mbe_energy_breakdown calls info
print_mbe_gradient_info calls to_char, info
print_vibrational_analysis calls info, compute_thermochemistry, warning, element_number_to_symbol, print_thermochemistry