mp2_total – metalquicha
mp2_total Function
5 statements
Source File
private pure function mp2_total(this) result(total)
Compute total MP2 correlation energy
Type Bound
mp2_energy_t
Arguments
Type Intent Optional Attributes Name
class(mp2_energy_t), intent(in) :: this
Return Value real(kind=dp)
Called by
Source Code
   pure function mp2_total(this) result(total)
      !! Compute total MP2 correlation energy
      class(mp2_energy_t), intent(in) :: this
      real(dp) :: total
      total = this%ss + this%os
   end function mp2_total
Call graph
energy_total calls mp2_total
compute_energy_and_forces calls energy_total
compute_gmbe calls energy_total, print_gmbe_intersection_debug
compute_mbe calls energy_total
dft_calc_energy calls energy_total
gmbe_pie_coordinator calls energy_total
hessian_coordinator calls energy_total, populate_unfragmented_json_data, populate_vibrational_json_data, hessian_coordinator
hf_calc_energy calls energy_total
mcscf_calc_energy calls energy_total
populate_unfragmented_json_data calls energy_total
populate_vibrational_json_data calls energy_total
print_gmbe_intersection_debug calls energy_total
serial_fragment_processor calls energy_total, compute_mbe, serial_fragment_processor
serial_gmbe_pie_processor calls energy_total
unfragmented_calculation calls energy_total, unfragmented_calculation
xtb_calc_energy calls energy_total
xtb_calc_gradient calls energy_total
dft_calc_gradient calls dft_calc_energy
dft_calc_hessian calls dft_calc_energy
global_coordinator_impl calls compute_mbe
gmbe_run_distributed calls gmbe_pie_coordinator
gmbe_run_serial calls serial_gmbe_pie_processor
hf_calc_gradient calls hf_calc_energy
mcscf_calc_gradient calls mcscf_calc_energy
mcscf_calc_hessian calls mcscf_calc_energy
xtb_calc_hessian calls xtb_calc_gradient
distributed_unfragmented_hessian calls hessian_coordinator, distributed_unfragmented_hessian
global_coordinator calls global_coordinator_impl, global_coordinator
mbe_run_serial calls serial_fragment_processor
run_unfragmented_calculation calls unfragmented_calculation
run_calculation calls run_unfragmented_calculation