mp2_reset – metalquicha
mp2_reset Subroutine
5 statements
Source File
private subroutine mp2_reset(this)
Reset both MP2 components to zero
Type Bound
mp2_energy_t
Arguments
Type Intent Optional Attributes Name
class(mp2_energy_t), intent(inout) :: this
Called by
Source Code
   subroutine mp2_reset(this)
      !! Reset both MP2 components to zero
      class(mp2_energy_t), intent(inout) :: this
      this%ss = 0.0_dp
      this%os = 0.0_dp
   end subroutine mp2_reset
Call graph
energy_reset calls mp2_reset
do_fragment_work calls energy_reset, do_fragment_work
result_reset calls energy_reset
result_destroy calls result_reset
compute_energy_and_forces calls result_destroy
flush_group_results calls result_destroy
handle_local_worker_results_to_batch calls result_destroy, flush_group_results
handle_node_results_to_batch calls result_destroy, flush_group_results
hessian_coordinator calls result_destroy, hessian_coordinator
hessian_worker calls result_destroy, hessian_worker
node_worker_impl calls do_fragment_work
serial_fragment_processor calls do_fragment_work, serial_fragment_processor
serial_gmbe_pie_processor calls do_fragment_work
unfragmented_calculation calls do_fragment_work, result_destroy, unfragmented_calculation
xtb_calc_hessian calls result_destroy
gmbe_group_global_coordinator calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
gmbe_run_serial calls serial_gmbe_pie_processor
group_global_coordinator_impl calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
node_worker calls node_worker_impl