node_coordinator_impl – metalquicha
node_coordinator_impl Subroutine
86 statements
Source File
subroutine node_coordinator_impl(ctx)
Uses
mqc_many_body_expansion
Internal implementation of node_coordinator with typed context
Arguments
Type Intent Optional Attributes Name
class(many_body_expansion_t), intent(in) :: ctx
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: dummy_msg
integer(kind=int32), private :: finished_workers
integer(kind=int64), private :: fragment_idx
integer(kind=int32), private, allocatable :: fragment_indices(:)
integer(kind=int32), private :: fragment_size
integer(kind=int32), private :: fragment_type
type(MPI_Status), private :: global_status
integer, private :: group_id
integer, private :: group_leader_rank
logical, private :: has_result
integer(kind=int32), private :: local_dummy
logical, private :: local_message_pending
logical, private :: more_fragments
type(request_t), private :: req
type(MPI_Status), private :: status
integer(kind=int64), private :: worker_fragment_map(ctx%resources%mpi_comms%node_comm%size())
type(calculation_result_t), private :: worker_result
integer(kind=int32), private :: worker_source
Source Code
   subroutine node_coordinator_impl(ctx)
      !! Internal implementation of node_coordinator with typed context
      use mqc_many_body_expansion, only: many_body_expansion_t
      class(many_body_expansion_t), intent(in) :: ctx
      integer :: group_leader_rank, group_id
      integer(int64) :: fragment_idx
      integer(int32) :: fragment_size, fragment_type, dummy_msg
      integer(int32) :: finished_workers
      integer(int32), allocatable :: fragment_indices(:)
      type(MPI_Status) :: status, global_status
      logical :: local_message_pending, more_fragments, has_result
      integer(int32) :: local_dummy
      ! For tracking worker-fragment mapping and collecting results
      integer(int64) :: worker_fragment_map(ctx%resources%mpi_comms%node_comm%size())
      integer(int32) :: worker_source
      type(calculation_result_t) :: worker_result
      ! MPI request handles for non-blocking operations
      type(request_t) :: req
      call get_group_leader_rank(ctx, ctx%resources%mpi_comms%world_comm%rank(), group_leader_rank, group_id)
      if (group_leader_rank == ctx%resources%mpi_comms%world_comm%rank()) then
         call group_global_coordinator_impl(ctx)
         return
      end if
      finished_workers = 0
      more_fragments = .true.
      dummy_msg = 0
      worker_fragment_map = 0
      do while (finished_workers < ctx%resources%mpi_comms%node_comm%size() - 1)
         ! PRIORITY 1: Check for incoming results from local workers
         call iprobe(ctx%resources%mpi_comms%node_comm, MPI_ANY_SOURCE, TAG_WORKER_SCALAR_RESULT, has_result, status)
         if (has_result) then
            worker_source = status%MPI_SOURCE
            ! Safety check: worker should have a fragment assigned
            if (worker_fragment_map(worker_source) == 0) then
               call logger%error("Node coordinator received result from worker "//to_char(worker_source)// &
                                 " but no fragment was assigned!")
               call abort_comm(ctx%resources%mpi_comms%world_comm, 1)
            end if
            ! Receive result from worker
         call result_irecv(worker_result, ctx%resources%mpi_comms%node_comm, worker_source, TAG_WORKER_SCALAR_RESULT, req)
            call wait(req)
            ! Check for calculation errors before forwarding
            if (worker_result%has_error) then
               call logger%error("Fragment "//to_char(worker_fragment_map(worker_source))// &
                                 " calculation failed on worker "//to_char(worker_source)//": "// &
                                 worker_result%error%get_message())
               call abort_comm(ctx%resources%mpi_comms%world_comm, 1)
            end if
            ! Forward results to global coordinator with fragment index
            call isend(ctx%resources%mpi_comms%world_comm, worker_fragment_map(worker_source), &
                       group_leader_rank, TAG_NODE_SCALAR_RESULT, req)  ! fragment_idx
            call wait(req)
call result_isend(worker_result, ctx%resources%mpi_comms%world_comm, group_leader_rank, TAG_NODE_SCALAR_RESULT, req)  ! result
            call wait(req)
            ! Clear the mapping
            worker_fragment_map(worker_source) = 0
         end if
         ! PRIORITY 2: Check for work requests from local workers
         call iprobe(ctx%resources%mpi_comms%node_comm, MPI_ANY_SOURCE, TAG_WORKER_REQUEST, local_message_pending, status)
         if (local_message_pending) then
            ! Only process work request if this worker doesn't have pending results
            if (worker_fragment_map(status%MPI_SOURCE) == 0) then
               call irecv(ctx%resources%mpi_comms%node_comm, local_dummy, status%MPI_SOURCE, TAG_WORKER_REQUEST, req)
               call wait(req)
               if (more_fragments) then
                  call isend(ctx%resources%mpi_comms%world_comm, dummy_msg, group_leader_rank, TAG_NODE_REQUEST, req)
                  call wait(req)
                  call irecv(ctx%resources%mpi_comms%world_comm, fragment_idx, group_leader_rank, MPI_ANY_TAG, req)
                  call wait(req, global_status)
                  if (global_status%MPI_TAG == TAG_NODE_FRAGMENT) then
                     ! Receive fragment type (0 = monomer indices, 1 = intersection atom list)
                  call irecv(ctx%resources%mpi_comms%world_comm, fragment_type, group_leader_rank, TAG_NODE_FRAGMENT, req)
                     call wait(req)
                  call irecv(ctx%resources%mpi_comms%world_comm, fragment_size, group_leader_rank, TAG_NODE_FRAGMENT, req)
                     call wait(req)
                     ! Note: must use blocking recv for allocatable arrays since size is unknown
                     allocate (fragment_indices(fragment_size))
                     call recv(ctx%resources%mpi_comms%world_comm, fragment_indices, group_leader_rank, &
                               TAG_NODE_FRAGMENT, global_status)
                     ! Forward to worker
                  call isend(ctx%resources%mpi_comms%node_comm, fragment_idx, status%MPI_SOURCE, TAG_WORKER_FRAGMENT, req)
                     call wait(req)
                 call isend(ctx%resources%mpi_comms%node_comm, fragment_type, status%MPI_SOURCE, TAG_WORKER_FRAGMENT, req)
                     call wait(req)
                 call isend(ctx%resources%mpi_comms%node_comm, fragment_size, status%MPI_SOURCE, TAG_WORKER_FRAGMENT, req)
                     call wait(req)
              call isend(ctx%resources%mpi_comms%node_comm, fragment_indices, status%MPI_SOURCE, TAG_WORKER_FRAGMENT, req)
                     call wait(req)
                     ! Track which fragment was sent to this worker
                     worker_fragment_map(status%MPI_SOURCE) = fragment_idx
                     deallocate (fragment_indices)
                  else
                     call isend(ctx%resources%mpi_comms%node_comm, -1, status%MPI_SOURCE, TAG_WORKER_FINISH, req)
                     call wait(req)
                     finished_workers = finished_workers + 1
                     more_fragments = .false.
                  end if
               else
                  call isend(ctx%resources%mpi_comms%node_comm, -1, status%MPI_SOURCE, TAG_WORKER_FINISH, req)
                  call wait(req)
                  finished_workers = finished_workers + 1
               end if
            end if
         end if
      end do
   end subroutine node_coordinator_impl
Call graph
node_coordinator_impl calls abort_comm, error, iprobe, irecv, isend, error_get_message, get_group_leader_rank, group_global_coordinator_impl, result_irecv, result_isend, recv, to_char
group_global_coordinator_impl calls abort_comm, error, isend, get_group_leader_rank, flush_group_results, handle_group_node_requests, handle_local_worker_requests_group, handle_local_worker_results_to_batch, handle_node_results_to_batch, queue_destroy, queue_init_from_list, queue_is_empty, receive_group_assignment_matrix
result_irecv calls irecv, recv
result_isend calls isend, send
flush_group_results calls isend, result_isend, result_destroy
handle_group_node_requests calls iprobe, irecv, isend, queue_pop, send_fragment_payload_from_row
handle_local_worker_requests_group calls iprobe, irecv, isend, queue_pop, send_fragment_payload_from_row
handle_local_worker_results_to_batch calls abort_comm, error, iprobe, error_get_message, result_irecv, to_char, flush_group_results, append_result_to_batch, result_destroy
handle_node_results_to_batch calls abort_comm, error, iprobe, irecv, error_get_message, result_irecv, to_char, flush_group_results, append_result_to_batch, result_destroy
receive_group_assignment_matrix calls irecv, recv
result_destroy calls result_reset
send_fragment_payload_from_row calls isend, build_fragment_payload_from_row
result_reset calls energy_reset, error_clear
node_coordinator calls node_coordinator_impl, node_coordinator
gmbe_run_distributed calls node_coordinator
mbe_run_distributed calls node_coordinator