parse_fragments_section – metalquicha
parse_fragments_section Subroutine
7 statements
Source File
private subroutine parse_fragments_section(unit, config, stat, errmsg)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
type(mqc_config_t), intent(inout) :: config
integer, intent(out) :: stat
character(len=:), intent(out), allocatable :: errmsg
Calls
Called by
Source Code
   subroutine parse_fragments_section(unit, config, stat, errmsg)
      integer, intent(in) :: unit
      type(mqc_config_t), intent(inout) :: config
      integer, intent(out) :: stat
      character(len=:), allocatable, intent(out) :: errmsg
      call parse_fragments_generic(unit, config%nfrag, config%fragments, stat, errmsg)
   end subroutine parse_fragments_section
Call graph
parse_fragments_section calls parse_fragments_generic
parse_fragments_generic calls parse_fragment, skip_to_end, strip_comment
parse_fragment calls strip_comment, parse_indices_line
skip_to_end calls strip_comment
read_mqc_file calls parse_fragments_section
main calls read_mqc_file