parse_molecule_fragments – metalquicha
parse_molecule_fragments Subroutine
7 statements
Source File
private subroutine parse_molecule_fragments(unit, mol, stat, errmsg)
Parse %fragments section for a molecule
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
type(molecule_t), intent(inout) :: mol
integer, intent(out) :: stat
character(len=:), intent(out), allocatable :: errmsg
Calls
Called by
Source Code
   subroutine parse_molecule_fragments(unit, mol, stat, errmsg)
      !! Parse %fragments section for a molecule
      integer, intent(in) :: unit
      type(molecule_t), intent(inout) :: mol
      integer, intent(out) :: stat
      character(len=:), allocatable, intent(out) :: errmsg
      call parse_fragments_generic(unit, mol%nfrag, mol%fragments, stat, errmsg)
   end subroutine parse_molecule_fragments
Call graph
parse_molecule_fragments calls parse_fragments_generic
parse_fragments_generic calls parse_fragment, skip_to_end, strip_comment
parse_fragment calls strip_comment, parse_indices_line
skip_to_end calls strip_comment
parse_single_molecule calls parse_molecule_fragments
parse_molecules_section calls parse_single_molecule
read_mqc_file calls parse_molecules_section
main calls read_mqc_file