print_vibrational_json_mbe – metalquicha
print_vibrational_json_mbe Subroutine
263 statements
Source File
public subroutine print_vibrational_json_mbe(mbe_result, frequencies, reduced_masses, force_constants, thermo, ir_intensities)
Write vibrational analysis and thermochemistry results to JSON file for MBE calculations This is analogous to print_vibrational_json but takes mbe_result_t instead of calculation_result_t
Arguments
Type Intent Optional Attributes Name
type(mbe_result_t), intent(in) :: mbe_result
real(kind=dp), intent(in) :: frequencies(:)
real(kind=dp), intent(in) :: reduced_masses(:)
real(kind=dp), intent(in) :: force_constants(:)
type(thermochemistry_result_t), intent(in) :: thermo
real(kind=dp), intent(in), optional :: ir_intensities(:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=256), private :: basename
logical, private :: has_ir
integer, private :: i
integer, private :: io_stat
character(len=512), private :: json_line
integer, private :: n_modes
character(len=256), private :: output_file
integer, private :: unit
Source Code
   subroutine print_vibrational_json_mbe(mbe_result, frequencies, reduced_masses, force_constants, &
                                         thermo, ir_intensities)
      !! Write vibrational analysis and thermochemistry results to JSON file for MBE calculations
      !! This is analogous to print_vibrational_json but takes mbe_result_t instead of calculation_result_t
      type(mbe_result_t), intent(in) :: mbe_result
      real(dp), intent(in) :: frequencies(:)
      real(dp), intent(in) :: reduced_masses(:)
      real(dp), intent(in) :: force_constants(:)
      type(thermochemistry_result_t), intent(in) :: thermo
      real(dp), intent(in), optional :: ir_intensities(:)
      integer :: unit, io_stat, i, n_modes
      character(len=512) :: json_line
      character(len=256) :: output_file, basename
      logical :: has_ir
      output_file = get_output_json_filename()
      basename = get_basename()
      n_modes = size(frequencies)
      has_ir = present(ir_intensities)
      open (newunit=unit, file=trim(output_file), status='replace', action='write', iostat=io_stat)
      if (io_stat /= 0) then
         call logger%error("Failed to open "//trim(output_file)//" for writing")
         return
      end if
      call logger%info("Writing vibrational/thermochemistry JSON to "//trim(output_file))
      write (unit, '(a)') "{"
      write (json_line, '(a,a,a)') '  "', trim(basename), '": {'
      write (unit, '(a)') trim(json_line)
      ! Total energy
      if (mbe_result%has_energy) then
         write (json_line, '(a,f25.15,a)') '    "total_energy": ', mbe_result%total_energy, ','
         write (unit, '(a)') trim(json_line)
      end if
      ! Dipole
      if (mbe_result%has_dipole) then
         write (unit, '(a)') '    "dipole": {'
         write (json_line, '(a,f25.15,a)') '      "x": ', mbe_result%dipole(1), ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f25.15,a)') '      "y": ', mbe_result%dipole(2), ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f25.15,a)') '      "z": ', mbe_result%dipole(3), ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f25.15)') '      "magnitude_debye": ', norm2(mbe_result%dipole)*2.541746_dp
         write (unit, '(a)') trim(json_line)
         write (unit, '(a)') '    },'
      end if
      ! Gradient norm
      if (mbe_result%has_gradient) then
         write (json_line, '(a,f25.15,a)') '    "gradient_norm": ', sqrt(sum(mbe_result%gradient**2)), ','
         write (unit, '(a)') trim(json_line)
      end if
      ! Hessian norm
      if (mbe_result%has_hessian) then
         write (json_line, '(a,f25.15,a)') '    "hessian_frobenius_norm": ', sqrt(sum(mbe_result%hessian**2)), ','
         write (unit, '(a)') trim(json_line)
      end if
      ! Vibrational analysis section
      write (unit, '(a)') '    "vibrational_analysis": {'
      write (json_line, '(a,i0,a)') '      "n_modes": ', n_modes, ','
      write (unit, '(a)') trim(json_line)
      ! Frequencies array
      write (unit, '(a)', advance='no') '      "frequencies_cm1": ['
      do i = 1, n_modes
         if (i > 1) write (unit, '(a)', advance='no') ', '
         write (json_line, '(ES15.6)') frequencies(i)
         write (unit, '(a)', advance='no') trim(adjustl(json_line))
      end do
      write (unit, '(a)') '],'
      ! Reduced masses array
      write (unit, '(a)', advance='no') '      "reduced_masses_amu": ['
      do i = 1, n_modes
         if (i > 1) write (unit, '(a)', advance='no') ', '
         write (json_line, '(ES15.6)') reduced_masses(i)
         write (unit, '(a)', advance='no') trim(adjustl(json_line))
      end do
      write (unit, '(a)') '],'
      ! Force constants array
      write (unit, '(a)', advance='no') '      "force_constants_mdyne_ang": ['
      do i = 1, n_modes
         if (i > 1) write (unit, '(a)', advance='no') ', '
         write (json_line, '(ES15.6)') force_constants(i)
         write (unit, '(a)', advance='no') trim(adjustl(json_line))
      end do
      if (has_ir) then
         write (unit, '(a)') '],'
      else
         write (unit, '(a)') ']'
      end if
      ! IR intensities array (optional)
      if (has_ir) then
         write (unit, '(a)', advance='no') '      "ir_intensities_km_mol": ['
         do i = 1, n_modes
            if (i > 1) write (unit, '(a)', advance='no') ', '
            write (json_line, '(ES15.6)') ir_intensities(i)
            write (unit, '(a)', advance='no') trim(adjustl(json_line))
         end do
         write (unit, '(a)') ']'
      end if
      write (unit, '(a)') '    },'
      ! Thermochemistry section
      write (unit, '(a)') '    "thermochemistry": {'
      ! Conditions
      write (json_line, '(a,f10.4,a)') '      "temperature_K": ', thermo%temperature, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f10.4,a)') '      "pressure_atm": ', thermo%pressure, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f12.6,a)') '      "molecular_mass_amu": ', thermo%total_mass, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,i0,a)') '      "symmetry_number": ', thermo%symmetry_number, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,i0,a)') '      "spin_multiplicity": ', thermo%spin_multiplicity, ','
      write (unit, '(a)') trim(json_line)
      if (thermo%is_linear) then
         write (unit, '(a)') '      "is_linear": true,'
      else
         write (unit, '(a)') '      "is_linear": false,'
      end if
      write (json_line, '(a,i0,a)') '      "n_real_frequencies": ', thermo%n_real_freqs, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,i0,a)') '      "n_imaginary_frequencies": ', thermo%n_imag_freqs, ','
      write (unit, '(a)') trim(json_line)
      ! Moments of inertia and rotational constants
      write (unit, '(a)') '      "moments_of_inertia_amu_ang2": {'
      write (json_line, '(a,f15.8,a)') '        "Ia": ', thermo%moments(1), ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f15.8,a)') '        "Ib": ', thermo%moments(2), ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f15.8)') '        "Ic": ', thermo%moments(3)
      write (unit, '(a)') trim(json_line)
      write (unit, '(a)') '      },'
      write (unit, '(a)') '      "rotational_constants_GHz": {'
      write (json_line, '(a,f15.8,a)') '        "A": ', thermo%rot_const(1), ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f15.8,a)') '        "B": ', thermo%rot_const(2), ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f15.8)') '        "C": ', thermo%rot_const(3)
      write (unit, '(a)') trim(json_line)
      write (unit, '(a)') '      },'
      ! Partition functions
      write (unit, '(a)') '      "partition_functions": {'
      write (json_line, '(a,ES15.6,a)') '        "translational": ', thermo%q_trans, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f15.6,a)') '        "rotational": ', thermo%q_rot, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f15.6)') '        "vibrational": ', thermo%q_vib
      write (unit, '(a)') trim(json_line)
      write (unit, '(a)') '      },'
      ! Thermodynamic contributions
      write (unit, '(a)') '      "contributions": {'
      write (unit, '(a)') '        "translational": {'
      write (json_line, '(a,f18.12,a)') '          "energy_hartree": ', thermo%E_trans, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f12.6,a)') '          "entropy_cal_mol_K": ', thermo%S_trans, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f12.6)') '          "Cv_cal_mol_K": ', thermo%Cv_trans
      write (unit, '(a)') trim(json_line)
      write (unit, '(a)') '        },'
      write (unit, '(a)') '        "rotational": {'
      write (json_line, '(a,f18.12,a)') '          "energy_hartree": ', thermo%E_rot, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f12.6,a)') '          "entropy_cal_mol_K": ', thermo%S_rot, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f12.6)') '          "Cv_cal_mol_K": ', thermo%Cv_rot
      write (unit, '(a)') trim(json_line)
      write (unit, '(a)') '        },'
      write (unit, '(a)') '        "vibrational": {'
      write (json_line, '(a,f18.12,a)') '          "energy_hartree": ', thermo%E_vib, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f12.6,a)') '          "entropy_cal_mol_K": ', thermo%S_vib, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f12.6)') '          "Cv_cal_mol_K": ', thermo%Cv_vib
      write (unit, '(a)') trim(json_line)
      write (unit, '(a)') '        },'
      write (unit, '(a)') '        "electronic": {'
      write (json_line, '(a,f18.12,a)') '          "energy_hartree": ', thermo%E_elec, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f12.6)') '          "entropy_cal_mol_K": ', thermo%S_elec
      write (unit, '(a)') trim(json_line)
      write (unit, '(a)') '        }'
      write (unit, '(a)') '      },'
      ! Contribution table (matching stdout format)
      block
         real(dp) :: pV_cal, H_vib_cal, H_rot_cal, H_trans_cal, H_total_cal
         real(dp) :: Cv_total, S_total, S_total_J
         real(dp) :: H_int_cal, Cv_int, S_int, S_int_J
         real(dp) :: Cp_trans
         pV_cal = R_CALMOLK*thermo%temperature
         H_vib_cal = thermo%E_vib*HARTREE_TO_CALMOL
         H_rot_cal = thermo%E_rot*HARTREE_TO_CALMOL
         H_trans_cal = thermo%E_trans*HARTREE_TO_CALMOL + pV_cal
         H_total_cal = H_vib_cal + H_rot_cal + H_trans_cal
         H_int_cal = H_vib_cal + H_rot_cal
         Cp_trans = thermo%Cv_trans + R_CALMOLK
         Cv_int = thermo%Cv_vib + thermo%Cv_rot
         Cv_total = Cp_trans + thermo%Cv_rot + thermo%Cv_vib
         S_int = thermo%S_vib + thermo%S_rot
         S_int_J = S_int*4.184_dp
         S_total = thermo%S_trans + thermo%S_rot + thermo%S_vib + thermo%S_elec
         S_total_J = S_total*4.184_dp
         write (unit, '(a)') '      "contribution_table": {'
         ! VIB row
         write (unit, '(a)') '        "VIB": {'
         write (json_line, '(a,f12.4,a)') '          "H_cal_mol": ', H_vib_cal, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4,a)') '          "Cp_cal_mol_K": ', thermo%Cv_vib, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4,a)') '          "S_cal_mol_K": ', thermo%S_vib, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4)') '          "S_J_mol_K": ', thermo%S_vib*4.184_dp
         write (unit, '(a)') trim(json_line)
         write (unit, '(a)') '        },'
         ! ROT row
         write (unit, '(a)') '        "ROT": {'
         write (json_line, '(a,f12.4,a)') '          "H_cal_mol": ', H_rot_cal, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4,a)') '          "Cp_cal_mol_K": ', thermo%Cv_rot, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4,a)') '          "S_cal_mol_K": ', thermo%S_rot, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4)') '          "S_J_mol_K": ', thermo%S_rot*4.184_dp
         write (unit, '(a)') trim(json_line)
         write (unit, '(a)') '        },'
         ! INT row (internal = VIB + ROT)
         write (unit, '(a)') '        "INT": {'
         write (json_line, '(a,f12.4,a)') '          "H_cal_mol": ', H_int_cal, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4,a)') '          "Cp_cal_mol_K": ', Cv_int, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4,a)') '          "S_cal_mol_K": ', S_int, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4)') '          "S_J_mol_K": ', S_int_J
         write (unit, '(a)') trim(json_line)
         write (unit, '(a)') '        },'
         ! TR row (translational)
         write (unit, '(a)') '        "TR": {'
         write (json_line, '(a,f12.4,a)') '          "H_cal_mol": ', H_trans_cal, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4,a)') '          "Cp_cal_mol_K": ', Cp_trans, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4,a)') '          "S_cal_mol_K": ', thermo%S_trans, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4)') '          "S_J_mol_K": ', thermo%S_trans*4.184_dp
         write (unit, '(a)') trim(json_line)
         write (unit, '(a)') '        },'
         ! TOT row (total)
         write (unit, '(a)') '        "TOT": {'
         write (json_line, '(a,f12.4,a)') '          "H_cal_mol": ', H_total_cal, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4,a)') '          "Cp_cal_mol_K": ', Cv_total, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4,a)') '          "S_cal_mol_K": ', S_total, ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f12.4)') '          "S_J_mol_K": ', S_total_J
         write (unit, '(a)') trim(json_line)
         write (unit, '(a)') '        }'
         write (unit, '(a)') '      },'
      end block
      ! Zero-point energy
      write (json_line, '(a,f18.12,a)') '      "zero_point_energy_hartree": ', thermo%zpe_hartree, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f12.6,a)') '      "zero_point_energy_kcal_mol": ', thermo%zpe_kcalmol, ','
      write (unit, '(a)') trim(json_line)
      ! Thermal corrections
      write (unit, '(a)') '      "thermal_corrections_hartree": {'
      write (json_line, '(a,f18.12,a)') '        "to_energy": ', thermo%thermal_correction_energy, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f18.12,a)') '        "to_enthalpy": ', thermo%thermal_correction_enthalpy, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f18.12)') '        "to_gibbs": ', thermo%thermal_correction_gibbs
      write (unit, '(a)') trim(json_line)
      write (unit, '(a)') '      },'
      ! Total energies (with electronic energy)
      write (unit, '(a)') '      "total_energies_hartree": {'
      write (json_line, '(a,f20.12,a)') '        "electronic": ', mbe_result%total_energy, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f20.12,a)') '        "electronic_plus_zpe": ', &
         mbe_result%total_energy + thermo%zpe_hartree, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f20.12,a)') '        "electronic_plus_thermal_E": ', &
         mbe_result%total_energy + thermo%thermal_correction_energy, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f20.12,a)') '        "electronic_plus_thermal_H": ', &
         mbe_result%total_energy + thermo%thermal_correction_enthalpy, ','
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f20.12)') '        "electronic_plus_thermal_G": ', &
         mbe_result%total_energy + thermo%thermal_correction_gibbs
      write (unit, '(a)') trim(json_line)
      write (unit, '(a)') '      }'
      write (unit, '(a)') '    }'
      ! Close main object
      write (unit, '(a)') '  }'
      write (unit, '(a)') '}'
      close (unit)
      call logger%info("Vibrational/thermochemistry JSON written successfully to "//trim(output_file))
   end subroutine print_vibrational_json_mbe
Call graph
print_vibrational_json_mbe calls error, info, get_basename, get_output_json_filename
compute_mbe calls print_vibrational_json_mbe
gmbe_pie_coordinator calls print_vibrational_json_mbe
serial_gmbe_pie_processor calls print_vibrational_json_mbe
global_coordinator calls compute_mbe, global_coordinator
run_fragmented_calculation calls gmbe_pie_coordinator, serial_gmbe_pie_processor, global_coordinator, serial_fragment_processor
serial_fragment_processor calls compute_mbe, serial_fragment_processor
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations