queue_is_empty – metalquicha
queue_is_empty Function
4 statements
Source File
public pure function queue_is_empty(queue)
Arguments
Type Intent Optional Attributes Name
type(queue_t), intent(in) :: queue
Return Value logical
Called by
Source Code
   pure logical function queue_is_empty(queue)
      type(queue_t), intent(in) :: queue
      queue_is_empty = (queue%head > queue%count)
   end function queue_is_empty
Call graph
global_coordinator_impl calls queue_is_empty
gmbe_group_global_coordinator calls queue_is_empty
gmbe_pie_coordinator calls queue_is_empty
group_global_coordinator_impl calls queue_is_empty
global_coordinator calls global_coordinator_impl, global_coordinator
gmbe_run_distributed calls gmbe_group_global_coordinator, gmbe_pie_coordinator, node_coordinator
node_coordinator_impl calls group_global_coordinator_impl
node_coordinator calls node_coordinator_impl, node_coordinator
mbe_run_distributed calls global_coordinator, node_coordinator