queue_pop – metalquicha
queue_pop Subroutine
13 statements
Source File
public subroutine queue_pop(queue, item_idx, has_item)
Arguments
Type Intent Optional Attributes Name
type(queue_t), intent(inout) :: queue
integer(kind=int64), intent(out) :: item_idx
logical, intent(out) :: has_item
Called by
Source Code
   subroutine queue_pop(queue, item_idx, has_item)
      type(queue_t), intent(inout) :: queue
      integer(int64), intent(out) :: item_idx
      logical, intent(out) :: has_item
      if (queue%head > queue%count) then
         item_idx = -1_int64
         has_item = .false.
         return
      end if
      item_idx = queue%ids(queue%head)
      queue%head = queue%head + 1_int64
      has_item = .true.
   end subroutine queue_pop
Call graph
handle_group_node_requests calls queue_pop
handle_local_worker_requests calls queue_pop
handle_local_worker_requests_group calls queue_pop
handle_node_requests calls queue_pop
global_coordinator_impl calls handle_group_node_requests, handle_local_worker_requests_group
gmbe_group_global_coordinator calls handle_group_node_requests, handle_local_worker_requests_group
gmbe_pie_coordinator calls handle_group_node_requests, handle_local_worker_requests_group
group_global_coordinator_impl calls handle_group_node_requests, handle_local_worker_requests_group
global_coordinator calls global_coordinator_impl, global_coordinator
gmbe_run_distributed calls gmbe_group_global_coordinator, gmbe_pie_coordinator
node_coordinator_impl calls group_global_coordinator_impl
node_coordinator calls node_coordinator_impl, node_coordinator
mbe_run_distributed calls global_coordinator