queue_destroy – metalquicha
queue_destroy Subroutine
6 statements
Source File
public subroutine queue_destroy(queue)
Arguments
Type Intent Optional Attributes Name
type(queue_t), intent(inout) :: queue
Called by
Source Code
   subroutine queue_destroy(queue)
      type(queue_t), intent(inout) :: queue
      if (allocated(queue%ids)) deallocate (queue%ids)
      queue%head = 1_int64
      queue%count = 0_int64
   end subroutine queue_destroy
Call graph
global_coordinator_impl calls queue_destroy
group_global_coordinator_impl calls queue_destroy
global_coordinator calls global_coordinator_impl, global_coordinator
node_coordinator_impl calls group_global_coordinator_impl
node_coordinator calls node_coordinator_impl, node_coordinator
mbe_run_distributed calls global_coordinator, node_coordinator
gmbe_run_distributed calls node_coordinator