receive_group_assignment_matrix – metalquicha
receive_group_assignment_matrix Subroutine
27 statements
Source File
public subroutine receive_group_assignment_matrix(world_comm, ids, matrix)
Receive shard-assignment ids and polymer matrix from rank 0.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: world_comm
integer(kind=int64), intent(out), allocatable :: ids(:)
integer, intent(out), allocatable :: matrix(:,:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private, allocatable :: buf(:)
integer(kind=int32), private :: n_cols
integer(kind=int64), private :: n_rows
type(request_t), private :: req
type(MPI_Status), private :: status
Source Code
   subroutine receive_group_assignment_matrix(world_comm, ids, matrix)
      !! Receive shard-assignment ids and polymer matrix from rank 0.
      type(comm_t), intent(in) :: world_comm
      integer(int64), allocatable, intent(out) :: ids(:)
      integer, allocatable, intent(out) :: matrix(:, :)
      integer(int64) :: n_rows
      integer(int32) :: n_cols
      integer, allocatable :: buf(:)
      type(MPI_Status) :: status
      type(request_t) :: req
      call irecv(world_comm, n_rows, 0, TAG_GROUP_ASSIGN, req)
      call wait(req)
      allocate (ids(n_rows))
      call recv(world_comm, ids, 0, TAG_GROUP_ASSIGN, status)
      call irecv(world_comm, n_cols, 0, TAG_GROUP_POLYMERS, req)
      call wait(req)
      allocate (matrix(int(n_rows), n_cols))
      if (n_rows > 0_int64 .and. n_cols > 0) then
         allocate (buf(n_rows*n_cols))
         call recv(world_comm, buf, 0, TAG_GROUP_POLYMERS, status)
         matrix = reshape(buf, [int(n_rows), n_cols])
         deallocate (buf)
      else
         allocate (buf(0))
         call recv(world_comm, buf, 0, TAG_GROUP_POLYMERS, status)
         deallocate (buf)
      end if
   end subroutine receive_group_assignment_matrix
Call graph
receive_group_assignment_matrix calls irecv, recv
gmbe_group_global_coordinator calls receive_group_assignment_matrix
group_global_coordinator_impl calls receive_group_assignment_matrix
gmbe_run_distributed calls gmbe_group_global_coordinator, node_coordinator
node_coordinator_impl calls group_global_coordinator_impl
node_coordinator calls node_coordinator_impl, node_coordinator
mbe_run_distributed calls node_coordinator