result_irecv – metalquicha
result_irecv Subroutine
31 statements
Source File
public subroutine result_irecv(result, comm, source, tag, req)
Receive calculation result over MPI (non-blocking) Receives SCF energy (non-blocking) and other components (blocking)
Arguments
Type Intent Optional Attributes Name
type(calculation_result_t), intent(inout) :: result
type(comm_t), intent(in) :: comm
integer, intent(in) :: source
integer, intent(in) :: tag
type(request_t), intent(out) :: req
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(MPI_Status), private :: status
Source Code
   subroutine result_irecv(result, comm, source, tag, req)
      !! Receive calculation result over MPI (non-blocking)
      !! Receives SCF energy (non-blocking) and other components (blocking)
      type(calculation_result_t), intent(inout) :: result
      type(comm_t), intent(in) :: comm
      integer, intent(in) :: source, tag
      type(request_t), intent(out) :: req
      type(MPI_Status) :: status
      ! Receive SCF energy (non-blocking)
      call irecv(comm, result%energy%scf, source, tag, req)
      ! Receive other energy components (blocking to avoid needing multiple request handles)
      call recv(comm, result%energy%mp2%ss, source, tag, status)
      call recv(comm, result%energy%mp2%os, source, tag, status)
      call recv(comm, result%energy%cc%singles, source, tag, status)
      call recv(comm, result%energy%cc%doubles, source, tag, status)
      call recv(comm, result%energy%cc%triples, source, tag, status)
      result%has_energy = .true.
      ! Receive fragment metadata
      call recv(comm, result%distance, source, tag, status)
      ! Receive gradient flag and data (blocking to avoid needing multiple request handles)
      call recv(comm, result%has_gradient, source, tag, status)
      if (result%has_gradient) then
         ! Receive allocatable gradient array (MPI lib handles allocation)
         call recv(comm, result%gradient, source, tag, status)
      end if
      ! Receive Hessian flag and data (blocking to avoid needing multiple request handles)
      call recv(comm, result%has_hessian, source, tag, status)
      if (result%has_hessian) then
         ! Receive allocatable Hessian array (MPI lib handles allocation)
         call recv(comm, result%hessian, source, tag, status)
      end if
      ! Receive dipole flag and data (blocking to avoid needing multiple request handles)
      call recv(comm, result%has_dipole, source, tag, status)
      if (result%has_dipole) then
         ! Receive allocatable dipole array (MPI lib handles allocation)
         call recv(comm, result%dipole, source, tag, status)
      end if
      ! Receive dipole derivatives flag and data (blocking to avoid needing multiple request handles)
      call recv(comm, result%has_dipole_derivatives, source, tag, status)
      if (result%has_dipole_derivatives) then
         ! Receive allocatable dipole derivatives array (MPI lib handles allocation)
         call recv(comm, result%dipole_derivatives, source, tag, status)
      end if
   end subroutine result_irecv
Call graph
result_irecv calls irecv, recv
handle_group_results calls result_irecv
handle_local_worker_results calls result_irecv
handle_local_worker_results_to_batch calls result_irecv
handle_node_results calls result_irecv
handle_node_results_to_batch calls result_irecv
node_coordinator_impl calls result_irecv, group_global_coordinator_impl
global_coordinator_impl calls handle_group_results, handle_local_worker_results, handle_node_results
gmbe_group_global_coordinator calls handle_local_worker_results_to_batch, handle_node_results_to_batch
gmbe_pie_coordinator calls handle_group_results, handle_local_worker_results, handle_node_results
group_global_coordinator_impl calls handle_local_worker_results_to_batch, handle_node_results_to_batch
node_coordinator calls node_coordinator_impl, node_coordinator
global_coordinator calls global_coordinator_impl, global_coordinator
gmbe_run_distributed calls gmbe_group_global_coordinator, gmbe_pie_coordinator, node_coordinator
mbe_run_distributed calls node_coordinator, global_coordinator