result_reset – metalquicha
result_reset Subroutine
12 statements
Source File
private subroutine result_reset(this)
Reset all values and flags in calculation_result_t
Type Bound
calculation_result_t
Arguments
Type Intent Optional Attributes Name
class(calculation_result_t), intent(inout) :: this
Calls
Called by
Source Code
   subroutine result_reset(this)
      !! Reset all values and flags in calculation_result_t
      class(calculation_result_t), intent(inout) :: this
      call this%energy%reset()
      call this%error%clear()
      this%has_energy = .false.
      this%has_gradient = .false.
      this%has_sigma = .false.
      this%has_hessian = .false.
      this%has_dipole = .false.
      this%has_dipole_derivatives = .false.
      this%has_error = .false.
   end subroutine result_reset
Call graph
result_reset calls energy_reset, error_clear
energy_reset calls mp2_reset
result_destroy calls result_reset
compute_energy_and_forces calls result_destroy
flush_group_results calls result_destroy
handle_local_worker_results_to_batch calls result_destroy, flush_group_results
handle_node_results_to_batch calls result_destroy, flush_group_results
hessian_coordinator calls result_destroy, hessian_coordinator
hessian_worker calls result_destroy, hessian_worker
unfragmented_calculation calls result_destroy, unfragmented_calculation
xtb_calc_hessian calls result_destroy
gmbe_group_global_coordinator calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
group_global_coordinator_impl calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
distributed_unfragmented_hessian calls hessian_coordinator, hessian_worker, distributed_unfragmented_hessian
gmbe_run_distributed calls gmbe_group_global_coordinator
node_coordinator_impl calls group_global_coordinator_impl
run_unfragmented_calculation calls unfragmented_calculation
node_coordinator calls node_coordinator_impl
run_calculation calls run_unfragmented_calculation