result_isend – metalquicha
result_isend Subroutine
29 statements
Source File
public subroutine result_isend(result, comm, dest, tag, req)
Send calculation result over MPI (non-blocking) Sends SCF energy (non-blocking) and other components (blocking)
Arguments
Type Intent Optional Attributes Name
type(calculation_result_t), intent(in) :: result
type(comm_t), intent(in) :: comm
integer, intent(in) :: dest
integer, intent(in) :: tag
type(request_t), intent(out) :: req
Calls
Called by
Source Code
   subroutine result_isend(result, comm, dest, tag, req)
      !! Send calculation result over MPI (non-blocking)
      !! Sends SCF energy (non-blocking) and other components (blocking)
      type(calculation_result_t), intent(in) :: result
      type(comm_t), intent(in) :: comm
      integer, intent(in) :: dest, tag
      type(request_t), intent(out) :: req
      ! Send SCF energy (non-blocking)
      call isend(comm, result%energy%scf, dest, tag, req)
      ! Send other energy components (blocking to avoid needing multiple request handles)
      call send(comm, result%energy%mp2%ss, dest, tag)
      call send(comm, result%energy%mp2%os, dest, tag)
      call send(comm, result%energy%cc%singles, dest, tag)
      call send(comm, result%energy%cc%doubles, dest, tag)
      call send(comm, result%energy%cc%triples, dest, tag)
      ! Send fragment metadata
      call send(comm, result%distance, dest, tag)
      ! Send gradient flag and data (blocking to avoid needing multiple request handles)
      call send(comm, result%has_gradient, dest, tag)
      if (result%has_gradient) then
         call send(comm, result%gradient, dest, tag)
      end if
      ! Send Hessian flag and data (blocking to avoid needing multiple request handles)
      call send(comm, result%has_hessian, dest, tag)
      if (result%has_hessian) then
         call send(comm, result%hessian, dest, tag)
      end if
      ! Send dipole flag and data (blocking to avoid needing multiple request handles)
      call send(comm, result%has_dipole, dest, tag)
      if (result%has_dipole) then
         call send(comm, result%dipole, dest, tag)
      end if
      ! Send dipole derivatives flag and data (blocking to avoid needing multiple request handles)
      call send(comm, result%has_dipole_derivatives, dest, tag)
      if (result%has_dipole_derivatives) then
         call send(comm, result%dipole_derivatives, dest, tag)
      end if
   end subroutine result_isend
Call graph
result_isend calls isend, send
flush_group_results calls result_isend
node_coordinator_impl calls result_isend, group_global_coordinator_impl
node_worker_impl calls result_isend
gmbe_group_global_coordinator calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
group_global_coordinator_impl calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
handle_local_worker_results_to_batch calls flush_group_results
handle_node_results_to_batch calls flush_group_results
node_coordinator calls node_coordinator_impl, node_coordinator
node_worker calls node_worker_impl, node_worker
gmbe_run_distributed calls gmbe_group_global_coordinator, node_coordinator, node_worker
mbe_run_distributed calls node_coordinator, node_worker