result_destroy – metalquicha
result_destroy Subroutine
9 statements
Source File
private subroutine result_destroy(this)
Clean up allocated memory in calculation_result_t
Type Bound
calculation_result_t
Arguments
Type Intent Optional Attributes Name
class(calculation_result_t), intent(inout) :: this
Calls
Called by
Source Code
   subroutine result_destroy(this)
      !! Clean up allocated memory in calculation_result_t
      class(calculation_result_t), intent(inout) :: this
      if (allocated(this%gradient)) deallocate (this%gradient)
      if (allocated(this%sigma)) deallocate (this%sigma)
      if (allocated(this%hessian)) deallocate (this%hessian)
      if (allocated(this%dipole)) deallocate (this%dipole)
      if (allocated(this%dipole_derivatives)) deallocate (this%dipole_derivatives)
      call this%reset()
   end subroutine result_destroy
Call graph
result_destroy calls result_reset
result_reset calls energy_reset, error_clear
energy_reset calls mp2_reset
compute_energy_and_forces calls result_destroy, run_calculation
flush_group_results calls result_destroy
handle_local_worker_results_to_batch calls result_destroy, flush_group_results
handle_node_results_to_batch calls result_destroy, flush_group_results
hessian_coordinator calls result_destroy, hessian_coordinator
hessian_worker calls result_destroy, hessian_worker
unfragmented_calculation calls result_destroy, unfragmented_calculation
xtb_calc_hessian calls result_destroy
gmbe_group_global_coordinator calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
group_global_coordinator_impl calls flush_group_results, handle_local_worker_results_to_batch, handle_node_results_to_batch
distributed_unfragmented_hessian calls hessian_coordinator, hessian_worker, distributed_unfragmented_hessian
gmbe_run_distributed calls gmbe_group_global_coordinator
node_coordinator_impl calls group_global_coordinator_impl
run_unfragmented_calculation calls unfragmented_calculation, distributed_unfragmented_hessian
node_coordinator calls node_coordinator_impl, node_coordinator
run_calculation calls run_unfragmented_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation