send_fragment_to_node – metalquicha
send_fragment_to_node Subroutine
7 statements
Source File
subroutine send_fragment_to_node(world_comm, fragment_idx, polymers, dest_rank)
Send fragment data to remote node coordinator Uses int64 for fragment_idx to handle large fragment indices that overflow int32.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: world_comm
integer(kind=int64), intent(in) :: fragment_idx
integer, intent(in) :: polymers(:,:)
integer, intent(in) :: dest_rank
Calls
Called by
Source Code
   subroutine send_fragment_to_node(world_comm, fragment_idx, polymers, dest_rank)
      !! Send fragment data to remote node coordinator
      !! Uses int64 for fragment_idx to handle large fragment indices that overflow int32.
      type(comm_t), intent(in) :: world_comm
      integer(int64), intent(in) :: fragment_idx
      integer, intent(in) :: dest_rank
      integer, intent(in) :: polymers(:, :)
      call send_fragment_payload(world_comm, TAG_NODE_FRAGMENT, fragment_idx, polymers, dest_rank)
   end subroutine send_fragment_to_node
Call graph
send_fragment_to_node calls send_fragment_payload
send_fragment_payload calls isend, build_fragment_payload
handle_node_requests calls send_fragment_to_node