serial_gmbe_processor – metalquicha
serial_gmbe_processor Subroutine
61 statements
Source File
public subroutine serial_gmbe_processor(n_monomers, polymers, intersections, intersection_sets, intersection_levels, n_intersections, sys_geom, method, calc_type, bonds)
Uses
mqc_mbe
Serial GMBE processor: builds all fragments (monomers + intersections) and computes GMBE energy
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n_monomers
Number of monomers
integer, intent(in) :: polymers(:,:)
Monomer indices (n_monomers, 1)
integer, intent(in) :: intersections(:,:)
Intersection atom lists
integer, intent(in) :: intersection_sets(:,:)
k-tuples that created intersections
integer, intent(in) :: intersection_levels(:)
Level k of each intersection
integer, intent(in) :: n_intersections
Number of intersection fragments
type(system_geometry_t), intent(in) :: sys_geom
integer(kind=int32), intent(in) :: method
integer(kind=int32), intent(in) :: calc_type
type(bond_t), intent(in), optional :: bonds(:)
Calls
Variables
Type Visibility Attributes Name Initial
type(calculation_result_t), private, allocatable :: all_results(:)
integer, private :: i
integer, private :: intersection_size
integer, private, allocatable :: monomer_idx(:)
integer, private, allocatable :: monomer_indices(:)
type(physical_fragment_t), private :: phys_frag
real(kind=dp), private :: total_energy
Source Code
   subroutine serial_gmbe_processor(n_monomers, polymers, intersections, intersection_sets, intersection_levels, &
                                    n_intersections, sys_geom, method, calc_type, bonds)
      !! Serial GMBE processor: builds all fragments (monomers + intersections) and computes GMBE energy
      use mqc_mbe, only: compute_gmbe_energy
      integer, intent(in) :: n_monomers  !! Number of monomers
      integer, intent(in) :: polymers(:, :)  !! Monomer indices (n_monomers, 1)
      integer, intent(in) :: intersections(:, :)  !! Intersection atom lists
      integer, intent(in) :: intersection_sets(:, :)  !! k-tuples that created intersections
      integer, intent(in) :: intersection_levels(:)  !! Level k of each intersection
      integer, intent(in) :: n_intersections  !! Number of intersection fragments
      type(system_geometry_t), intent(in) :: sys_geom
      integer(int32), intent(in) :: method, calc_type
      type(bond_t), intent(in), optional :: bonds(:)
      type(calculation_result_t), allocatable :: all_results(:)
      type(physical_fragment_t) :: phys_frag
      integer :: i, intersection_size
      integer, allocatable :: monomer_idx(:), monomer_indices(:)
      real(dp) :: total_energy
      ! Total results = monomers + intersections
      allocate (all_results(n_monomers + n_intersections))
      ! Build and calculate monomers
      call logger%info("Processing "//to_char(n_monomers)//" monomer fragments...")
      do i = 1, n_monomers
         allocate (monomer_idx(1))
         monomer_idx(1) = polymers(i, 1)
         ! Use build_fragment_from_indices for monomers to preserve fragment charges/multiplicities
         call build_fragment_from_indices(sys_geom, monomer_idx, phys_frag, bonds)
         call do_fragment_work(i, all_results(i), method, phys_frag, calc_type)
         call phys_frag%destroy()
         deallocate (monomer_idx)
      end do
      ! Build and calculate intersections
      if (n_intersections > 0) then
         call logger%info("Processing "//to_char(n_intersections)//" intersection fragments...")
         do i = 1, n_intersections
            ! Find size of this intersection (first zero marks end)
            intersection_size = 0
            do while (intersection_size < size(intersections, 1))
               if (intersections(intersection_size + 1, i) == 0) exit
               intersection_size = intersection_size + 1
            end do
            ! Build intersection fragment from atom list
            call build_fragment_from_atom_list(sys_geom, intersections(1:intersection_size, i), &
                                               intersection_size, phys_frag, bonds)
            call do_fragment_work(n_monomers + i, all_results(n_monomers + i), method, phys_frag, calc_type)
            call phys_frag%destroy()
         end do
      end if
      ! Compute GMBE energy
      allocate (monomer_indices(n_monomers))
      do i = 1, n_monomers
         monomer_indices(i) = polymers(i, 1)
      end do
      call compute_gmbe_energy(monomer_indices, n_monomers, all_results(1:n_monomers), &
                               n_intersections, all_results(n_monomers + 1:n_monomers + n_intersections), &
                               intersection_sets, intersection_levels, total_energy)
      call logger%info(" ")
      call logger%info("GMBE calculation completed successfully")
      call logger%info("Final GMBE energy: "//to_char(total_energy)//" Hartree")
      call logger%info(" ")
      ! Write JSON output
      if (n_intersections > 0) then
         call print_gmbe_json(n_monomers, monomer_indices, all_results(1:n_monomers), &
                              n_intersections, all_results(n_monomers + 1:n_monomers + n_intersections), &
                              intersection_sets, intersection_levels, total_energy)
      else
         ! No intersections - need dummy arrays
         block
            integer, allocatable :: dummy_sets(:, :), dummy_levels(:)
            type(calculation_result_t), allocatable :: dummy_results(:)
            allocate (dummy_sets(1, 0), dummy_levels(0), dummy_results(0))
            call print_gmbe_json(n_monomers, monomer_indices, all_results(1:n_monomers), &
                                 0, dummy_results, &
                                 dummy_sets, dummy_levels, total_energy)
            deallocate (dummy_sets, dummy_levels, dummy_results)
         end block
      end if
      deallocate (all_results, monomer_indices)
   end subroutine serial_gmbe_processor
Call graph
serial_gmbe_processor calls dummy_levels, dummy_results, dummy_sets, info, build_fragment_from_atom_list, build_fragment_from_indices, compute_gmbe_energy, do_fragment_work, fragment_destroy, print_gmbe_json, to_char
build_fragment_from_atom_list calls check_duplicate_atoms, fragment_compute_nelec
build_fragment_from_indices calls check_duplicate_atoms, fragment_compute_nelec
compute_gmbe_energy calls info, debug, energy_total
do_fragment_work calls configuration, error, calc_type_to_string, energy_reset, method_type_to_string, print_fragment_xyz, xtb_calc_energy, xtb_calc_gradient
fragment_destroy calls basis_set_destroy
print_gmbe_json calls info, error, energy_total, get_basename, get_output_json_filename
basis_set_destroy calls atomic_basis_destroy
check_duplicate_atoms calls to_char, error, element_number_to_symbol
energy_reset calls mp2_reset
energy_total calls mp2_total
print_fragment_xyz calls info, to_char, element_number_to_symbol, to_angstrom
xtb_calc_energy calls energy_total, new, new_gfn1_calculator, new_gfn2_calculator, new_wavefunction, xtb_singlepoint
xtb_calc_gradient calls energy_total, new, new_gfn1_calculator, new_gfn2_calculator, new_wavefunction, xtb_singlepoint
atomic_basis_destroy calls cgto_destroy