to_angstrom – metalquicha
to_angstrom Function
5 statements
Source File
public pure elemental function to_angstrom(bohr_value) result(angstrom_value)
Convert coordinate from Bohr to Angstrom
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: bohr_value
Return Value real(kind=dp)
Called by
Source Code
   pure elemental function to_angstrom(bohr_value) result(angstrom_value)
      !! Convert coordinate from Bohr to Angstrom
      real(dp), intent(in) :: bohr_value
      real(dp) :: angstrom_value
      angstrom_value = bohr_value*BOHR_TO_ANGSTROM
   end function to_angstrom
Call graph
calculate_fragment_distances calls to_angstrom
calculate_monomer_distance calls to_angstrom
print_fragment_xyz calls to_angstrom
build_fragment_from_indices calls calculate_monomer_distance
do_fragment_work calls print_fragment_xyz, do_fragment_work
fragment_should_be_screened calls calculate_monomer_distance
apply_distance_screening calls fragment_should_be_screened
compute_gmbe calls build_fragment_from_indices
map_fragment_to_system_dipole_derivatives calls build_fragment_from_indices
map_fragment_to_system_gradient calls build_fragment_from_indices
map_fragment_to_system_hessian calls build_fragment_from_indices
node_worker_impl calls build_fragment_from_indices, do_fragment_work
serial_fragment_processor calls build_fragment_from_indices, do_fragment_work, compute_mbe, serial_fragment_processor
compute_mbe calls map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives
compute_mbe_gradient calls map_fragment_to_system_gradient
compute_mbe_hessian calls map_fragment_to_system_hessian
node_worker calls node_worker_impl, node_worker
run_fragmented_calculation calls apply_distance_screening
serial_gmbe_pie_processor calls do_fragment_work
unfragmented_calculation calls do_fragment_work, unfragmented_calculation
global_coordinator_impl calls compute_mbe
gmbe_run_serial calls serial_gmbe_pie_processor
mbe_run_serial calls serial_fragment_processor
run_calculation calls run_fragmented_calculation