#!/usr/bin/env python3
"""Write basis_sets/minao/minao.json, the minimal ANO basis the `minao` guess uses.

PySCF's init_guess_by_minao (pyscf/scf/hf.py) builds its starting density in the
leading contractions of its 'ano' basis (pyscf/gto/basis/ano.dat, ANO-RCC):
for each angular momentum l, the columns that are doubly occupied in the
spherically averaged ground state plus the open shell. Which columns those are
follows from pyscf.data.elements.NRSRHF_CONFIGURATION through
pyscf.scf.atom_hf.frac_occ.

PySCF keeps a trailing column even when the open shell is empty (fractional
occupation zero, and for every l an element has no electrons in). A column with
zero occupation adds nothing to the projected density, so it is left out here,
which keeps hydrogen from carrying p, d and f functions it never uses.

The occupations themselves are not written: mqc_czt_minao carries the same
NRSRHF_CONFIGURATION table and derives the column count from it, and checks the
file agrees.

Run from the repository root with PySCF importable:

    python3 tools/minao/gen_minao_basis.py
"""
import json
import pathlib

import pyscf
from pyscf import gto
from pyscf.data import elements
from pyscf.scf import atom_hf

Z_MAX = 36  # H through Kr
OUT = pathlib.Path("basis_sets/minao/minao.json")


def columns_kept(symbol, l):
    ndocc, frac = atom_hf.frac_occ(symbol, l)
    return ndocc + (1 if frac > 0 else 0)


def element_shells(z):
    symbol = elements.ELEMENTS[z]
    ano = gto.basis.load("ano", symbol)
    shells = []
    for l in range(4):
        ncol = columns_kept(symbol, l)
        if ncol == 0:
            continue
        # One generally contracted shell per l, in order, in PySCF's ano data.
        block = ano[l]
        assert block[0] == l, (symbol, l, block[0])
        prims = block[1:]
        assert len(prims[0]) - 1 >= ncol, (symbol, l, ncol)
        shells.append({
            "function_type": "gto_spherical" if l >= 2 else "gto",
            "region": "",
            "angular_momentum": [l],
            "exponents": ["%.10E" % p[0] for p in prims],
            "coefficients": [["%.10E" % p[1 + c] for p in prims] for c in range(ncol)],
        })
    return {"electron_shells": shells}


def main():
    data = {
        "molssi_bse_schema": {"schema_type": "element", "schema_version": "0.1"},
        "name": "MINAO",
        "description": (
            "Leading ANO-RCC contractions per occupied shell, H-Kr, as PySCF's "
            "minao initial guess uses them. Generated by "
            "tools/minao/gen_minao_basis.py from PySCF " + pyscf.__version__ +
            " gto/basis/ano.dat; zero-occupation columns dropped."),
        "function_types": ["gto", "gto_spherical"],
        "elements": {str(z): element_shells(z) for z in range(1, Z_MAX + 1)},
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(data, indent=1) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
