"""Emit the Lebedev-Laikov orbit parameters as a Fortran data module.

Input is lebedev.json from extract_lebedev.py. Output is a module of plain
parameter arrays: the seed parameters (a, b) and weight for each octahedral
orbit, flattened across all 32 orders with an offset table.

The arrays are emitted in chunks and concatenated, because a single array
constructor of 1287 elements would blow past the 255-continuation-line limit.
"""
import json
import sys

CHUNK = 300  # records per chunk; keeps each constructor well under 255 lines


def reals(name, values, per_line=4):
    """A real parameter array, chunked and concatenated."""
    out, parts = [], []
    for ci, start in enumerate(range(0, len(values), CHUNK), 1):
        block = values[start:start + CHUNK]
        part = f"{name}_{ci}"
        parts.append(part)
        out.append(f"   real(dp), parameter :: {part}(*) = [ &")
        for i in range(0, len(block), per_line):
            row = ", ".join(f"{v!r}_dp" for v in block[i:i + per_line])
            tail = " &" if i + per_line < len(block) else " ]"
            out.append(f"      {row},{tail}" if tail == " &" else f"      {row}{tail}")
        out.append("")
    out.append(f"   real(dp), parameter :: {name}(*) = [{', '.join(parts)}]")
    out.append("")
    return out


def ints(name, values, per_line=20):
    out = [f"   integer, parameter :: {name}(*) = [ &"]
    for i in range(0, len(values), per_line):
        row = ", ".join(str(v) for v in values[i:i + per_line])
        tail = " &" if i + per_line < len(values) else " ]"
        out.append(f"      {row},{tail}" if tail == " &" else f"      {row}{tail}")
    out.append("")
    return out


def main(path):
    params = json.load(open(path))["params"]
    orders = sorted((int(k) for k in params), key=int)

    codes, aa, bb, ww, offsets = [], [], [], [], [1]
    for o in orders:
        for code, a, b, v in params[str(o)]:
            codes.append(code)
            aa.append(a)
            bb.append(b)
            ww.append(v)
        offsets.append(len(codes) + 1)

    L = []
    L.append("module mqc_lebedev_data")
    L.append("   !! Lebedev-Laikov octahedral orbit parameters, orders 6 to 5810")
    L.append("   !!")
    L.append("   !! Each record is one orbit of the octahedral group: a code saying which")
    L.append("   !! orbit type, the seed parameters a and b, and the weight carried by every")
    L.append("   !! point in it. `mqc_lebedev` expands them into points. Records for order")
    L.append("   !! LEBEDEV_ORDERS(i) run from ORDER_OFFSET(i) to ORDER_OFFSET(i+1)-1.")
    L.append("   !!")
    L.append("   !! These are the published Lebedev-Laikov parameters [V.I. Lebedev and")
    L.append("   !! D.N. Laikov, Dokl. Math. 59, 477 (1999)] and integrate polynomials up to")
    L.append("   !! degree 131 to a relative accuracy of 2e-14. The weights of each grid sum")
    L.append("   !! to 1, so the surface of the unit sphere is normalised out.")
    L.append("   !!")
    L.append("   !! Generated by scratchpad/gen_lebedev_fortran.py -- do not edit by hand.")
    L.append("   use pic_types, only: dp")
    L.append("   implicit none")
    L.append("   private")
    L.append("")
    L.append("   public :: LEBEDEV_ORDERS, ORDER_OFFSET, ORBIT_CODE, ORBIT_A, ORBIT_B, ORBIT_W")
    L.append("")
    L += ints("LEBEDEV_ORDERS", orders, per_line=8)
    L += ints("ORDER_OFFSET", offsets, per_line=8)
    L += ints("ORBIT_CODE", codes)
    L += reals("ORBIT_A", aa)
    L += reals("ORBIT_B", bb)
    L += reals("ORBIT_W", ww)
    L.append("end module mqc_lebedev_data")
    print("\n".join(L))


main(sys.argv[1])
