"""Emit the radial-grid element tables as a Fortran data module.

    python gen_radial_fortran.py radial.json > ../../src/methods/mqc_dft_radial_data.f90

Table names carry a _TABLE suffix because Fortran does not distinguish
identifiers by case: a TREUTLER_XI array and a treutler_xi accessor are the
same name, and the module will not compile.
"""
import json
import sys


def arr(name, vals, bound, per_line=4):
    # The named bound, not the literal: fortitude's C031 rejects a magic number
    # in an array size, and the module already declares MAX_XI_Z / MAX_BRAGG_Z
    # right above. Emitting 0:103 there meant the generated file failed the
    # linter while the hand-written one beside it passed.
    out = [f"   real(dp), parameter :: {name}(0:{bound}) = [ &"]
    for i in range(0, len(vals), per_line):
        row = ", ".join(f"{v!r}_dp" for v in vals[i:i + per_line])
        out.append(f"      {row}, &" if i + per_line < len(vals) else f"      {row}]")
    return out + [""]


d = json.load(open(sys.argv[1]))
xi, bragg = d["xi"], d["bragg"]

L = ["module mqc_dft_radial_data",
     "   !! Element tables for radial DFT quadrature",
     "   !!",
     "   !! TREUTLER_XI_TABLE: the per-element radius parameter of the",
     "   !! Treutler-Ahlrichs M4 mapping. H to Kr are the values optimised in the",
     "   !! original paper [JCP 102, 346 (1995)]; heavier elements are the Psi4",
     "   !! values, which is also where PySCF takes them from. Index 0 is a ghost.",
     "   !!",
     "   !! BRAGG_RADII_TABLE: Bragg-Slater atomic radii in Bohr, used to size the",
     "   !! partition cells. Runs to Z=130, so nothing in the periodic table falls",
     "   !! back to a default.",
     "   !!",
     "   !! Generated by tools/dft_grid/gen_radial_fortran.py -- do not edit by hand.",
     "   use pic_types, only: dp",
     "   implicit none",
     "   private",
     "",
     "   public :: TREUTLER_XI_TABLE, BRAGG_RADII_TABLE, MAX_XI_Z, MAX_BRAGG_Z",
     "",
     f"   integer, parameter :: MAX_XI_Z = {len(xi)-1}",
     f"   integer, parameter :: MAX_BRAGG_Z = {len(bragg)-1}",
     ""]
L += arr("TREUTLER_XI_TABLE", xi, "MAX_XI_Z")
L += arr("BRAGG_RADII_TABLE", bragg, "MAX_BRAGG_Z")
L.append("end module mqc_dft_radial_data")
print("\n".join(L))
