!! Manual check of the distributed LMO polarizabilities against GAMESS
!!
!!     cmake -B build -DMQC_ENABLE_LIBCINT=ON
!!     ./build/check_distributed_polarizability
!!     python3 validation/check_distributed_polarizability.py
!!
!! Milestone 5 of the EFP plan, and the first one checked against GAMESS rather
!! than PySCF. The reference is `tools/efp_validation/reference/`, generated by
!! the local GAMESS with `RUNTYP=MAKEFP LOCAL=BOYS`.
!!
!! The sum rule and the asymmetry structure are unit-tested, needing nothing
!! external. What is left for here is the part only another program can settle:
!! whether our localized orbitals land where GAMESS's do, and whether the tensor
!! on each of them agrees. Those are separable failures -- centroids can match
!! while tensors do not -- so the Python reports them separately.
program check_distributed_polarizability
   use pic_types, only: dp
   use mqc_libcint_integrals, only: libcint_molecule_t, build_libcint_molecule
   use mqc_libcint_rhf, only: rhf_result_t, run_libcint_rhf
   use mqc_libcint_cphf, only: distributed_polarizability, static_polarizability
   use mqc_error, only: error_t
   implicit none

   !> Bohr per Angstrom **as GAMESS converts it**, not as CODATA now has it.
   !>
   !> GAMESS uses 0.52917724924 Angstrom per Bohr, an older CODATA value; the
   !> current one is 0.529177210903, which is what the rest of this repository
   !> uses. The difference is 7e-8 relative -- invisible in an energy, and not
   !> invisible here. Converting water's geometry with our constant put every
   !> coordinate 1.3e-7 Bohr from GAMESS's, which is a *different molecule* by the
   !> standards of a parameter comparison and would have been charged against the
   !> partition instead of against arithmetic.
   !>
   !> So a program that compares against a GAMESS potential converts the way
   !> GAMESS does. `0.9584 * this` reproduces their printed 1.8111133866 exactly.
   !> Programs that compare against PySCF must *not* use this -- PySCF is on the
   !> current value, and this is the same trap as feeding it a different basis
   !> table.
   real(dp), parameter :: ANG = 1.0_dp/0.52917724924_dp
   integer :: failures

   failures = 0
   ! Water in 6-31G*, one core orbital excluded -- the arrangement GAMESS's
   ! reference potential uses, and the reason `n_core` exists.
   call one_case(1, "6-31g*", 1)
   ! And with nothing excluded, so the Python can confirm the whole occupied
   ! space reproduces the total exactly while the valence set does not.
   call one_case(2, "6-31g*", 0)

   write (*, "(A)") ""
   if (failures == 0) then
      write (*, "(A)") "[distributed] wrote every case; run "// &
         "validation/check_distributed_polarizability.py"
   else
      write (*, "(A,I0,A)") "[distributed] ", failures, " FAILURE(S)"
      error stop 1
   end if

contains

   subroutine one_case(case_index, basis, n_core)
      integer, intent(in) :: case_index
      character(len=*), intent(in) :: basis
      integer, intent(in) :: n_core

      type(libcint_molecule_t) :: mol
      type(rhf_result_t) :: scf
      type(error_t) :: err
      real(dp), allocatable :: tensors(:, :, :), centroids(:, :)
      real(dp) :: c(3, 3), alpha(3, 3), total(3, 3)
      real(dp) :: sum_asym, worst_single
      integer :: unit, i, n_lmo
      character(len=64) :: name

      c = reshape([0.0_dp, 0.0_dp, 0.0_dp, &
                   0.0_dp, 0.0_dp, 0.9584_dp*ANG, &
                   0.9268_dp*ANG, 0.0_dp, -0.2400_dp*ANG], [3, 3])

      call build_libcint_molecule([8, 1, 1], ["O ", "H ", "H "], c, basis, mol, err)
      if (err%has_error()) then
         write (*, "(A,A)") "[distributed] basis failed: ", err%get_message()
         failures = failures + 1
         return
      end if

      call run_libcint_rhf(mol, 10, 200, 1.0e-12_dp, 1.0e-10_dp, .false., scf, err, &
                           in_core=.true.)
      if (err%has_error() .or. .not. scf%converged) then
         write (*, "(A)") "[distributed] SCF failed"
         failures = failures + 1
         call mol%destroy()
         return
      end if

      call static_polarizability(mol, scf%orbitals, scf%orbital_energies, &
                                 scf%n_occupied, alpha, err)
      if (.not. err%has_error()) then
         call distributed_polarizability(mol, scf%orbitals, scf%orbital_energies, &
                                         scf%n_occupied, tensors, centroids, err, &
                                         n_core=n_core)
      end if
      if (err%has_error()) then
         write (*, "(A,A)") "[distributed] failed: ", err%get_message()
         failures = failures + 1
         call mol%destroy()
         return
      end if

      n_lmo = size(tensors, 3)
      total = 0.0_dp
      worst_single = 0.0_dp
      do i = 1, n_lmo
         total = total + tensors(:, :, i)
         worst_single = max(worst_single, &
                            maxval(abs(tensors(:, :, i) - transpose(tensors(:, :, i)))))
      end do
      sum_asym = maxval(abs(total - transpose(total)))

      write (name, "(A,I0,A)") "/tmp/mqc_distributed_", case_index, ".txt"
      open (newunit=unit, file=trim(name), status="replace", action="write")
      write (unit, "(A)") trim(basis)
      write (unit, "(I0,1X,I0,1X,I0)") mol%nao, scf%n_occupied, n_core
      write (unit, "(I0)") n_lmo
      write (unit, "(es25.16e3)") scf%energy
      write (unit, "(3es25.16e3)") alpha
      write (unit, "(3es25.16e3)") centroids
      write (unit, "(3es25.16e3)") tensors
      close (unit)

      write (*, "(A,A8,A,I0,A,I0,A,F12.6,A,ES9.2,A,F8.4)") &
         "  ", trim(basis), "  n_core ", n_core, "  LMOs ", n_lmo, &
         "   sum alpha_iso ", (total(1, 1) + total(2, 2) + total(3, 3))/3.0_dp, &
         "   sum asym ", sum_asym, "   worst single asym ", worst_single

      call mol%destroy()
      deallocate (tensors, centroids)
   end subroutine one_case

end program check_distributed_polarizability
