!! Parser for MQC section-based input files (.mqc format)
module mqc_config_parser
   !! Parses section-based input files with %section...end blocks
   !! This is the new format generated by mqc_prep.py
   use pic_types, only: dp, int32, int64
   use mqc_method_types, only: parse_method_string, METHOD_TYPE_UNKNOWN
   use mqc_calc_types, only: calc_type_from_string, CALC_TYPE_UNKNOWN
   use mqc_geometry, only: geometry_type
   use mqc_error, only: error_t, ERROR_IO, ERROR_PARSE, ERROR_VALIDATION
   use mqc_config_types, only: mqc_config_t, molecule_t, input_fragment_t, bond_t
   implicit none
   private

   public :: read_mqc_file
   ! Re-exported so the submodules under parsers/ reach them by host
   ! association, and so existing consumers keep a single import.
   public :: mqc_config_t, input_fragment_t, bond_t, molecule_t

   ! Maximum line length for reading (shared with submodules)
   integer, parameter, public :: MAX_LINE_LEN = 1024

   ! Utility functions shared with submodules
   public :: strip_comment, skip_to_end



   ! Interfaces for submodule procedures
   interface
      ! Basic section parsers (mqc_config_parser_basic_sections)
      module subroutine parse_schema_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_schema_section

      module subroutine parse_model_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_model_section

      module subroutine parse_driver_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_driver_section

      module subroutine parse_scf_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_scf_section

      module subroutine parse_xtb_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_xtb_section

      module subroutine parse_system_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_system_section

      ! Structure & geometry parsers (mqc_config_parser_structure)
      module subroutine parse_structure_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_structure_section

      module subroutine parse_geometry_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_geometry_section

      module subroutine parse_structure_generic(unit, charge, multiplicity, error)
         implicit none
         integer, intent(in) :: unit
         integer, intent(inout) :: charge, multiplicity
         type(error_t), intent(out) :: error
      end subroutine parse_structure_generic

      module subroutine parse_geometry_generic(unit, geom, error)
         use mqc_geometry, only: geometry_type
         implicit none
         integer, intent(in) :: unit
         type(geometry_type), intent(inout) :: geom
         type(error_t), intent(out) :: error
      end subroutine parse_geometry_generic

      ! Fragments & connectivity parsers (mqc_config_parser_fragments)
      module subroutine parse_fragments_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_fragments_section

      module subroutine parse_connectivity_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_connectivity_section

      module subroutine parse_fragments_generic(unit, nfrag, fragments, error)
         implicit none
         integer, intent(in) :: unit
         integer, intent(inout) :: nfrag
         type(input_fragment_t), allocatable, intent(inout) :: fragments(:)
         type(error_t), intent(out) :: error
      end subroutine parse_fragments_generic

      module subroutine parse_connectivity_generic(unit, nbonds, nbroken, bonds, error)
         use mqc_physical_fragment, only: bond_t
         implicit none
         integer, intent(in) :: unit
         integer, intent(inout) :: nbonds, nbroken
         type(bond_t), allocatable, intent(inout) :: bonds(:)
         type(error_t), intent(out) :: error
      end subroutine parse_connectivity_generic

      ! Calculation settings parsers (mqc_config_parser_calc_settings)
      module subroutine parse_hessian_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_hessian_section

      module subroutine parse_aimd_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_aimd_section

      module subroutine parse_fragmentation_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_fragmentation_section

      ! Molecules section parser (mqc_config_parser_molecules)
      module subroutine parse_molecules_section(unit, config, error)
         implicit none
         integer, intent(in) :: unit
         type(mqc_config_t), intent(inout) :: config
         type(error_t), intent(out) :: error
      end subroutine parse_molecules_section
   end interface

contains

   pure function strip_comment(line) result(stripped)
      !! Remove comments (! or #) from a line and trim result
      character(len=*), intent(in) :: line
      character(len=:), allocatable :: stripped
      integer :: comment_pos

      ! Find first occurrence of ! or #
      comment_pos = index(line, "!")
      if (comment_pos == 0) comment_pos = index(line, "#")

      if (comment_pos > 0) then
         ! Comment found - take everything before it
         stripped = trim(adjustl(line(1:comment_pos - 1)))
      else
         ! No comment - use full line
         stripped = trim(adjustl(line))
      end if
   end function strip_comment

   subroutine skip_to_end(unit, error)
      !! Skip lines until 'end' marker is found
      integer, intent(in) :: unit
      type(error_t), intent(out) :: error

      character(len=MAX_LINE_LEN) :: line
      integer :: io_stat
      do
         read (unit, "(A)", iostat=io_stat) line
         if (io_stat /= 0) then
            call error%set(ERROR_IO, "Unexpected end of file while skipping section")
            return
         end if

         line = adjustl(line)
         if (trim(strip_comment(line)) == "end") exit
      end do

   end subroutine skip_to_end



   subroutine read_mqc_file(filename, config, error)
      !! Read and parse a .mqc format input file
      character(len=*), intent(in) :: filename
      type(mqc_config_t), intent(out) :: config
      type(error_t), intent(out) :: error

      integer :: unit, io_stat
      character(len=MAX_LINE_LEN) :: line
      logical :: file_exists
      type(error_t) :: parse_error

      inquire (file=filename, exist=file_exists)
      if (.not. file_exists) then
         call error%set(ERROR_IO, "Input file not found: "//trim(filename))
         return
      end if

      open (newunit=unit, file=filename, status="old", action="read", iostat=io_stat)
      if (io_stat /= 0) then
         call error%set(ERROR_IO, "Error opening input file: "//trim(filename))
         return
      end if

      ! Set defaults
      config%log_level = "info"
      config%fragment_breakdown = "csv"

      ! Read file line by line and dispatch to section parsers
      do
         read (unit, "(A)", iostat=io_stat) line
         if (io_stat /= 0) exit

         line = adjustl(line)
         if (len_trim(line) == 0) cycle
         if (line(1:1) == "#" .or. line(1:1) == "!") cycle

         ! Check for section start
         if (line(1:1) == "%") then
            select case (trim(line))
            case ("%schema")
               call parse_schema_section(unit, config, parse_error)
            case ("%model")
               call parse_model_section(unit, config, parse_error)
            case ("%driver")
               call parse_driver_section(unit, config, parse_error)
            case ("%structure")
               call parse_structure_section(unit, config, parse_error)
            case ("%geometry")
               call parse_geometry_section(unit, config, parse_error)
            case ("%fragments")
               call parse_fragments_section(unit, config, parse_error)
            case ("%connectivity")
               call parse_connectivity_section(unit, config, parse_error)
            case ("%scf")
               call parse_scf_section(unit, config, parse_error)
            case ("%xtb")
               call parse_xtb_section(unit, config, parse_error)
            case ("%hessian")
               call parse_hessian_section(unit, config, parse_error)
            case ("%aimd")
               call parse_aimd_section(unit, config, parse_error)
            case ("%fragmentation")
               call parse_fragmentation_section(unit, config, parse_error)
            case ("%system")
               call parse_system_section(unit, config, parse_error)
            case ("%molecules")
               call parse_molecules_section(unit, config, parse_error)
            case default
               ! Skip unknown sections
               call skip_to_end(unit, parse_error)
            end select

            if (parse_error%has_error()) then
               error = parse_error
               call error%add_context("mqc_config_parser:read_mqc_file")
               close (unit)
               return
            end if
         end if
      end do

      close (unit)

      ! Validate required fields
      if (.not. allocated(config%schema_name)) then
         call error%set(ERROR_VALIDATION, "Missing required section: %schema")
         return
      end if

      ! Validate geometry: required for single-molecule mode, not for multi-molecule mode
      if (config%nmol == 0) then
         ! Single molecule mode: require top-level geometry
         if (.not. allocated(config%geometry%coords) .or. config%geometry%natoms == 0) then
            call error%set(ERROR_VALIDATION, "Missing required section: %geometry")
            return
         end if
      else
         ! Multi-molecule mode: each molecule must have geometry (validated during parsing)
         ! No additional validation needed here
      end if

   end subroutine read_mqc_file







end module mqc_config_parser
