add_subdirectory(basis)
add_subdirectory(cli)
add_subdirectory(core)
add_subdirectory(fragmentation)
add_subdirectory(interface)
add_subdirectory(io)
add_subdirectory(methods)
add_subdirectory(optimization)
add_subdirectory(parallel)
add_subdirectory(properties)
add_subdirectory(utils)
add_subdirectory(vibrational)
target_sources(${main_lib} PRIVATE mqc_calc_types.f90 mqc_method_types.f90
                                   mqc_driver.f90)
