#!/usr/bin/env python3
"""Generate the CPU (libcint) validation table from PySCF.

Writes, under ``validation/``:

* ``inputs/sample_inputs/<molecule>.xyz`` -- one geometry per molecule
* ``inputs/cpu_<molecule>_<basis>.json`` -- one metalquicha deck per case
* ``validation_tests_cpu.json``          -- the manifest, with PySCF energies

Nothing here is hand-maintained: edit ``MOLECULES`` or ``SWEEPS`` and rerun.
See README.md for how and why.

The reference energies are PySCF RHF driven with the *same* basis JSON that
metalquicha reads out of ``basis_sets/``, converted in ``bse_to_pyscf``. Using
PySCF's own basis library instead would disagree in the 8th decimal on some
sets, because the two tables are rounded differently -- which looks exactly
like a bug and is not one.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
BASIS_DIR = REPO / "basis_sets"
VALIDATION = REPO / "validation"
INPUTS = VALIDATION / "inputs"
XYZ_DIR = INPUTS / "sample_inputs"
MANIFEST = VALIDATION / "validation_tests_cpu.json"

TOLERANCE = 1e-6

DESCRIPTION = (
    "CPU Hartree-Fock through the libcint backend. Reference energies are PySCF "
    "RHF on the same geometry and the same basis JSON out of basis_sets/, not "
    "values this program produced -- a manifest of its own output would only "
    "detect change, not error. Generated by tools/cpu_validation; do not edit by "
    "hand. Kept separate from validation_tests.json because that one is xTB and "
    "needs tblite, while these need libcint and nothing else. The angular form "
    "of each reference follows the basis rather than being assumed: the "
    "polarised Pople sets are Cartesian, six d functions rather than five, and "
    "computing one as the other is 1.4 mHartree on water under a basis name "
    "that means the opposite. Reading the exponents out of basis_sets/ rather "
    "than PySCF's own tables matters most for these same sets -- BSE writes "
    "them to ten significant figures and PySCF carries more, which alone is "
    "worth 1e-7 and looks exactly like a bug in whichever code is checked."
)


# --------------------------------------------------------------------------
# geometry helpers -- all distances in Angstrom, all species closed shell
# --------------------------------------------------------------------------

def atom(sym):
    return [(sym, 0.0, 0.0, 0.0)]


def diatomic(a, b, r):
    return [(a, 0.0, 0.0, 0.0), (b, 0.0, 0.0, r)]


def linear_ah2(a, h, r):
    """D_inf_h AH2, e.g. BeH2."""
    return [(a, 0.0, 0.0, 0.0), (h, 0.0, 0.0, r), (h, 0.0, 0.0, -r)]


def bent_ah2(a, h, r, angle):
    """C2v AH2 with the given H-A-H angle in degrees."""
    half = math.radians(angle) / 2.0
    x, z = r * math.sin(half), r * math.cos(half)
    return [(a, 0.0, 0.0, 0.0), (h, x, 0.0, z), (h, -x, 0.0, z)]


def planar_ah3(a, h, r):
    """D3h AH3, e.g. BH3 and AlH3."""
    out = [(a, 0.0, 0.0, 0.0)]
    for k in range(3):
        phi = 2.0 * math.pi * k / 3.0
        out.append((h, r * math.cos(phi), r * math.sin(phi), 0.0))
    return out


def pyramidal_ah3(a, h, r, angle):
    """C3v AH3 with the given H-A-H angle in degrees.

    For unit H vectors at polar angle beta and azimuths 0/120/240,
    cos(H-A-H) = 1 - 1.5 sin^2(beta), which inverts to the sin_b below.
    """
    sin_b = math.sqrt((1.0 - math.cos(math.radians(angle))) / 1.5)
    cos_b = math.sqrt(max(0.0, 1.0 - sin_b * sin_b))
    out = [(a, 0.0, 0.0, 0.0)]
    for k in range(3):
        phi = 2.0 * math.pi * k / 3.0
        out.append((h, r * sin_b * math.cos(phi), r * sin_b * math.sin(phi), r * cos_b))
    return out


def tetrahedral_ah4(a, h, r):
    """T_d AH4, e.g. CH4 and SiH4."""
    d = r / math.sqrt(3.0)
    corners = [(1, 1, 1), (1, -1, -1), (-1, 1, -1), (-1, -1, 1)]
    return [(a, 0.0, 0.0, 0.0)] + [(h, d * x, d * y, d * z) for x, y, z in corners]


# --------------------------------------------------------------------------
# the molecules -- one closed-shell species per element H through Ar
# --------------------------------------------------------------------------

@dataclass
class Molecule:
    label: str
    element: str
    atoms: list = field(default_factory=list)
    #: set when the geometry already exists in the tree and must not be rewritten
    xyz: str = ""


def _mol(label, element, atoms):
    return Molecule(label=label, element=element, atoms=atoms)


MOLECULES = {
    # element  species                                    bond lengths are
    #                                                     near-experimental
    "h2": _mol("H2", "H", diatomic("H", "H", 0.7414)),
    "lih": _mol("LiH", "Li", diatomic("Li", "H", 1.5957)),
    "beh2": _mol("BeH2", "Be", linear_ah2("Be", "H", 1.3264)),
    "bh3": _mol("BH3", "B", planar_ah3("B", "H", 1.1900)),
    "ch4": _mol("CH4", "C", tetrahedral_ah4("C", "H", 1.0870)),
    "nh3": _mol("NH3", "N", pyramidal_ah3("N", "H", 1.0124, 106.67)),
    # water reuses the geometry the pre-existing decks already point at
    "water": Molecule(label="H2O", element="O", xyz="sample_inputs/w1.xyz"),
    "hf": _mol("HF", "F", diatomic("F", "H", 0.9168)),
    "ne": _mol("Ne", "Ne", atom("Ne")),
    "nah": _mol("NaH", "Na", diatomic("Na", "H", 1.8874)),
    "mgh2": _mol("MgH2", "Mg", linear_ah2("Mg", "H", 1.7000)),
    "alh3": _mol("AlH3", "Al", planar_ah3("Al", "H", 1.5840)),
    "sih4": _mol("SiH4", "Si", tetrahedral_ah4("Si", "H", 1.4798)),
    "ph3": _mol("PH3", "P", pyramidal_ah3("P", "H", 1.4200, 93.50)),
    "h2s": _mol("H2S", "S", bent_ah2("S", "H", 1.3356, 92.11)),
    "hcl": _mol("HCl", "Cl", diatomic("Cl", "H", 1.2746)),
    # Open-shell species. Geometries already in the tree, so they are read
    # rather than written; both are radicals and appear only in OPEN_SHELL.
    "oh": Molecule(label="OH", element="O", xyz="sample_inputs/oh.xyz"),
    # Two of prism's waters, for the fragmented cases below.
    "w2dimer": Molecule(label="(H2O)2", element="O", xyz="sample_inputs/w2_dimer.xyz"),
    "o2": Molecule(label="O2", element="O", xyz="sample_inputs/o2.xyz"),
    "ar": _mol("Ar", "Ar", atom("Ar")),
}

ALL = [m for m in MOLECULES if m not in ("oh", "o2", "w2dimer")]

# --------------------------------------------------------------------------
# the sweeps -- what each one is here to exercise
# --------------------------------------------------------------------------

POLAR = ["h2", "ch4", "nh3", "water", "hf", "ne", "sih4", "ph3", "h2s", "hcl", "ar"]

SWEEPS = [
    # minimal, SP-contracted shells, every element H-Ar
    ("sto-3g", ALL),
    # split valence, segmented, SP-contracted, every element H-Ar
    ("3-21g", ALL),
    ("6-31g", ALL),
    # general contraction (several coefficient columns on one l), through d
    ("cc-pvdz", ALL),
    # general contraction carried up to f shells. Not the whole element range:
    # cc-pVTZ on the second row costs 9-30 s a case here (SiH4 alone is 30 s),
    # which is too slow for CI. Ar keeps one second-row general contraction
    # with f in the suite at 4 s, and def2-TZVP below covers Al-Ar's f shells.
    ("cc-pvtz", ["h2", "lih", "beh2", "bh3", "nh3", "water", "hf", "ne", "ar"]),
    # diffuse functions
    ("aug-cc-pvdz", ["h2", "ch4", "nh3", "water", "hf", "ne", "h2s", "hcl"]),
    # Karlsruhe contraction pattern, through d
    ("def2-svp", POLAR),
    # Karlsruhe, f shells on B-Ne and Al-Ar, and far cheaper than cc-pVTZ
    ("def2-tzvp", ALL),
    # The Cartesian convention. BSE marks the polarisation shells of the
    # polarised Pople sets "gto_cartesian" on every element from lithium up, so
    # these are the only sweeps here whose reference is built with cart=True --
    # and the only ones that would come back wrong if the reader stopped reading
    # function_type. The two differ on hydrogen: 6-31G* leaves it unpolarised,
    # which makes H2 the one case in either sweep with no Cartesian shell in it
    # at all, and so the one that exercises the undecided form.
    ("6-31g*", ALL),
    ("6-31g**", ALL),
]

# Density fitting, as (molecule, orbital basis, auxiliary basis). A separate
# list because it is a different code path rather than a wider sweep of the same
# one -- the three-centre and two-centre integrals, and the fitting solve, none
# of which the exact cases above touch.
#
# The Cartesian entry fits 6-31G* with itself. That is a poor fitting set and a
# fine test: every JKFIT set shipped here is spherical, and the fitting integrals
# are built in one angular form for all three centres, so a Cartesian orbital
# basis has no shipped auxiliary to pair with. Using it as its own is the only
# way to reach the Cartesian three-centre entry points at all.
# Open shell, as (molecule, basis, multiplicity). These are the unrestricted
# path: two Fock matrices sharing one Coulomb field. A closed-shell system run
# unrestricted is a different and weaker test -- it converges to the restricted
# answer, so it checks the plumbing and not the physics -- and it is covered by
# a unit test rather than here.
OPEN_SHELL = [
    ("oh", "sto-3g", 2),
    ("oh", "cc-pvdz", 2),
    # The case that found the DIIS start delay. Extrapolating from the first
    # iteration converged it to a sigma-hole state 158 mHartree above the
    # pi-hole ground state, with the pi pair still degenerate to six digits --
    # a symmetric guess plus a linear extrapolation never leaves the symmetric
    # subspace. Worth keeping in the suite precisely because it converged
    # tidily while being wrong.
    ("oh", "def2-svp", 2),
    ("o2", "cc-pvdz", 3),
]

# Second-order perturbation theory, as (molecule, basis, method, frozen).
#
# `frozen` is written into the deck explicitly rather than left to the default,
# and the reference is generated with the same count. Most programs freeze the
# core by default and this one does too, but a frozen energy compared against
# an unfrozen one differs by a couple of millihartree -- inside no tolerance
# worth having, and for a reason that has nothing to do with the code.
#
# The scaled variants share their reference with plain MP2 by construction:
# SCS is 1.2 E_OS + E_SS/3 and SOS is 1.3 E_OS, both computed from the same
# two components. They are here because the *dispatch* is what can break --
# "scs-mp2" parses to the same method type as "mp2", so a deck asking for it
# could run unscaled and report it as scaled, and only an end-to-end case
# catches that.
MP2_CASES = [
    ("water", "sto-3g", "mp2", 0),
    ("water", "cc-pvdz", "mp2", 0),
    ("water", "cc-pvdz", "mp2", 1),
    ("water", "cc-pvdz", "scs-mp2", 1),
    ("water", "cc-pvdz", "sos-mp2", 1),
    ("water", "def2-svp", "mp2", 1),
    ("ch4", "cc-pvdz", "mp2", 1),
    ("nh3", "cc-pvdz", "mp2", 1),
]

# Fragmented, as (molecule, basis, method, frozen, fragments).
#
# The reference is the supermolecule, and that is not an approximation being
# waved through: a many-body expansion truncated at the number of monomers it
# has is exact. Over two fragments E_1 + E_2 + (E_12 - E_1 - E_2) collapses to
# E_12 term by term, whatever the method, so a fragmented MBE(2) run here has
# to reproduce the supermolecular MP2 to machine precision or the expansion is
# wrong.
#
# That is what makes this checkable at all. A prism at MBE(2) has no external
# reference short of running the whole thing, and comparing the expansion to
# its own output would only detect change.
#
# It also exercises a path the unfragmented cases do not: the runner gives
# fragmented cases several MPI ranks, so this covers fragment distribution as
# well as the correlation energy surviving the expansion.
# Density-fitted MP2, as (molecule, orbital basis, auxiliary basis, frozen).
#
# The auxiliary sets here are RIFIT, which is what fits a (ia|jb) block. A
# JKFIT set is fitted for the Coulomb and exchange matrices instead; the code
# accepts one and warns, and that is deliberately not covered by a reference
# case -- the point of the warning is that the number is poor, and pinning a
# poor number teaches nothing.
# Decks under inputs/ that this script must not delete. They are inputs to other
# things -- run_cpu_guess_comparison.sh drives the peptide one across all four
# initial guesses -- and are not validation cases, so they have no reference
# energy and no entry in the manifest. Without this they match the cpu_*.json
# sweep below and vanish on the next regeneration.
HAND_MAINTAINED = {
    "cpu/mqc/rhf/cpu_peptide46_sto-3g.json",
}

# Coupled cluster. Small on purpose: the spin-orbital tensor is (2 n_act)^4, so
# water/cc-pVDZ is 42 MB and anything much larger stops being a validation case
# and starts being a benchmark. Both spellings appear because they are separate
# method types, and a deck asking for "ccsd(t)" that quietly ran CCSD would agree
# with a CCSD reference perfectly.
CC_CASES = [
    ("water", "sto-3g", "ccsd", 0),
    ("water", "sto-3g", "ccsd(t)", 0),
    ("water", "cc-pvdz", "ccsd", 1),
    ("water", "cc-pvdz", "ccsd(t)", 1),
    ("ch4", "sto-3g", "ccsd(t)", 1),
]

# RI coupled cluster. The reference fits every MO integral class, not only the
# particle-particle ladder -- pyscf.cc.dfccsd's ao2mo returns _make_df_eris, which
# builds oooo, ovov, ovvo, oovv and ovvv from the fitted tensor -- so ours does
# too, and the (T) is fitted along with the rest because ccsd_t consumes that same
# object. Fitting a different set would leave us ~1e-5 away permanently.
RI_CC_CASES = [
    ("water", "sto-3g", "cc-pvdz-rifit", "ccsd", 0),
    ("water", "cc-pvdz", "cc-pvdz-rifit", "ccsd", 1),
    ("water", "cc-pvdz", "cc-pvdz-rifit", "ccsd(t)", 1),
]

RI_MP2_CASES = [
    ("water", "cc-pvdz", "cc-pvdz-rifit", 0),
    ("water", "cc-pvdz", "cc-pvdz-rifit", 1),
    ("water", "def2-svp", "def2-svp-rifit", 1),
    ("ch4", "cc-pvdz", "cc-pvdz-rifit", 1),
]

FRAGMENTED_CASES = [
    ("w2dimer", "cc-pvdz", "mp2", 2, [[0, 1, 2], [3, 4, 5]]),
]

DF_CASES = [
    ("water", "cc-pvdz", "cc-pvdz-rifit"),
    ("water", "def2-svp", "def2-universal-jkfit"),
    ("water", "6-31g*", "6-31g*"),
    ("ch4", "6-31g**", "6-31g**"),
]

# Cases whose deck already exists in the tree and is referenced from elsewhere
# (run_cuest_validation.sh, run_guess_comparison.sh). Reuse rather than
# duplicate them; the generator still produces their reference energies.
DECK_OVERRIDES = {
    ("water", "sto-3g"): "inputs/cpu/mqc/rhf/hf_water_sto-3g.json",
    ("water", "cc-pvdz"): "inputs/cpu/mqc/rhf/hf_water_cc-pvdz.json",
    ("water", "def2-svp"): "inputs/cpu/mqc/rhf/hf_water_def2-svp.json",
}

# Where each theory's decks live under inputs/. One directory per method, so
# `ls` answers "what is covered" instead of scrolling past two hundred files.
#
# The tree is inputs/<hardware>/<engine>/<method>/, which is three levels down
# from inputs/ -- and `sample_inputs/` deliberately stays at inputs/, shared by
# every backend, so a deck reaches its geometry with XYZ_UP. Nothing here holds
# an absolute path; the `xyz` field in a deck is resolved relative to the deck.
CPU_MQC = "cpu/mqc"
XYZ_UP = "../../../"


def _write_deck(path, text):
    """Write a deck, creating its directory. Keeps every emitter to one line."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def deck_for(subdir, stem):
    """Path of a deck, relative to validation/."""
    return f"inputs/{subdir}/{stem}.json"


def xyz_for(mol):
    """How a deck three levels down refers to a shared geometry."""
    return XYZ_UP + mol.xyz


# --------------------------------------------------------------------------
# basis handling
# --------------------------------------------------------------------------

def normalize_basis_name(name):
    """Mirror normalize_basis_name in src/basis/mqc_basis_utils.F90."""
    return name.lower().replace("*", "_st_").replace(" ", "")


#: the three angular forms, mirroring mqc_cgto.f90
UNSET, SPHERICAL, CARTESIAN = "unset", "spherical", "cartesian"


def shell_form(sh):
    """What one BSE shell entry's function_type says about the angular form.

    Mirrors shell_angular_form in mqc_json_basis_reader.f90, including the two
    rules that are easy to get subtly wrong. A shell at or below p is undecided
    whatever it is labelled, because s and p carry the same count either way.
    Above p, anything not spelled exactly "gto_cartesian" -- including the bare
    "gto" that most sets use -- is spherical.
    """
    if max(sh["angular_momentum"]) <= 1:
        return UNSET
    return CARTESIAN if sh.get("function_type") == "gto_cartesian" else SPHERICAL


def element_form(basis, symbol):
    """The angular form of one element, or UNSET if it has no shell above p."""
    from pyscf import gto

    path = BASIS_DIR / f"{normalize_basis_name(basis)}.json"
    with open(path) as fh:
        data = json.load(fh)
    shells = data["elements"][str(gto.charge(symbol))]["electron_shells"]
    forms = {shell_form(sh) for sh in shells} - {UNSET}
    if len(forms) > 1:
        raise SystemExit(
            f"{basis} {symbol}: mixes {' and '.join(sorted(forms))} shells; "
            "metalquicha refuses this element rather than picking one"
        )
    return forms.pop() if forms else UNSET


def molecule_form(basis, symbols):
    """The one form the whole molecule is built in.

    Undecided elements do not vote: hydrogen in 6-31G* has no shell above s, and
    counting it as spherical would put it in conflict with the oxygen it is
    bonded to and refuse water outright.
    """
    forms = {element_form(basis, s) for s in symbols} - {UNSET}
    if len(forms) > 1:
        raise SystemExit(f"{basis}: elements disagree on the angular form")
    return forms.pop() if forms else UNSET


def bse_to_pyscf(basis, symbol):
    """Convert one element out of a BSE JSON file into PySCF's basis format.

    The shell rule matches mqc_json_basis_reader.f90: one shell per coefficient
    column. When there are as many angular momenta as columns the shell is an
    SP-type block and each column takes its own l; otherwise every column is a
    contraction of the single l, i.e. a general contraction.
    """
    from pyscf import gto

    z = gto.charge(symbol)
    path = BASIS_DIR / f"{normalize_basis_name(basis)}.json"
    if not path.exists():
        raise SystemExit(f"missing basis file {path}; configure CMake to extract it")
    with open(path) as fh:
        data = json.load(fh)
    if str(z) not in data["elements"]:
        raise SystemExit(f"{basis} has no element {symbol}")

    shells = []
    for sh in data["elements"][str(z)]["electron_shells"]:
        momenta = sh["angular_momentum"]
        exps = [float(x) for x in sh["exponents"]]
        cols = sh["coefficients"]
        if len(momenta) == len(cols):
            for l, col in zip(momenta, cols):
                shells.append([l] + [[e, float(c)] for e, c in zip(exps, col)])
        elif len(momenta) == 1:
            l = momenta[0]
            shells.append(
                [l] + [[e] + [float(col[i]) for col in cols] for i, e in enumerate(exps)]
            )
        else:
            raise SystemExit(
                f"{basis} {symbol}: {len(momenta)} angular momenta, {len(cols)} columns"
            )
    return shells


# --------------------------------------------------------------------------
# emitters
# --------------------------------------------------------------------------

def read_xyz(path):
    lines = path.read_text().splitlines()
    n = int(lines[0].split()[0])
    out = []
    for line in lines[2:2 + n]:
        f = line.split()
        out.append((f[0], float(f[1]), float(f[2]), float(f[3])))
    return out


def write_xyz(path, mol):
    body = [f"{len(mol.atoms)}", f"{mol.label} generated by tools/cpu_validation"]
    for sym, x, y, z in mol.atoms:
        body.append(f"{sym:<3s} {x:22.14f} {y:22.14f} {z:22.14f}")
    path.write_text("\n".join(body) + "\n")


def deck_json(xyz_rel, basis, aux="", multiplicity=1, method="hf", correlation=None,
              cc=None):
    model = {"method": method, "basis": basis}
    if aux:
        model["aux_basis"] = aux
    deck = {
        "schema": {"name": "mqc-frag", "version": "1.0"},
        "molecules": [
            {"xyz": xyz_rel, "molecular_charge": 0,
             "molecular_multiplicity": multiplicity}
        ],
        "model": model,
        "keywords": {"scf": {"maxiter": 100, "tolerance": 1e-08}},
        "system": {"logger": {"level": "Verbose"}},
        "driver": "Energy",
    }
    if aux:
        deck["keywords"]["scf"]["density_fitting"] = True
    if correlation:
        deck["keywords"]["correlation"] = correlation
    if cc:
        deck["keywords"]["cc"] = cc
    return deck


def pyscf_ri_mp2(atoms, basis, aux, frozen):
    """Reference DF-MP2 total energy, fitted with the given auxiliary basis.

    Compared against PySCF's own density-fitted MP2 rather than against exact
    MP2: agreeing with the exact answer to the fitting error would only say the
    fitting error is the usual size, not that the same fitted quantity is being
    computed. These agree to 1e-10, which is the stronger statement.
    """
    from pyscf import gto, scf, mp

    mol = gto.Mole()
    mol.atom = [(s, (x, y, z)) for s, x, y, z in atoms]
    mol.unit = "Angstrom"
    symbols = {a[0] for a in atoms}
    mol.basis = {s: bse_to_pyscf(basis, s) for s in symbols}
    mol.charge = 0
    mol.spin = 0
    mol.cart = molecule_form(basis, symbols) == CARTESIAN
    mol.verbose = 0
    mol.build()
    mf = scf.RHF(mol)
    mf.conv_tol = 1e-12
    escf = mf.kernel()
    pt = mp.dfmp2.DFMP2(mf, frozen=frozen)
    pt.with_df = pt.with_df.__class__(mol, auxbasis={s: bse_to_pyscf(aux, s) for s in symbols})
    ecorr, _ = pt.kernel()
    return float(escf + ecorr), mol.nao


def pyscf_mp2(atoms, basis, method, frozen):
    """Reference MP2 total energy, scaled the way the method name says."""
    from pyscf import gto, scf, mp

    mol = gto.Mole()
    mol.atom = [(s, (x, y, z)) for s, x, y, z in atoms]
    mol.unit = "Angstrom"
    symbols = {a[0] for a in atoms}
    mol.basis = {s: bse_to_pyscf(basis, s) for s in symbols}
    mol.charge = 0
    mol.spin = 0
    mol.cart = molecule_form(basis, symbols) == CARTESIAN
    mol.verbose = 0
    mol.build()
    mf = scf.RHF(mol)
    mf.conv_tol = 1e-12
    escf = mf.kernel()
    pt = mp.MP2(mf, frozen=frozen)
    pt.kernel()
    # Recombined here rather than taken from pt.e_corr, so the factors this
    # suite checks against are written down where they can be read.
    if method == "scs-mp2":
        ecorr = 1.2*pt.e_corr_os + pt.e_corr_ss/3.0
    elif method == "sos-mp2":
        ecorr = 1.3*pt.e_corr_os
    else:
        ecorr = pt.e_corr_os + pt.e_corr_ss
    return float(escf + ecorr), mol.nao


def pyscf_cc(atoms, basis, method, frozen):
    """Reference CCSD or CCSD(T) total energy.

    The triples come from ``ccsd_t()`` rather than from a CCSD(T) driver, which
    is what PySCF offers and what ``validation/check_cc.f90`` compares against
    too -- the two references being produced the same way is the point.
    """
    from pyscf import cc, gto, scf

    mol = gto.Mole()
    mol.atom = [(s, (x, y, z)) for s, x, y, z in atoms]
    mol.unit = "Angstrom"
    symbols = {a[0] for a in atoms}
    mol.basis = {s: bse_to_pyscf(basis, s) for s in symbols}
    mol.charge = 0
    mol.spin = 0
    mol.cart = molecule_form(basis, symbols) == CARTESIAN
    mol.verbose = 0
    mol.build()
    mf = scf.RHF(mol)
    mf.conv_tol = 1e-12
    escf = mf.kernel()
    mycc = cc.CCSD(mf, frozen=frozen)
    mycc.conv_tol = 1e-11
    mycc.kernel()
    ecorr = mycc.e_corr
    if method == "ccsd(t)":
        ecorr += mycc.ccsd_t()
    return float(escf + ecorr), mol.nao


def pyscf_ri_cc(atoms, basis, aux, method, frozen):
    """Reference RI-CCSD / RI-CCSD(T), from pyscf.cc.dfccsd.

    Built on a *conventional* mean field so the number isolates the CC-side
    fitting. A density-fitted Hartree-Fock underneath would fold two different
    approximations into one comparison, and the SCF one is already covered by the
    density-fitted RHF cases.
    """
    from pyscf import gto, scf
    from pyscf.cc import dfccsd

    mol = gto.Mole()
    mol.atom = [(s, (x, y, z)) for s, x, y, z in atoms]
    mol.unit = "Angstrom"
    symbols = {a[0] for a in atoms}
    mol.basis = {s: bse_to_pyscf(basis, s) for s in symbols}
    mol.charge = 0
    mol.spin = 0
    mol.cart = molecule_form(basis, symbols) == CARTESIAN
    mol.verbose = 0
    mol.build()
    mf = scf.RHF(mol)
    mf.conv_tol = 1e-12
    escf = mf.kernel()
    mycc = dfccsd.RCCSD(mf, frozen=frozen)
    mycc.conv_tol = 1e-11
    mycc.with_df = mycc.with_df.__class__(
        mol, auxbasis={s: bse_to_pyscf(aux, s) for s in symbols})
    mycc.kernel()
    ecorr = mycc.e_corr
    if method == "ccsd(t)":
        ecorr += mycc.ccsd_t()
    return float(escf + ecorr), mol.nao


def pyscf_rhf(atoms, basis, aux="", multiplicity=1):
    from pyscf import df, gto, scf

    mol = gto.Mole()
    mol.atom = [(s, (x, y, z)) for s, x, y, z in atoms]
    mol.unit = "Angstrom"
    symbols = {a[0] for a in atoms}
    mol.basis = {s: bse_to_pyscf(basis, s) for s in symbols}
    mol.charge = 0
    mol.spin = multiplicity - 1
    # The basis decides, exactly as it does on the Fortran side. Hardcoding this
    # either way is the bug the 6-31G* sweeps are here to catch: spherical is
    # right for most of the table and silently wrong for the polarised Pople
    # sets, and a reference generated the wrong way round would bless it.
    mol.cart = molecule_form(basis, symbols) == CARTESIAN
    mol.verbose = 0
    mol.build()
    # UHF once the system is open shell, which is what the CPU backend does
    # too -- it goes unrestricted on multiplicity or an odd electron count
    # rather than on the keyword alone, so the reference has to follow the
    # same rule or the two disagree for a reason that is not the integrals.
    mf = scf.UHF(mol) if multiplicity != 1 else scf.RHF(mol)
    if aux:
        # All three centres of a fitting integral are built in one angular form,
        # so an auxiliary set of the other convention is not a reference to
        # compare against -- it is a different calculation. metalquicha refuses
        # the pairing outright; refuse it here too rather than generate a number
        # for it.
        if molecule_form(aux, symbols) != molecule_form(basis, symbols):
            raise SystemExit(
                f"{basis} is {molecule_form(basis, symbols)} and {aux} is "
                f"{molecule_form(aux, symbols)}; the two cannot be fitted together"
            )
        mf = df.density_fit(mf, auxbasis={s: bse_to_pyscf(aux, s) for s in symbols})
    mf.conv_tol = 1e-12
    energy = mf.kernel()
    if not mf.converged:
        raise SystemExit(f"PySCF RHF did not converge for {basis}")
    return float(energy), mol.nao


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true",
                    help="compute and print, write nothing")
    args = ap.parse_args()

    os.environ.setdefault("OMP_NUM_THREADS", "1")

    # geometries first, so PySCF and the decks cannot drift apart
    for name, mol in MOLECULES.items():
        if mol.xyz:
            mol.atoms = read_xyz(INPUTS / mol.xyz)
        else:
            mol.xyz = f"sample_inputs/{name}.xyz"
            if not args.dry_run:
                write_xyz(INPUTS / mol.xyz, mol)

    written = set()
    tests = []
    for basis, names in SWEEPS:
        stem = normalize_basis_name(basis)
        for name in names:
            mol = MOLECULES[name]
            energy, nao = pyscf_rhf(mol.atoms, basis)
            deck = DECK_OVERRIDES.get((name, basis), deck_for(f"{CPU_MQC}/rhf", f"cpu_{name}_{stem}"))
            # Recorded as produced even when it is an override, which is not the
            # same as being written. The sweep below deletes anything in the tree
            # that this run did not account for, and an override is accounted for
            # -- it is just maintained by hand rather than emitted here.
            written.add(str((VALIDATION / deck).relative_to(INPUTS)))
            if (name, basis) not in DECK_OVERRIDES:
                if not args.dry_run:
                    _write_deck(VALIDATION / deck,
                        json.dumps(deck_json(xyz_for(mol), basis), indent=4) + "\n"
                    )
            tests.append({
                "name": f"RHF {mol.label} {basis} (CPU)",
                "input": deck,
                "expected_energy": round(energy, 12),
                "type": "unfragmented",
            })
            print(f"{mol.label:6s} {basis:12s} nao={nao:4d} E={energy:.12f}", flush=True)

    for name, basis, aux in DF_CASES:
        mol = MOLECULES[name]
        energy, nao = pyscf_rhf(mol.atoms, basis, aux=aux)
        deck = deck_for(f"{CPU_MQC}/df-hf", f"cpu_{name}_{normalize_basis_name(basis)}_df")
        written.add(str((VALIDATION / deck).relative_to(INPUTS)))
        if not args.dry_run:
            _write_deck(VALIDATION / deck,
                json.dumps(deck_json(xyz_for(mol), basis, aux=aux), indent=4) + "\n"
            )
        tests.append({
            "name": f"RHF {mol.label} {basis} density fitted with {aux} (CPU)",
            "input": deck,
            "expected_energy": round(energy, 12),
            "type": "unfragmented",
        })
        print(f"{mol.label:6s} {basis:12s} df={aux:22s} E={energy:.12f}", flush=True)

    for name, basis, mult in OPEN_SHELL:
        mol = MOLECULES[name]
        energy, nao = pyscf_rhf(mol.atoms, basis, multiplicity=mult)
        deck = deck_for(f"{CPU_MQC}/uhf", f"cpu_{name}_{normalize_basis_name(basis)}_m{mult}")
        written.add(str((VALIDATION / deck).relative_to(INPUTS)))
        if not args.dry_run:
            _write_deck(VALIDATION / deck,
                json.dumps(deck_json(xyz_for(mol), basis, multiplicity=mult), indent=4) + "\n"
            )
        tests.append({
            "name": f"UHF {mol.label} {basis} multiplicity {mult} (CPU)",
            "input": deck,
            "expected_energy": round(energy, 12),
            "type": "unfragmented",
        })
        print(f"{mol.label:6s} {basis:12s} mult={mult}  nao={nao:4d} E={energy:.12f}", flush=True)

    for name, basis, method, frozen in MP2_CASES:
        mol = MOLECULES[name]
        energy, nao = pyscf_mp2(mol.atoms, basis, method, frozen)
        deck = deck_for(f"{CPU_MQC}/{method}", f"cpu_{name}_{normalize_basis_name(basis)}_{method}_f{frozen}")
        written.add(str((VALIDATION / deck).relative_to(INPUTS)))
        if not args.dry_run:
            _write_deck(VALIDATION / deck,
                json.dumps(deck_json(xyz_for(mol), basis, method=method,
                                     correlation={"freeze_core": frozen > 0,
                                                  "n_frozen_core": frozen}), indent=4) + "\n"
            )
        tests.append({
            "name": f"{method.upper()} {mol.label} {basis} frozen {frozen} (CPU)",
            "input": deck,
            "expected_energy": round(energy, 12),
            "type": "unfragmented",
        })
        print(f"{mol.label:6s} {basis:12s} {method:8s} frozen={frozen}  nao={nao:4d} E={energy:.12f}", flush=True)

    for name, basis, method, frozen in CC_CASES:
        mol = MOLECULES[name]
        energy, nao = pyscf_cc(mol.atoms, basis, method, frozen)
        tag = method.replace("(", "").replace(")", "")
        # "ccsd(t)" cannot be a directory name with brackets in it, so the
        # directory takes the hyphenated spelling while the file keeps the
        # bracket-free one it already had.
        deck = deck_for(f"{CPU_MQC}/" + method.replace("(", "-").replace(")", ""),
                        f"cpu_{name}_{normalize_basis_name(basis)}_{tag}_f{frozen}")
        written.add(str((VALIDATION / deck).relative_to(INPUTS)))
        if not args.dry_run:
            # A tighter amplitude tolerance than the default 1e-8, so the case
            # tests the equations rather than where the iteration was stopped.
            _write_deck(VALIDATION / deck,
                json.dumps(deck_json(xyz_for(mol), basis, method=method,
                                     correlation={"freeze_core": frozen > 0,
                                                  "n_frozen_core": frozen},
                                     cc={"tolerance": 1e-10}), indent=4) + "\n"
            )
        tests.append({
            "name": f"{method.upper()} {mol.label} {basis} frozen {frozen} (CPU)",
            "input": deck,
            "expected_energy": round(energy, 12),
            "type": "unfragmented",
        })
        print(f"{mol.label:6s} {basis:12s} {method:8s} frozen={frozen}  nao={nao:4d} E={energy:.12f}", flush=True)

    for name, basis, aux, method, frozen in RI_CC_CASES:
        mol = MOLECULES[name]
        energy, nao = pyscf_ri_cc(mol.atoms, basis, aux, method, frozen)
        tag = "ri" + method.replace("(", "").replace(")", "")
        deck = deck_for(f"{CPU_MQC}/ri-" + method.replace("(", "-").replace(")", ""),
                        f"cpu_{name}_{normalize_basis_name(basis)}_{tag}_f{frozen}")
        written.add(str((VALIDATION / deck).relative_to(INPUTS)))
        if not args.dry_run:
            _write_deck(VALIDATION / deck,
                json.dumps(deck_json(xyz_for(mol), basis, method="ri-" + method,
                                     correlation={"freeze_core": frozen > 0,
                                                  "n_frozen_core": frozen,
                                                  "aux_basis": aux},
                                     cc={"tolerance": 1e-10}), indent=4) + "\n"
            )
        tests.append({
            "name": f"RI-{method.upper()} {mol.label} {basis}/{aux} frozen {frozen} (CPU)",
            "input": deck,
            "expected_energy": round(energy, 12),
            "type": "unfragmented",
        })
        print(f"{mol.label:6s} {basis:12s} ri-{method:8s} frozen={frozen}  nao={nao:4d} E={energy:.12f}", flush=True)

    for name, basis, aux, frozen in RI_MP2_CASES:
        mol = MOLECULES[name]
        energy, nao = pyscf_ri_mp2(mol.atoms, basis, aux, frozen)
        deck = deck_for(f"{CPU_MQC}/ri-mp2", f"cpu_{name}_{normalize_basis_name(basis)}_rimp2_f{frozen}")
        written.add(str((VALIDATION / deck).relative_to(INPUTS)))
        if not args.dry_run:
            _write_deck(VALIDATION / deck,
                json.dumps(deck_json(xyz_for(mol), basis, method="ri-mp2",
                                     correlation={"freeze_core": frozen > 0,
                                                  "n_frozen_core": frozen,
                                                  "aux_basis": aux}), indent=4) + "\n"
            )
        tests.append({
            "name": f"RI-MP2 {mol.label} {basis}/{aux} frozen {frozen} (CPU)",
            "input": deck,
            "expected_energy": round(energy, 12),
            "type": "unfragmented",
        })
        print(f"{mol.label:6s} {basis:12s} ri-mp2/{aux:16s} frozen={frozen} E={energy:.12f}", flush=True)

    for name, basis, method, frozen, fragments in FRAGMENTED_CASES:
        mol = MOLECULES[name]
        energy, nao = pyscf_mp2(mol.atoms, basis, method, frozen)
        deck = deck_for(f"{CPU_MQC}/{method}", f"cpu_{name}_{normalize_basis_name(basis)}_{method}_mbe2")
        written.add(str((VALIDATION / deck).relative_to(INPUTS)))
        if not args.dry_run:
            d = deck_json(xyz_for(mol), basis, method=method,
                          correlation={"freeze_core": True})
            d["molecules"][0]["fragments"] = fragments
            d["molecules"][0]["fragment_charges"] = [0]*len(fragments)
            d["molecules"][0]["fragment_multiplicities"] = [1]*len(fragments)
            d["keywords"]["fragmentation"] = {
                "method": "MBE", "level": len(fragments),
                "allow_overlapping_fragments": False, "embedding": "none",
            }
            _write_deck(VALIDATION / deck, json.dumps(d, indent=4) + "\n")
        tests.append({
            "name": f"MBE({len(fragments)}) {method.upper()} {mol.label} {basis} (CPU)",
            "input": deck,
            "expected_energy": round(energy, 12),
            "type": "fragmented",
        })
        print(f"{mol.label:6s} {basis:12s} {method:8s} MBE({len(fragments)})  nao={nao:4d} E={energy:.12f}", flush=True)

    manifest = {"description": DESCRIPTION, "tolerance": TOLERANCE, "tests": tests}
    if args.dry_run:
        print(f"\n{len(tests)} cases (dry run, nothing written)")
        return 0

    # Drop decks left behind by an earlier, wider case list, so that what is on
    # disk is exactly what this script produces -- except the few that are
    # deliberately hand-maintained and merely happen to share the prefix.
    for stale in sorted((INPUTS / CPU_MQC).rglob("*.json")):
        rel = str(stale.relative_to(INPUTS))
        if rel in HAND_MAINTAINED:
            continue
        if rel not in written:
            stale.unlink()
            print(f"removed stale {rel}")
    # And drop directories the case list no longer produces anything for, so a
    # method that is removed does not leave an empty folder implying coverage.
    for d in sorted((INPUTS / CPU_MQC).glob("*"), reverse=True):
        if d.is_dir() and not any(d.iterdir()):
            d.rmdir()
            print(f"removed empty {d.relative_to(INPUTS)}")

    MANIFEST.write_text(json.dumps(manifest, indent=4) + "\n")
    print(f"\nwrote {MANIFEST} with {len(tests)} cases")
    return 0


if __name__ == "__main__":
    sys.exit(main())
